import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SB,KEY,{auth:{persistSession:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"GET,OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const ageMin=(v:any)=>v?Math.max(0,(Date.now()-new Date(v).getTime())/60000):null;
function marketHealth(s:any){const current=!!s&&s.last_m15_bar&&s.expected_last_completed_m15&&new Date(s.last_m15_bar).getTime()===new Date(s.expected_last_completed_m15).getTime();const clean=(Number(s?.gap_count_96||0)===0&&Number(s?.duplicate_count_96||0)===0&&Number(s?.structure_lag_bars||0)===0&&!s?.blocked_reason);const stateAge=ageMin(s?.updated_at);return{symbol:s?.symbol??null,status:current&&clean&&stateAge!=null&&stateAge<=12?"healthy":"attention",stateAgeMinutes:stateAge,lastCompletedM15:s?.last_m15_bar??null,expectedLastCompletedM15:s?.expected_last_completed_m15??null,gaps96:Number(s?.gap_count_96||0),duplicates96:Number(s?.duplicate_count_96||0),lagBars:Number(s?.structure_lag_bars||0),structureStatus:s?.structure_status??null,blockedReason:s?.blocked_reason??null,formationStage:s?.formation_stage??null,formationLabel:s?.formation_label??null,direction:s?.formation_direction??null,referencePrice:s?.reference_price??null};}
function jobHealth(j:any){const a=ageMin(j?.last_run_start);let max=12;if(String(j?.schedule||'').includes('* * * * *'))max=3;else if(String(j?.schedule||'').includes('/5'))max=8;else if(String(j?.schedule||'').includes('/10'))max=13;const ok=j?.active===true&&j?.last_run_status==='succeeded'&&a!=null&&a<=max;return{name:j?.jobname??null,schedule:j?.schedule??null,status:ok?"healthy":"attention",lastRunStatus:j?.last_run_status??null,lastRunAt:j?.last_run_start??null,lastRunAgeMinutes:a,active:j?.active===true};}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="GET")return J({error:"GET only"},405);try{const q=await db.rpc("v2_health_snapshot");if(q.error)throw new Error(q.error.message);const raw=q.data??{},markets=(raw.marketStates??[]).map(marketHealth),jobs=(raw.jobs??[]).map(jobHealth),discordHeartbeatAge=ageMin(raw.discord?.heartbeat_at),discord={status:discordHeartbeatAge!=null&&discordHeartbeatAge<=3?"healthy":"attention",heartbeatAt:raw.discord?.heartbeat_at??null,heartbeatAgeMinutes:discordHeartbeatAge,lastAlertSentAt:raw.discord?.last_alert_sent_at??null,lastAlertType:raw.discord?.last_alert_type??null,lastAlertSymbol:raw.discord?.last_alert_symbol??null,lastMessageId:raw.discord?.last_message_id??null},coreNames=new Set(["v2-paper-trade-engine-5m","v2-discord-fx-pulse-2m","v2-discord-fx-closures-5m","v2-discord-quality-2m","v2-eurusd-fast-canonical","v2-market-lab-refresh-5m"]),coreJobs=jobs.filter((x:any)=>coreNames.has(x.name)),overall=markets.every((x:any)=>x.status==='healthy')&&coreJobs.every((x:any)=>x.status==='healthy')&&discord.status==='healthy'?"healthy":"attention";return J({version:"V2 health v1",generatedAt:new Date().toISOString(),overall,market:markets,paper:{...raw.paperTrades,latestEventAt:raw.paperEvents?.latest_event_at??null,latestEventCreatedAt:raw.paperEvents?.latest_event_created??null},discord,executionAudit:raw.executionAudit,jobs,boundary:"Health checks monitor freshness and pipeline operation only; they do not alter V2 trading rules or paper results."});}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});
