import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SB,KEY,{auth:{persistSession:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"GET,OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const ageMin=(v:any)=>v?Math.max(0,(Date.now()-new Date(v).getTime())/60000):null;
function marketHealth(s:any){const current=!!s&&s.last_m15_bar&&s.expected_last_completed_m15&&new Date(s.last_m15_bar).getTime()===new Date(s.expected_last_completed_m15).getTime();const structuralGaps=Number(s?.structural_gap_count??s?.gap_count_96??0),diagnosticGaps=Number(s?.gap_count_96??0);const clean=(structuralGaps===0&&Number(s?.duplicate_count_96||0)===0&&Number(s?.structure_lag_bars||0)===0&&!s?.blocked_reason);const stateAge=ageMin(s?.updated_at);return{symbol:s?.symbol??null,status:current&&clean&&stateAge!=null&&stateAge<=12?"healthy":"attention",stateAgeMinutes:stateAge,lastCompletedM15:s?.last_m15_bar??null,expectedLastCompletedM15:s?.expected_last_completed_m15??null,gaps96:diagnosticGaps,structuralGaps32:structuralGaps,duplicates96:Number(s?.duplicate_count_96||0),lagBars:Number(s?.structure_lag_bars||0),structureStatus:s?.structure_status??null,blockedReason:s?.blocked_reason??null,formationStage:s?.formation_stage??null,formationLabel:s?.formation_label??null,direction:s?.formation_direction??null,referencePrice:s?.reference_price??null};}
function jobHealth(j:any){const a=ageMin(j?.last_run_start);let max=12;if(String(j?.schedule||'').includes('* * * * *'))max=3;else if(String(j?.schedule||'').includes('/5')||String(j?.schedule||'').includes('0,15,30,45'))max=8;else if(String(j?.schedule||'').includes('/10'))max=13;const ok=j?.active===true&&j?.last_run_status==='succeeded'&&a!=null&&a<=max;return{name:j?.jobname??null,schedule:j?.schedule??null,status:ok?"healthy":"attention",lastRunStatus:j?.last_run_status??null,lastRunAt:j?.last_run_start??null,lastRunAgeMinutes:a,active:j?.active===true};}
function fastHealth(rows:any[],activeCount:number){const xs=(rows??[]).map((x:any)=>{const age=ageMin(x.updated_at),active=!!x.active_trade_key,provider=String(x.provider_status??'');const providerOk=!active||provider==='bidask_ok'||provider==='mid_fallback'||provider==='idle';const ok=age!=null&&age<=3&&providerOk;return{symbol:x.symbol,status:ok?'healthy':'attention',mode:provider==='bidask_ok'?'BID/ASK fast execution':provider==='mid_fallback'?'1m indicative observer':provider==='idle'?'idle':'provider issue',heartbeatAgeMinutes:age,latestBar:x.latest_bar??null,activeTradeKey:x.active_trade_key??null,activeTradeStatus:x.active_trade_status??null,lastAction:x.last_action??null,providerStatus:provider,source:x.source??null,details:x.details??{}}});const expected=activeCount>0?xs.some((x:any)=>x.activeTradeKey):true;const ok=xs.length>=2&&xs.every((x:any)=>x.status==='healthy')&&expected;return{status:ok?'healthy':'attention',activeTrades:activeCount,symbols:xs,boundary:'Completed 1m observation is near-live. Only public BID/ASK confirmation can promote a fast paper fill; indicative mid-price fallback cannot change paper P&L.'};}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="GET")return J({error:"GET only"},405);try{const q=await db.rpc("v2_health_snapshot");if(q.error)throw new Error(q.error.message);const raw=q.data??{},markets=(raw.marketStates??[]).map(marketHealth),jobs=(raw.jobs??[]).map(jobHealth),discordHeartbeatAge=ageMin(raw.discord?.heartbeat_at),discord={status:discordHeartbeatAge!=null&&discordHeartbeatAge<=3?"healthy":"attention",heartbeatAt:raw.discord?.heartbeat_at??null,heartbeatAgeMinutes:discordHeartbeatAge,lastAlertSentAt:raw.discord?.last_alert_sent_at??null,lastAlertType:raw.discord?.last_alert_type??null,lastAlertSymbol:raw.discord?.last_alert_symbol??null,lastMessageId:raw.discord?.last_message_id??null},activeCount=Number(raw.paperTrades?.open_trades||0)+Number(raw.paperTrades?.active_armed||0),fast=fastHealth(raw.fastExecution??[],activeCount),coreNames=new Set(["v2-paper-trade-engine-5m","v2-paper-fast-execution-1m","v2-discord-fx-pulse-2m","v2-discord-fx-closures-5m","v2-discord-quality-2m","v2-eurusd-fast-canonical","v2-market-lab-refresh-5m"]),coreJobs=jobs.filter((x:any)=>coreNames.has(x.name)),overall=markets.every((x:any)=>x.status==='healthy')&&coreJobs.every((x:any)=>x.status==='healthy')&&discord.status==='healthy'&&fast.status==='healthy'?"healthy":"attention";return J({version:"V2 health v2.1",generatedAt:new Date().toISOString(),overall,market:markets,paper:{...raw.paperTrades,latestEventAt:raw.paperEvents?.latest_event_at??null,latestEventCreatedAt:raw.paperEvents?.latest_event_created??null},fastExecution:fast,discord,executionAudit:raw.executionAudit,jobs,boundary:"Health checks monitor freshness and pipeline operation only; GBPUSD keeps the 96-bar gap metric for diagnostics while the circuit breaker uses the latest 32 structural M15 bars. Trading rules and historical paper results are unchanged."});}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});
