import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import LZMA from "npm:lzma@2.3.2";

const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const SYMBOLS=["EURUSD","GBPUSD"],PIP=.0001,SRC="Dukascopy BID/ASK ticks";
const LOOKBACK_HOURS=30,MAX_REPAIR_HOURS_PER_SYMBOL=4,MIN_COMPLETE_MINUTES=55,CONCURRENCY=4;
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
type M={symbol:string;ts:string;bid_open:number;bid_high:number;bid_low:number;bid_close:number;ask_open:number;ask_high:number;ask_low:number;ask_close:number;spread_open_pips:number;spread_high_pips:number;spread_low_pips:number;spread_close_pips:number;spread_mean_pips:number;tick_count:number;ask_volume:number;bid_volume:number;source:string};
type Job={symbol:string;d:Date;reason:"live"|"repair"};
const hourMs=3600000;
const floorHour=(x:number)=>Math.floor(x/hourMs)*hourMs;
function path(d:Date){return`${d.getUTCFullYear()}/${String(d.getUTCMonth()).padStart(2,"0")}/${String(d.getUTCDate()).padStart(2,"0")}/${String(d.getUTCHours()).padStart(2,"0")}h_ticks.bi5`}
function fxOpenHour(ms:number){const d=new Date(ms),day=d.getUTCDay(),h=d.getUTCHours();if(day===6)return false;if(day===5&&h>=21)return false;if(day===0&&h<21)return false;return true}
async function fetchHour(symbol:string,d:Date){const r=await fetch(`https://datafeed.dukascopy.com/datafeed/${symbol}/${path(d)}`,{headers:{"User-Agent":"Mozilla/5.0 V2MicrostructureLive/3.0"},signal:AbortSignal.timeout(6500)});if(r.status===404)return[];if(!r.ok)throw Error(`${symbol} ${d.toISOString()} ${r.status}`);const enc=new Uint8Array(await r.arrayBuffer());if(!enc.length)return[];const raw:any=(LZMA as any).decompress(enc),bytes=raw instanceof Uint8Array?raw:new Uint8Array(raw),dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),m=new Map<number,any>();for(let o=0;o+20<=bytes.length;o+=20){const ofs=dv.getUint32(o,false),ask=dv.getUint32(o+4,false)/100000,bid=dv.getUint32(o+8,false)/100000,av=dv.getFloat32(o+12,false),bv=dv.getFloat32(o+16,false);if(!(ask>=bid&&bid>0&&ask-bid<.01))continue;const t=d.getTime()+ofs,k=Math.floor(t/60000)*60000;if(Date.now()<k+60000)continue;const sp=(ask-bid)/PIP,b=m.get(k);if(!b)m.set(k,{symbol,ts:new Date(k).toISOString(),bid_open:bid,bid_high:bid,bid_low:bid,bid_close:bid,ask_open:ask,ask_high:ask,ask_low:ask,ask_close:ask,spread_open_pips:sp,spread_high_pips:sp,spread_low_pips:sp,spread_close_pips:sp,spread_sum:sp,tick_count:1,ask_volume:Number.isFinite(av)?av:0,bid_volume:Number.isFinite(bv)?bv:0,source:SRC});else{b.bid_high=Math.max(b.bid_high,bid);b.bid_low=Math.min(b.bid_low,bid);b.bid_close=bid;b.ask_high=Math.max(b.ask_high,ask);b.ask_low=Math.min(b.ask_low,ask);b.ask_close=ask;b.spread_high_pips=Math.max(b.spread_high_pips,sp);b.spread_low_pips=Math.min(b.spread_low_pips,sp);b.spread_close_pips=sp;b.spread_sum+=sp;b.tick_count++;if(Number.isFinite(av))b.ask_volume+=av;if(Number.isFinite(bv))b.bid_volume+=bv}}return[...m.values()].map(b=>{const x={...b,spread_mean_pips:b.spread_sum/b.tick_count};delete x.spread_sum;return x as M})}
async function save(rows:M[]){for(let i=0;i<rows.length;i+=200){const q=await db.from("fx_microstructure_1m").upsert(rows.slice(i,i+200),{onConflict:"symbol,ts,source"});if(q.error)throw Error(q.error.message)}}
async function coverage(symbol:string,start:number){const out:any[]=[];for(let from=0;from<3000;from+=1000){const q=await db.from("fx_microstructure_1m").select("ts").eq("symbol",symbol).eq("source",SRC).gte("ts",new Date(start).toISOString()).order("ts",{ascending:false}).range(from,from+999);if(q.error)throw Error(q.error.message);const rows=q.data??[];out.push(...rows);if(rows.length<1000)break}const m=new Map<number,number>();for(const x of out){const h=floorHour(Date.parse(x.ts));m.set(h,(m.get(h)||0)+1)}return m}
async function runLimited<T,R>(items:T[],limit:number,fn:(x:T)=>Promise<R>){const out:R[]=[];for(let i=0;i<items.length;i+=limit){const batch=await Promise.all(items.slice(i,i+limit).map(fn));out.push(...batch)}return out}
Deno.serve(async()=>{try{const nowHour=floorHour(Date.now()),lookbackStart=nowHour-LOOKBACK_HOURS*hourMs,jobs:Job[]=[],before:any={};for(const symbol of SYMBOLS){const counts=await coverage(symbol,lookbackStart);const gaps:any[]=[];for(let i=2;i<=LOOKBACK_HOURS;i++){const h=nowHour-i*hourMs;if(!fxOpenHour(h))continue;const minutes=counts.get(h)||0;if(minutes<MIN_COMPLETE_MINUTES)gaps.push({hour:new Date(h).toISOString(),minutes})}before[symbol]={incompleteHours:gaps.length,repairQueue:gaps.slice(0,MAX_REPAIR_HOURS_PER_SYMBOL)};jobs.push({symbol,d:new Date(nowHour),reason:"live"},{symbol,d:new Date(nowHour-hourMs),reason:"live"},...gaps.slice(0,MAX_REPAIR_HOURS_PER_SYMBOL).map(g=>({symbol,d:new Date(g.hour),reason:"repair" as const}))}const seen=new Set<string>(),unique=jobs.filter(j=>{const k=`${j.symbol}:${j.d.toISOString()}`;if(seen.has(k))return false;seen.add(k);return true}),errors:string[]=[];const batches=await runLimited(unique,CONCURRENCY,async x=>{try{return{job:x,rows:await fetchHour(x.symbol,x.d)}}catch(e){errors.push(`${x.symbol} ${x.d.toISOString()} ${String(e)}`);return{job:x,rows:[] as M[]}}}),rows=batches.flatMap(x=>x.rows);await save(rows);const by:any={};for(const s of SYMBOLS){const z=rows.filter(x=>x.symbol===s).sort((a,b)=>Date.parse(a.ts)-Date.parse(b.ts)),q=await db.from("fx_microstructure_1m").select("ts,spread_mean_pips,tick_count").eq("symbol",s).order("ts",{ascending:false}).limit(1);if(q.error)throw Error(q.error.message);const afterCounts=await coverage(s,lookbackStart),remaining:any[]=[];for(let i=2;i<=LOOKBACK_HOURS;i++){const h=nowHour-i*hourMs;if(!fxOpenHour(h))continue;const minutes=afterCounts.get(h)||0;if(minutes<MIN_COMPLETE_MINUTES)remaining.push({hour:new Date(h).toISOString(),minutes})}const repairJobs=batches.filter(x=>x.job.symbol===s&&x.job.reason==="repair");by[s]={minutesWritten:z.length,newestWritten:z.at(-1)?.ts??null,newestStored:q.data?.[0]?.ts??null,spreadPips:q.data?.[0]?.spread_mean_pips??null,ticksPerMinute:q.data?.[0]?.tick_count??null,repairHoursAttempted:repairJobs.map(x=>x.job.d.toISOString()),repairMinutesRecovered:repairJobs.reduce((a,x)=>a+x.rows.length,0),incompleteHoursBefore:before[s].incompleteHours,incompleteHoursRemaining:remaining.length,nextRepairQueue:remaining.slice(0,MAX_REPAIR_HOURS_PER_SYMBOL)}}return J({ok:true,mode:"prospective_live_plus_self_healing_recent_gaps",lookbackHours:LOOKBACK_HOURS,minCompleteMinutes:MIN_COMPLETE_MINUTES,rows:rows.length,jobs:unique.length,by,errors})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});