import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,WH=(Deno.env.get("DISCORD_WEBHOOK_URL")??"").trim();
const db=createClient(SB,KEY,{auth:{persistSession:false}}),H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
async function cronOk(req:Request){const k=req.headers.get("x-v2-cron-key")??"";if(!k)return false;const q=await db.from("v2_runtime_secrets").select("secret").eq("name","cron").maybeSingle();if(q.error||!q.data?.secret)return false;const a=new TextEncoder().encode(k),b=new TextEncoder().encode(String(q.data.secret));if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]!^b[i]!;return d===0}
const f=(v:any,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):"—";
function webhookOk(){try{const u=new URL(WH);return u.protocol==="https:"&&u.hostname==="discord.com"&&u.pathname.startsWith("/api/webhooks/")}catch{return false}}
async function read(k:string){const q=await db.from("discord_alert_state").select("snapshot").eq("state_key",k).maybeSingle();if(q.error)throw Error(q.error.message);return q.data?.snapshot??null}
async function save(k:string,s:any,sent=false){const row:any={state_key:k,snapshot:s,updated_at:new Date().toISOString()};if(sent)row.last_sent_at=new Date().toISOString();const q=await db.from("discord_alert_state").upsert(row,{onConflict:"state_key"});if(q.error)throw Error(q.error.message)}
async function log(symbol:string,type:string,payload:any,id:any){const q=await db.from("discord_alert_log").insert({symbol,event_type:type,discord_message_id:id??null,payload,sent_at:new Date().toISOString()});if(q.error)console.error(q.error.message)}
async function post(title:string,description:string,fields:any[],color:number){const u=new URL(WH);u.searchParams.set("wait","true");const r=await fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:"V2 Market Brief",allowed_mentions:{parse:[]},embeds:[{title,description,fields,color,footer:{text:"V2 FX paper research · setup quality, not a win prediction"},timestamp:new Date().toISOString()}]})});const t=await r.text();if(!r.ok)throw Error(`Discord ${r.status}: ${t.slice(0,180)}`);try{return JSON.parse(t)}catch{return{id:null}}}
function colorFor(type:string){if(type==="quality_strong_interaction")return 0x3fb27f;if(type==="quality_broken")return 0xe06c5f;if(type.startsWith("quality_"))return 0xd9a44a;return 0x7fa8e0}
const meaningful=new Set(["STRONG_INTERACTION","WEAKENED","LATE_RETURN","BROKEN"]);
const label=(code:string)=>({STRONG_INTERACTION:"Strong interaction",WEAKENED:"Weakened setup",LATE_RETURN:"Late return",BROKEN:"Broken setup"}[code]||code);
Deno.serve(async req=>{if(req.method!=="GET")return J({error:"GET only"},405);try{if(!(await cronOk(req)))return J({error:"unauthorized"},401);if(!webhookOk())return J({configured:false},503);const r=await fetch(`${SB}/functions/v1/trade-quality?symbol=EURUSD,GBPUSD`,{headers:{"Cache-Control":"no-cache"}});if(!r.ok)throw Error(`trade-quality ${r.status}`);const d=await r.json(),sent:any[]=[];for(const symbol of ["EURUSD","GBPUSD"]){const c=d?.current?.[symbol],key=`quality:v31:${symbol}`,old=await read(key),tradeKey=c?.tradeKey??null,code=c?.quality?.code??"NO_SETUP",att=c?.fastAttention?.status??"UNKNOWN";let state:any=old&&old.tradeKey===tradeKey?{...old}:{tradeKey,qualityCode:null,nearNotified:false};const events:any[]=[];
if(tradeKey&&c?.status==="armed"&&!state.nearNotified&&["VERY_NEAR","IN_ZONE"].includes(att)){events.push({type:"entry_proximity",title:`${symbol} · Entry area is close`,desc:att==="IN_ZONE"?`The current reference price is inside the paper entry zone and about ${f(c.fastAttention?.distanceToEntryPips)} pips from the midpoint.`:`The current reference price is about ${f(c.fastAttention?.distanceToEntryPips)} pips from the paper midpoint.`,fields:[{name:"Setup quality",value:c.quality?.label??"Waiting",inline:false},{name:"What this means",value:"This is an early heads-up only. V2 still waits for the normal midpoint/path rule before counting a paper entry.",inline:false},{name:"Risk room",value:c.risk?.stopPolicyVersion==="v3.0_breathing_room"?`${f(c.risk?.pips)} pips · 1% dollar risk stays unchanged`:`${f(c.risk?.pips)} pips · older frozen plan`,inline:false}]});state.nearNotified=true}
if(tradeKey&&meaningful.has(code)&&state.qualityCode!==code){events.push({type:`quality_${code.toLowerCase()}`,title:`${symbol} · Setup quality: ${label(code)}`,desc:c.quality?.reason??"The setup quality changed.",fields:[{name:"What now",value:c.quality?.next??"Keep following the frozen paper rules.",inline:false},{name:"Important",value:"This grade describes the observed setup pattern. It is not a probability or guarantee that the trade will win.",inline:false}]})}
state.tradeKey=tradeKey;state.qualityCode=code;state.attention=att;state.updatedAt=new Date().toISOString();for(const e of events){const msg=await post(e.title,e.desc,e.fields,colorFor(e.type));await log(symbol,e.type,e,msg?.id);sent.push({symbol,type:e.type,messageId:msg?.id??null})}await save(key,state,events.length>0)}return J({ok:true,generatedAt:new Date().toISOString(),sent})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});
