import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SB,KEY,{auth:{persistSession:false}}),ROOT="https://jetta.dukascopy.com/v1",CODE="XAU-USD",SYMBOL="XAUUSD",SOURCE="Dukascopy Jetta XAU/USD";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
type Bar={ts:string;open:number;high:number;low:number;close:number;volume:number|null};
function scale(m:number){const[c,e="0"]=String(m).toLowerCase().split("e"),d=c.split(".")[1]?.length??0;return Math.max(0,d-Number(e))}
function decode(j:any):Bar[]{if(!j||!Array.isArray(j.times)||!Number.isFinite(j.timestamp)||!Number.isFinite(j.multiplier))return[];const n=j.times.length,cols=[j.opens,j.highs,j.lows,j.closes,j.volumes];if(cols.some((c:any)=>!Array.isArray(c)||c.length!==n))return[];const m=Number(j.multiplier),sc=scale(m),fmt=(u:number)=>Number((u*m).toFixed(sc));let ts=Number(j.timestamp),o=Math.round(Number(j.open)/m),h=Math.round(Number(j.high)/m),l=Math.round(Number(j.low)/m),c=Math.round(Number(j.close)/m);const out:Bar[]=[];for(let i=0;i<n;i++){ts+=Number(j.times[i])*Number(j.shift);o+=Number(j.opens[i]);h+=Number(j.highs[i]);l+=Number(j.lows[i]);c+=Number(j.closes[i]);const x={ts:new Date(ts).toISOString(),open:fmt(o),high:fmt(h),low:fmt(l),close:fmt(c),volume:Number.isFinite(Number(j.volumes[i]))?Number(j.volumes[i]):null};if(x.open>0&&x.high>=x.low&&x.low>0)out.push(x)}return out}
async function get(url:string){const r=await fetch(url,{headers:{"Accept":"application/json","User-Agent":"V2GoldResearch/1.0"},signal:AbortSignal.timeout(12000)});if(r.status===404)return[];if(!r.ok)throw Error(`${r.status} ${url}`);return decode(await r.json())}
const startDay=(d:Date)=>new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));
function aggregate(b:Bar[],mins:number){const ms=mins*60000,m=new Map<number,Bar[]>();for(const x of b){const k=Math.floor(+new Date(x.ts)/ms)*ms,g=m.get(k)??[];g.push(x);m.set(k,g)}return[...m.entries()].sort((a,b)=>a[0]-b[0]).map(([t,g])=>({ts:new Date(t).toISOString(),open:g[0].open,high:Math.max(...g.map(x=>x.high)),low:Math.min(...g.map(x=>x.low)),close:g.at(-1)!.close,volume:g.some(x=>x.volume!=null)?g.reduce((s,x)=>s+(x.volume??0),0):null}))}
async function persist(tf:string,b:Bar[]){const rows=b.map(x=>({symbol:SYMBOL,timeframe:tf,ts:x.ts,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume,source:SOURCE,is_proxy:false}));for(let i=0;i<rows.length;i+=200){const q=await db.from("market_bars").upsert(rows.slice(i,i+200),{onConflict:"symbol,timeframe,ts,source"});if(q.error)throw Error(`${tf}: ${q.error.message}`)}}
Deno.serve(async req=>{if(req.method!=="GET")return J({error:"GET only"},405);try{const now=new Date(),today=startDay(now),jobs:Promise<Bar[]>[]=[];for(let k=24;k>=1;k--){const d=new Date(today.getTime()-k*86400000);jobs.push(get(`${ROOT}/candles/minute/${CODE}/BID/${d.getUTCFullYear()}/${d.getUTCMonth()+1}/${d.getUTCDate()}`).catch(()=>[]))}jobs.push(get(`${ROOT}/candles/minute/${CODE}/BID?from=${today.getTime()}`));const minute=(await Promise.all(jobs)).flat(),dedupe=new Map<string,Bar>();for(const b of minute)dedupe.set(b.ts,b);const m1=[...dedupe.values()].sort((a,b)=>+new Date(a.ts)-+new Date(b.ts)),m15=aggregate(m1,15),h1=aggregate(m1,60),h4=aggregate(m1,240),year=Date.UTC(now.getUTCFullYear(),0,1),d1=await get(`${ROOT}/candles/day/${CODE}/BID?from=${year}`);await Promise.all([persist("15m",m15),persist("1h",h1),persist("4h",h4),persist("1d",d1)]);return J({ok:true,version:"xau-seed-v1",source:SOURCE,counts:{m1:m1.length,m15:m15.length,h1:h1.length,h4:h4.length,d1:d1.length},first:m1[0]?.ts,last:m1.at(-1)?.ts})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});