import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import LZMA from "npm:lzma@2.3.2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,db=createClient(U,K,{auth:{persistSession:false}}),SRC="Dukascopy BID ticks";
type B={ts:string;open:number;high:number;low:number;close:number;volume:number|null};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
function path(d:Date){return`${d.getUTCFullYear()}/${String(d.getUTCMonth()).padStart(2,"0")}/${String(d.getUTCDate()).padStart(2,"0")}/${String(d.getUTCHours()).padStart(2,"0")}h_ticks.bi5`}
function add(m:Map<number,B>,k:number,p:number,v:number|null){const b=m.get(k);if(!b){m.set(k,{ts:new Date(k).toISOString(),open:p,high:p,low:p,close:p,volume:v});return}b.high=Math.max(b.high,p);b.low=Math.min(b.low,p);b.close=p;if(v!=null)b.volume=(b.volume??0)+v}
async function hour(d:Date){const url=`https://datafeed.dukascopy.com/datafeed/EURUSD/${path(d)}`,r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 V2EURRaw/3.0"},signal:AbortSignal.timeout(7000)});if(r.status===404)return null;if(!r.ok)throw Error(`Dukascopy ${r.status}`);const enc=new Uint8Array(await r.arrayBuffer());if(!enc.length)return null;const raw:any=(LZMA as any).decompress(enc),bytes=raw instanceof Uint8Array?raw:new Uint8Array(raw),dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),m5=new Map<number,B>(),m15=new Map<number,B>();let ticks=0;for(let o=0;o+20<=bytes.length;o+=20){const ms=dv.getUint32(o,false),ask=dv.getUint32(o+4,false)/100000,bid=dv.getUint32(o+8,false)/100000,v=dv.getFloat32(o+16,false);if(!(ask>=bid&&bid>0&&ask-bid<.01))continue;const t=d.getTime()+ms;add(m5,Math.floor(t/300000)*300000,bid,Number.isFinite(v)?v:null);add(m15,Math.floor(t/900000)*900000,bid,Number.isFinite(v)?v:null);ticks++}return{m5:[...m5.values()],m15:[...m15.values()],ticks}}
async function save(tf:string,b:B[]){if(!b.length)return;const rows=b.map(x=>({symbol:"EURUSD",timeframe:tf,ts:x.ts,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume,source:SRC}));for(let i=0;i<rows.length;i+=150){const q=await db.from("market_raw_bars").upsert(rows.slice(i,i+150),{onConflict:"symbol,timeframe,ts,source"});if(q.error)throw Error(q.error.message)}}
async function pool<T,R>(xs:T[],n:number,f:(x:T)=>Promise<R>){const out:R[]=[];let i=0;async function w(){for(;;){const k=i++;if(k>=xs.length)return;out[k]=await f(xs[k])}}await Promise.all(Array.from({length:Math.min(n,xs.length)},()=>w()));return out}
Deno.serve(async()=>{try{const count=await db.from("market_raw_bars").select("*",{count:"exact",head:true}).eq("symbol","EURUSD").eq("timeframe","15m").eq("source",SRC);if(count.error)throw Error(count.error.message);const bootstrap=(count.count??0)<80,hours=bootstrap?30:2,n=new Date();n.setUTCMinutes(0,0,0);const hs:Date[]=[];for(let i=hours;i>=1;i--)hs.push(new Date(n.getTime()-i*3600000));let ok=0,ticks=0;const errors:string[]=[];const results=await pool(hs,bootstrap?4:2,async h=>{try{return await hour(h)}catch(e){errors.push(`${h.toISOString()}: ${String(e)}`);return null}});const all5:B[]=[],all15:B[]=[];for(const x of results){if(!x)continue;ok++;ticks+=x.ticks;all5.push(...x.m5);all15.push(...x.m15)}await Promise.all([save("5m",all5),save("15m",all15)]);return J({bootstrap,hoursAttempted:hours,hoursOk:ok,hoursFailed:hours-ok,ticks,m5Bars:all5.length,m15Bars:all15.length,errors:errors.slice(0,8)})}catch(e){return J({error:e instanceof Error?e.message:String(e)},500)}});