import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import LZMA from "npm:lzma@2.3.2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,db=createClient(U,K,{auth:{persistSession:false}}),SRC="Dukascopy BID ticks";
type B={ts:string;open:number;high:number;low:number;close:number;volume:number|null};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
function path(d:Date){return`${d.getUTCFullYear()}/${String(d.getUTCMonth()).padStart(2,"0")}/${String(d.getUTCDate()).padStart(2,"0")}/${String(d.getUTCHours()).padStart(2,"0")}h_ticks.bi5`}
function add(m:Map<number,B>,k:number,p:number,v:number|null){const b=m.get(k);if(!b){m.set(k,{ts:new Date(k).toISOString(),open:p,high:p,low:p,close:p,volume:v});return}b.high=Math.max(b.high,p);b.low=Math.min(b.low,p);b.close=p;if(v!=null)b.volume=(b.volume??0)+v}
async function hour(d:Date){const url=`https://datafeed.dukascopy.com/datafeed/EURUSD/${path(d)}`,r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 V2EURRaw/1.0"}});if(r.status===404)return null;if(!r.ok)throw Error(`Dukascopy ${r.status}`);const enc=new Uint8Array(await r.arrayBuffer());if(!enc.length)return null;const raw:any=(LZMA as any).decompress(enc),bytes=raw instanceof Uint8Array?raw:new Uint8Array(raw),dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),m5=new Map<number,B>(),m15=new Map<number,B>();let ticks=0;for(let o=0;o+20<=bytes.length;o+=20){const ms=dv.getUint32(o,false),ask=dv.getUint32(o+4,false)/100000,bid=dv.getUint32(o+8,false)/100000,v=dv.getFloat32(o+16,false);if(!(ask>=bid&&bid>0&&ask-bid<.01))continue;const t=d.getTime()+ms;add(m5,Math.floor(t/300000)*300000,bid,Number.isFinite(v)?v:null);add(m15,Math.floor(t/900000)*900000,bid,Number.isFinite(v)?v:null);ticks++}return{m5:[...m5.values()],m15:[...m15.values()],ticks}}
async function save(tf:string,b:B[]){if(!b.length)return;const rows=b.map(x=>({symbol:"EURUSD",timeframe:tf,ts:x.ts,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume,source:SRC}));const q=await db.from("market_raw_bars").upsert(rows,{onConflict:"symbol,timeframe,ts,source"});if(q.error)throw Error(q.error.message)}
Deno.serve(async()=>{try{const n=new Date();n.setUTCMinutes(0,0,0);const hs=[new Date(n.getTime()-2*3600000),new Date(n.getTime()-3600000)];let ok=0,ticks=0;const errors:string[]=[];for(const h of hs){try{const x=await hour(h);if(!x)continue;await Promise.all([save("5m",x.m5),save("15m",x.m15)]);ok++;ticks+=x.ticks}catch(e){errors.push(String(e))}}return J({attempted:2,ok,ticks,errors})}catch(e){return J({error:e instanceof Error?e.message:String(e)},500)}});