import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } });

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Cache-Control": "no-store",
};

const INSTRUMENTS: Record<string, any> = {
  EURUSD: { name: "Euro / U.S. Dollar", chart: "EURUSD=X", proxy: false },
  GBPUSD: { name: "British Pound / U.S. Dollar", chart: "GBPUSD=X", proxy: false },
  XAUUSD: { name: "Gold / U.S. Dollar", chart: "GC=F", proxy: true },
  US30: { name: "Dow / US30", chart: "YM=F", proxy: true },
};
const TF_SECONDS: Record<string, number> = { "15m": 900, "1h": 3600, "1d": 86400 };
type Bar = { ts:string; open:number; high:number; low:number; close:number; volume:number|null };

function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}})}
function finite(x:any):number|null{const n=Number(x);return Number.isFinite(n)?n:null}
function clamp(v:number,lo:number,hi:number){return Math.max(lo,Math.min(hi,v))}
function ema(values:number[],period:number){if(!values.length)return[];const k=2/(period+1),out=[values[0]];for(let i=1;i<values.length;i++)out.push(values[i]*k+out[i-1]*(1-k));return out}
function trueRanges(bars:Bar[]){return bars.map((b,i)=>i===0?b.high-b.low:Math.max(b.high-b.low,Math.abs(b.high-bars[i-1].close),Math.abs(b.low-bars[i-1].close)))}
function rollingMean(v:number[],n:number){const out:number[]=[];let sum=0;for(let i=0;i<v.length;i++){sum+=v[i];if(i>=n)sum-=v[i-n];out.push(sum/Math.min(i+1,n))}return out}
function median(v:number[]){if(!v.length)return NaN;const a=[...v].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}

function aggregate(bars:Bar[],hours:number){const ms=hours*3600_000,groups=new Map<number,Bar[]>();for(const b of bars){const key=Math.floor(new Date(b.ts).getTime()/ms)*ms,g=groups.get(key)??[];g.push(b);groups.set(key,g)}return [...groups.entries()].sort((a,b)=>a[0]-b[0]).map(([t,g])=>({ts:new Date(t).toISOString(),open:g[0].open,high:Math.max(...g.map(x=>x.high)),low:Math.min(...g.map(x=>x.low)),close:g[g.length-1].close,volume:g.some(x=>x.volume!=null)?g.reduce((s,x)=>s+(x.volume??0),0):null}))}
function stripIncomplete(bars:Bar[],sec:number){let out=bars.filter(b=>b.open>0&&b.high>0&&b.low>0&&b.close>0&&b.high>=b.low);while(out.length>1){const last=new Date(out[out.length-1].ts).getTime();if(Date.now()-last<sec*1000*.9)out=out.slice(0,-1);else break}return out}

async function yahoo(symbol:string,interval:string,range:string):Promise<{bars:Bar[],meta:any,source:string}>{const encoded=encodeURIComponent(symbol);let lastErr="";for(const host of ["query1.finance.yahoo.com","query2.finance.yahoo.com"]){try{const u=`https://${host}/v8/finance/chart/${encoded}?interval=${interval}&range=${range}&includePrePost=false&events=div%2Csplits`;const r=await fetch(u,{headers:{"User-Agent":"Mozilla/5.0 V2QuantResearch/2.0","Accept":"application/json"}});if(!r.ok){lastErr=`${host}:${r.status}`;continue}const j=await r.json(),root=j?.chart?.result?.[0];if(!root?.timestamp?.length){lastErr=`${host}:empty`;continue}const q=root.indicators?.quote?.[0]??{},bars:Bar[]=[];for(let i=0;i<root.timestamp.length;i++){const o=finite(q.open?.[i]),h=finite(q.high?.[i]),l=finite(q.low?.[i]),c=finite(q.close?.[i]);if(o==null||h==null||l==null||c==null||o<=0||h<=0||l<=0||c<=0||h<l)continue;bars.push({ts:new Date(root.timestamp[i]*1000).toISOString(),open:o,high:h,low:l,close:c,volume:finite(q.volume?.[i])})}return{bars,meta:root.meta??{},source:"Yahoo Finance public chart"}}catch(e){lastErr=String(e)}}throw new Error(`chart fetch failed ${lastErr}`)}

async function cachedProvider(key:string,ttlMs:number,loader:()=>Promise<any>){const read=await db.from("provider_cache").select("payload,fetched_at,expires_at,status").eq("cache_key",key).maybeSingle();const data=read.data;if(data&&new Date(data.expires_at).getTime()>Date.now())return{payload:data.payload,fetchedAt:data.fetched_at,status:data.status};try{const payload=await loader(),now=new Date(),exp=new Date(now.getTime()+ttlMs);const w=await db.from("provider_cache").upsert({cache_key:key,payload,fetched_at:now.toISOString(),expires_at:exp.toISOString(),status:"ok",error:null});if(w.error)throw new Error(`cache write: ${w.error.message}`);return{payload,fetchedAt:now.toISOString(),status:"ok"}}catch(e){if(data)return{payload:data.payload,fetchedAt:data.fetched_at,status:"stale",error:String(e)};return{payload:null,fetchedAt:new Date(0).toISOString(),status:"error",error:String(e)}}}

async function fxReference(){return cachedProvider("exchangerate-dev-usd",90_000,async()=>{const r=await fetch("https://api.exchangerate.dev/v1/latest/USD?symbols=EUR,GBP",{headers:{"Accept":"application/json","User-Agent":"V2QuantResearchLab/2.0"}});if(!r.ok)throw new Error(`exchangerate.dev ${r.status}`);const j=await r.json();if(j?.result!=="success"||!j?.rates?.EUR||!j?.rates?.GBP)throw new Error(`exchangerate.dev invalid ${JSON.stringify(j).slice(0,180)}`);return j})}
async function goldSpot(){return cachedProvider("goldprice-xau",90_000,async()=>{const r=await fetch("https://api.goldprice.dev/v1/prices?symbol=XAU-USD-SPOT",{headers:{"Accept":"application/json","User-Agent":"V2QuantResearchLab/2.0"}});if(!r.ok)throw new Error(`goldprice ${r.status}`);const j=await r.json();if(j?.error)throw new Error(`goldprice ${j.error}`);return j})}

function trend(bars:Bar[]){if(bars.length<55)return{label:"insufficient",strength:0,score:0,ema20:null,ema50:null};const closes=bars.map(x=>x.close),e20=ema(closes,20),e50=ema(closes,50),atr=rollingMean(trueRanges(bars),14),i=bars.length-1,a=Math.max(atr[i],Math.abs(closes[i])*1e-5);const p1=clamp((closes[i]-e20[i])/a,-3,3),p2=clamp((e20[i]-e50[i])/a,-3,3),p3=clamp((e20[i]-e20[Math.max(0,i-5)])/a,-3,3),score=p1*.55+p2*.75+p3*.45,label=score>.35?"bullish":score<-.35?"bearish":"mixed";return{label,strength:Math.round(clamp(Math.abs(score)*38,0,100)),score,ema20:e20[i],ema50:e50[i]}}
function swings(bars:Bar[]){const highs:any[]=[],lows:any[]=[];for(let i=2;i<bars.length-2;i++){if(bars[i].high>bars[i-1].high&&bars[i].high>=bars[i-2].high&&bars[i].high>bars[i+1].high&&bars[i].high>=bars[i+2].high)highs.push({i,price:bars[i].high,ts:bars[i].ts});if(bars[i].low<bars[i-1].low&&bars[i].low<=bars[i-2].low&&bars[i].low<bars[i+1].low&&bars[i].low<=bars[i+2].low)lows.push({i,price:bars[i].low,ts:bars[i].ts})}return{highs,lows,lastHigh:highs.at(-1)??null,lastLow:lows.at(-1)??null}}
function marketSession(){const h=new Date().getUTCHours(),london=h>=7&&h<16,ny=h>=13&&h<22,asia=h>=0&&h<9;if(london&&ny)return"London / New York overlap";if(london)return"London";if(ny)return"New York";if(asia)return"Asia";return"Transition / off-hours"}

function formation(bars:Bar[],reference:number){if(bars.length<45)return{stage:0,code:"NO_SETUP",label:"Not enough M15 history",direction:null,confidence:0,poiHigh:null,poiLow:null,distancePoiAtr:null,details:{}};const atr=rollingMean(trueRanges(bars),14),n=bars.length,last=bars[n-1],a=Math.max(atr[n-1],Math.abs(last.close)*1e-5);let sweep:any=null;for(let i=Math.max(22,n-12);i<n;i++){const prior=bars.slice(i-20,i),ph=Math.max(...prior.map(x=>x.high)),pl=Math.min(...prior.map(x=>x.low)),ai=Math.max(atr[i],a),bear=bars[i].high>ph+.03*ai&&bars[i].close<ph,bull=bars[i].low<pl-.03*ai&&bars[i].close>pl;if(bear||bull)sweep={i,direction:bear?"short":"long",priorHigh:ph,priorLow:pl,ts:bars[i].ts,extreme:bear?bars[i].high:bars[i].low}}
  const sw=swings(bars.slice(-60));if(!sweep){const hi=sw.lastHigh?.price??Math.max(...bars.slice(-20).map(x=>x.high)),lo=sw.lastLow?.price??Math.min(...bars.slice(-20).map(x=>x.low)),dh=Math.abs(reference-hi)/a,dl=Math.abs(reference-lo)/a;if(Math.min(dh,dl)<=.35){const dir=dl<dh?"long":"short";return{stage:1,code:"LIQUIDITY_NEARBY",label:`Price is near ${dl<dh?"sell-side":"buy-side"} liquidity`,direction:dir,confidence:42,poiHigh:null,poiLow:null,distancePoiAtr:null,details:{distanceHighAtr:dh,distanceLowAtr:dl}}}return{stage:0,code:"NO_SETUP",label:"No active V2 formation",direction:null,confidence:15,poiHigh:null,poiLow:null,distancePoiAtr:null,details:{distanceHighAtr:dh,distanceLowAtr:dl}}}
  const pre=bars.slice(Math.max(0,sweep.i-8),sweep.i),bosHigh=Math.max(...pre.map(x=>x.high)),bosLow=Math.min(...pre.map(x=>x.low));let bos=-1;for(let i=sweep.i+1;i<n;i++)if((sweep.direction==="long"&&bars[i].close>bosHigh)||(sweep.direction==="short"&&bars[i].close<bosLow)){bos=i;break}if(bos<0){const age=n-1-sweep.i;return{stage:age>=1?4:3,code:age>=1?"WAITING_FOR_BOS":"SWEEP_CONFIRMED",label:age>=1?"Liquidity sweep confirmed; waiting for BOS":"Liquidity sweep confirmed",direction:sweep.direction,confidence:55,poiHigh:null,poiLow:null,distancePoiAtr:null,details:{sweepTime:sweep.ts,bosReference:sweep.direction==="long"?bosHigh:bosLow}}}
  let poi=-1;for(let i=bos;i>=sweep.i;i--){const opp=sweep.direction==="long"?bars[i].close<bars[i].open:bars[i].close>bars[i].open;if(opp){poi=i;break}}if(poi<0)return{stage:5,code:"BOS_CONFIRMED",label:"BOS confirmed; no clean POI identified",direction:sweep.direction,confidence:62,poiHigh:null,poiLow:null,distancePoiAtr:null,details:{sweepTime:sweep.ts,bosTime:bars[bos].ts}};
  const pHigh=bars[poi].high,pLow=bars[poi].low,mid=(pHigh+pLow)/2,dist=Math.abs(reference-mid)/a,inside=reference>=pLow&&reference<=pHigh;let touched=false;for(let i=bos+1;i<n-1;i++)if(bars[i].low<=pHigh&&bars[i].high>=pLow){touched=true;break}if(touched&&!inside)return{stage:2,code:"POI_USED",label:"Recent V2 sequence found, but the POI has already been revisited",direction:sweep.direction,confidence:30,poiHigh:pHigh,poiLow:pLow,distancePoiAtr:dist,details:{sweepTime:sweep.ts,bosTime:bars[bos].ts,poiTime:bars[poi].ts,fresh:false}};if(inside)return{stage:8,code:"ENTRY_ZONE_REACHED",label:"Research entry zone reached — not a trade signal",direction:sweep.direction,confidence:78,poiHigh:pHigh,poiLow:pLow,distancePoiAtr:dist,details:{sweepTime:sweep.ts,bosTime:bars[bos].ts,poiTime:bars[poi].ts,fresh:!touched}};if(dist<=.5)return{stage:7,code:"APPROACHING_POI",label:"Fresh POI identified; price is approaching the zone",direction:sweep.direction,confidence:72,poiHigh:pHigh,poiLow:pLow,distancePoiAtr:dist,details:{sweepTime:sweep.ts,bosTime:bars[bos].ts,poiTime:bars[poi].ts,fresh:!touched}};return{stage:6,code:"FRESH_POI_IDENTIFIED",label:"BOS confirmed and a fresh POI is identified",direction:sweep.direction,confidence:68,poiHigh:pHigh,poiLow:pLow,distancePoiAtr:dist,details:{sweepTime:sweep.ts,bosTime:bars[bos].ts,poiTime:bars[poi].ts,fresh:!touched}}}

function regime(h4:Bar[],m15:Bar[],h4t:any){if(h4.length<55||m15.length<55)return"insufficient";const h4atr=rollingMean(trueRanges(h4),14).at(-1)??0,sep=Math.abs((h4t.ema20??0)-(h4t.ema50??0))/Math.max(h4atr,1e-9),mAtr=rollingMean(trueRanges(m15),14),current=mAtr.at(-1)??0,base=median(mAtr.slice(-50));if(current>base*1.45)return"volatility expansion";if(current<base*.68)return"volatility compression";if(sep>.7&&h4t.label!=="mixed")return"trending";if(sep<.22)return"ranging";return"transition"}
function summaryText(symbol:string,trends:any,reg:string,form:any,session:string,proxy:boolean){const align=trends.d1.label===trends.h4.label&&trends.d1.label!=="mixed"?`${trends.d1.label} D1/H4 alignment`:`D1 ${trends.d1.label}, H4 ${trends.h4.label}`,pull=trends.m15.label!==trends.h4.label&&trends.m15.label!=="mixed"?`; M15 is moving against the H4 bias`:`; M15 is ${trends.m15.label}`,proxyText=proxy?" The chart feed is a context proxy, so this is research context rather than execution truth.":"";return`${symbol}: ${align}${pull}. Regime: ${reg}. ${form.label}. Active session: ${session}.${proxyText}`}

async function persistBars(symbol:string,tf:string,bars:Bar[],source:string,isProxy:boolean){const q=await db.from("market_bars").select("*",{count:"exact",head:true}).eq("symbol",symbol).eq("timeframe",tf),initial=(q.count??0)===0,keep=initial?(tf==="15m"?250:tf==="1d"?180:120):5,rows=bars.slice(-keep).map(b=>({symbol,timeframe:tf,ts:b.ts,open:b.open,high:b.high,low:b.low,close:b.close,volume:b.volume,source,is_proxy:isProxy}));if(rows.length){const w=await db.from("market_bars").upsert(rows,{onConflict:"symbol,timeframe,ts,source"});if(w.error)throw new Error(`bars ${symbol}/${tf}: ${w.error.message}`)}}

async function refresh(symbol:string){const cfg=INSTRUMENTS[symbol];if(!cfg)throw new Error("unknown symbol");const [m15raw,h1raw,d1raw,fx,gold]=await Promise.all([yahoo(cfg.chart,"15m","1mo"),yahoo(cfg.chart,"1h","3mo"),yahoo(cfg.chart,"1d","1y"),symbol==="EURUSD"||symbol==="GBPUSD"?fxReference():Promise.resolve(null),symbol==="XAUUSD"?goldSpot():Promise.resolve(null)]);const m15=stripIncomplete(m15raw.bars,TF_SECONDS["15m"]),h1=stripIncomplete(h1raw.bars,TF_SECONDS["1h"]),d1=stripIncomplete(d1raw.bars,TF_SECONDS["1d"]),h4=stripIncomplete(aggregate(h1,4),4*3600);if(m15.length<60||h1.length<60||d1.length<60)throw new Error("insufficient chart bars");let bid:number|null=null,ask:number|null=null,quoteSource="Yahoo delayed/reference price",reference=finite(m15raw.meta?.regularMarketPrice)??m15.at(-1)!.close;
  if(symbol==="EURUSD"&&fx?.payload?.rates?.EUR){reference=1/Number(fx.payload.rates.EUR);quoteSource="exchangerate.dev live reference"}if(symbol==="GBPUSD"&&fx?.payload?.rates?.GBP){reference=1/Number(fx.payload.rates.GBP);quoteSource="exchangerate.dev live reference"}
  if(symbol==="XAUUSD"&&gold?.payload){const gp=gold.payload,gprice=finite(gp.price??gp?.symbols?.[0]?.price),gbid=finite(gp.bid??gp?.symbols?.[0]?.bid),gask=finite(gp.ask??gp?.symbols?.[0]?.ask);if(gprice!=null){reference=gprice;quoteSource="goldprice.dev spot reference"}if(gbid!=null)bid=gbid;if(gask!=null)ask=gask}
  const trends={d1:trend(d1),h4:trend(h4),h1:trend(h1),m15:trend(m15)},reg=regime(h4,m15,trends.h4),form=formation(m15,reference),session=marketSession(),atr15=rollingMean(trueRanges(m15),14).at(-1)??null,recent=m15.slice(-20),hi=Math.max(...recent.map(x=>x.high)),lo=Math.min(...recent.map(x=>x.low)),pos=(reference-lo)/Math.max(hi-lo,1e-9),d1last=d1.at(-1)!,sw=swings(m15.slice(-80));const warning=cfg.proxy?(symbol==="US30"?"Chart uses E-mini Dow futures as a free extended-hours proxy; not broker US30 CFD execution":"Chart uses COMEX gold futures as a free structure proxy; spot reference used when anonymous spot API is available"):"Public reference feed; not broker execution truth";
  const dataHealth:any={chart_status:"ok",chart_symbol:cfg.chart,chart_proxy:cfg.proxy,last_m15_bar:m15.at(-1)?.ts,reference_source:quoteSource,fx_reference_status:fx?.status??null,fx_reference_fetched_at:fx?.fetchedAt??null,gold_spot_status:gold?.status??null,gold_spot_fetched_at:gold?.fetchedAt??null,generated_at:new Date().toISOString(),warning};
  const state:any={symbol,as_of:new Date().toISOString(),reference_price:reference,bid,ask,spread:bid!=null&&ask!=null?ask-bid:null,quote_source:quoteSource,chart_source:m15raw.source,market_session:session,d1_trend:trends.d1.label,h4_trend:trends.h4.label,h1_trend:trends.h1.label,m15_trend:trends.m15.label,d1_strength:trends.d1.strength,h4_strength:trends.h4.strength,h1_strength:trends.h1.strength,m15_strength:trends.m15.strength,regime:reg,formation_stage:form.stage,formation_code:form.code,formation_label:form.label,formation_direction:form.direction,formation_confidence:form.confidence,atr15,range_position:clamp(pos,0,1),prev_day_high:d1last.high,prev_day_low:d1last.low,swing_high:sw.lastHigh?.price??null,swing_low:sw.lastLow?.price??null,poi_high:form.poiHigh,poi_low:form.poiLow,distance_to_poi_atr:form.distancePoiAtr,research_summary:summaryText(symbol,trends,reg,form,session,cfg.proxy),data_health:dataHealth,details:{trends,formation:form.details,chart_name:cfg.name,proxy:cfg.proxy},updated_at:new Date().toISOString()};
  const s=await db.from("market_states").upsert(state,{onConflict:"symbol"});if(s.error)throw new Error(`state write: ${s.error.message}`);await Promise.all([persistBars(symbol,"15m",m15,m15raw.source,cfg.proxy),persistBars(symbol,"1h",h1,h1raw.source,cfg.proxy),persistBars(symbol,"4h",h4,h1raw.source,cfg.proxy),persistBars(symbol,"1d",d1,d1raw.source,cfg.proxy)]);const lh=await db.from("market_state_history").select("as_of").eq("symbol",symbol).order("as_of",{ascending:false}).limit(1).maybeSingle();if(!lh.data||Date.now()-new Date(lh.data.as_of).getTime()>=14*60_000){const w=await db.from("market_state_history").insert({symbol,as_of:state.as_of,reference_price:reference,formation_stage:form.stage,formation_code:form.code,formation_direction:form.direction,regime:reg,state:{trends,formation:form,session,quoteSource,spread:state.spread,rangePosition:state.range_position,dataHealth}});if(w.error)throw new Error(`history write: ${w.error.message}`)}return state}
async function getState(symbol:string,force=false){const q=await db.from("market_states").select("*").eq("symbol",symbol).maybeSingle();if(!force&&q.data&&Date.now()-new Date(q.data.updated_at).getTime()<90_000)return{...q.data,cached:true};try{return{...await refresh(symbol),cached:false}}catch(e){if(q.data)return{...q.data,cached:true,refresh_error:String(e)};throw e}}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});try{const u=new URL(req.url);let symbols:string[]=[],force=false;if(req.method==="POST"){const b=await req.json().catch(()=>({})),raw=b.symbols??b.symbol??"all";symbols=raw==="all"?Object.keys(INSTRUMENTS):(Array.isArray(raw)?raw:[raw]);force=Boolean(b.force)}else{const raw=u.searchParams.get("symbol")??"all";symbols=raw==="all"?Object.keys(INSTRUMENTS):raw.split(",");force=u.searchParams.get("force")==="1"}symbols=symbols.map(x=>String(x).toUpperCase()).filter(x=>INSTRUMENTS[x]);if(!symbols.length)return json({error:"No valid instruments"},400);const settled=await Promise.allSettled(symbols.map(s=>getState(s,force))),states:any[]=[],errors:any[]=[];settled.forEach((r,i)=>r.status==="fulfilled"?states.push(r.value):errors.push({symbol:symbols[i],error:String(r.reason)}));return json({version:"V2 Research Lab v1.1",research_only:true,live_signals:false,generated_at:new Date().toISOString(),states,errors,methodology:{purpose:"Market-state and V2 formation research; not trade execution",formation_scale:"0-8 deterministic state machine",execution_truth:"Unavailable without broker feed",free_data_policy:"No paid API keys; public/no-key reference sources only",visual_chart:"TradingView free widget is separate from research calculations"}})}catch(e){return json({error:String(e)},500)}});
