import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,db=createClient(U,K,{auth:{persistSession:false}});
const H={"content-type":"application/json","cache-control":"no-store"},CAN="EURUSD canonical structure v1",CUT="2026-08-11T18:30:00Z",R=2.5,MAX_HOLD=48,ENTRY_HORIZON=192,EPS=1e-9;
type B={ts:string;open:number;high:number;low:number;close:number};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),ms=(x:any)=>new Date(x).getTime(),clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
async function cronOk(req:Request){const k=req.headers.get("x-v2-cron-key")??"";if(!k)return false;const q=await db.from("v2_runtime_secrets").select("secret").eq("name","cron").maybeSingle();if(q.error||!q.data?.secret)return false;const a=new TextEncoder().encode(k),b=new TextEncoder().encode(String(q.data.secret));if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]!^b[i]!;return d===0}
const touch=(b:B,p:number)=>b.low<=p+EPS&&p<=b.high+EPS;
const levels=(dir:string,b:B,stop:number,target:number)=>dir==="long"?{stop:b.low<=stop+EPS,target:b.high>=target-EPS}:{stop:b.high>=stop-EPS,target:b.low<=target+EPS};
async function bars(tf:string,n:number){const q=await db.from("market_bars").select("ts,open,high,low,close").eq("symbol","EURUSD").eq("timeframe",tf).eq("source",CAN).order("ts",{ascending:false}).limit(n);if(q.error)throw Error(q.error.message);return[...(q.data??[])].reverse().map((x:any)=>({ts:new Date(x.ts).toISOString(),open:+x.open,high:+x.high,low:+x.low,close:+x.close})) as B[]}
function resolve(m15:B[],m5:B[],dir:string,bosAt:string,entry:number,stop:number,target:number,risk:number,entryHorizon:number|null){
  const bos=m15.findIndex(b=>b.ts===new Date(bosAt).toISOString());if(bos<0)return{kind:"defer",reason:"BOS not present in canonical M15"};
  const seq=m15.slice(bos+1),fillRel=seq.findIndex(b=>touch(b,entry));
  if(fillRel<0){if(entryHorizon!=null&&seq.length>=entryHorizon)return{kind:"not_filled",at:seq[entryHorizon-1].ts,gross:0};return{kind:"waiting"};}
  const entryIdx=bos+1+fillRel,eb=m15[entryIdx],subs=m5.filter(b=>ms(b.ts)>=ms(eb.ts)&&ms(b.ts)<ms(eb.ts)+900000),k=subs.findIndex(b=>touch(b,entry));
  if(k<0)return{kind:"ambiguous",reason:"Canonical M15 entry touch not reproduced by canonical 5m",entryIdx,barsToEntry:entryIdx-bos};
  const first=subs[k],h0=levels(dir,first,stop,target);
  if(h0.stop||h0.target)return{kind:"ambiguous",reason:"Entry and exit level touched in same canonical 5m bar",entryAt:first.ts,exitAt:first.ts,entryIdx,barsToEntry:entryIdx-bos};
  const timeoutIdx=entryIdx+MAX_HOLD,timeoutBar=timeoutIdx<m15.length?m15[timeoutIdx]:null,end=timeoutBar?ms(timeoutBar.ts)+900000:Infinity;
  const path=m5.filter(b=>ms(b.ts)>ms(first.ts)&&ms(b.ts)<end);let hi=first.high,lo=first.low;
  for(const b of path){hi=Math.max(hi,b.high);lo=Math.min(lo,b.low);const h=levels(dir,b,stop,target);if(h.stop&&h.target)return{kind:"ambiguous",reason:"SL and TP touched in same canonical 5m bar",entryAt:first.ts,exitAt:b.ts,entryIdx,barsToEntry:entryIdx-bos};if(h.stop)return{kind:"loss",entryAt:first.ts,exitAt:b.ts,exitPrice:stop,gross:-1,entryIdx,barsToEntry:entryIdx-bos,mfe:risk>0?(dir==="long"?(hi-entry)/risk:(entry-lo)/risk):null,mae:risk>0?(dir==="long"?(entry-lo)/risk:(hi-entry)/risk):null};if(h.target)return{kind:"win",entryAt:first.ts,exitAt:b.ts,exitPrice:target,gross:R,entryIdx,barsToEntry:entryIdx-bos,mfe:risk>0?(dir==="long"?(hi-entry)/risk:(entry-lo)/risk):null,mae:risk>0?(dir==="long"?(entry-lo)/risk:(hi-entry)/risk):null};}
  if(timeoutBar){const raw=risk>0?(dir==="long"?(timeoutBar.close-entry)/risk:(entry-timeoutBar.close)/risk):0;return{kind:"timeout",entryAt:first.ts,exitAt:timeoutBar.ts,exitPrice:timeoutBar.close,gross:clamp(raw,-1,R),entryIdx,barsToEntry:entryIdx-bos,mfe:risk>0?(dir==="long"?(hi-entry)/risk:(entry-lo)/risk):null,mae:risk>0?(dir==="long"?(entry-lo)/risk:(hi-entry)/risk):null};}
  return{kind:"open",entryAt:first.ts,entryIdx,barsToEntry:entryIdx-bos,mfe:risk>0?(dir==="long"?(hi-entry)/risk:(entry-lo)/risk):null,mae:risk>0?(dir==="long"?(entry-lo)/risk:(hi-entry)/risk):null};
}
async function verifyTrades(m15:B[],m5:B[]){const q=await db.from("paper_trades").select("*").eq("symbol","EURUSD").gte("armed_at",CUT).eq("status","ambiguous").like("ambiguous_reason","Legacy Yahoo EURUSD 5m resolution censored%").order("armed_at",{ascending:true}).limit(50);if(q.error)throw Error(q.error.message);let fixed=0,still=0;for(const t of q.data??[]){const z:any=resolve(m15,m5,t.direction,t.bos_time,+t.entry_price,+t.stop_price,+t.target_price,+t.risk_distance,null);if(z.kind==="defer"||z.kind==="waiting"){still++;continue}const ctx={...(t.context??{}),legacy_eurusd_5m_censored:false,canonical_5m_verified:true,canonical_5m_verified_at:new Date().toISOString(),canonical_5m_resolution:z.kind};const patch:any={context:ctx,resolution_timeframe:"canonical5m",updated_at:new Date().toISOString(),ambiguous_reason:null};if(z.kind==="ambiguous"){patch.status="ambiguous";patch.lifecycle_phase="closed";patch.focus_active=false;patch.entry_at=z.entryAt??null;patch.exit_at=z.exitAt??z.entryAt??new Date().toISOString();patch.exit_price=null;patch.gross_r=null;patch.ambiguous_reason=z.reason;still++;}else if(z.kind==="open"){patch.status="open";patch.lifecycle_phase="filled";patch.focus_active=true;patch.entry_at=z.entryAt;patch.exit_at=null;patch.exit_price=null;patch.gross_r=null;patch.bars_to_entry=z.barsToEntry;patch.mfe_r=z.mfe;patch.mae_r=z.mae;ctx.entry_bar_resolved_5m=true;fixed++;}else{patch.status=z.kind;patch.lifecycle_phase="closed";patch.focus_active=false;patch.entry_at=z.entryAt;patch.exit_at=z.exitAt;patch.exit_price=z.exitPrice;patch.gross_r=z.gross;patch.bars_to_entry=z.barsToEntry;patch.mfe_r=z.mfe;patch.mae_r=z.mae;ctx.entry_bar_resolved_5m=true;fixed++;}const w=await db.from("paper_trades").update(patch).eq("trade_key",t.trade_key);if(w.error)throw Error(w.error.message);await db.from("paper_trade_events").insert({trade_key:t.trade_key,event_at:new Date().toISOString(),event_type:"update",price:z.exitPrice??z.entryAt?+t.entry_price:null,payload:{canonical5m:true,verifiedResult:z.kind,reason:z.reason??null}});}return{found:(q.data??[]).length,fixed,stillAmbiguous:still}}
async function verifyShadows(m15:B[],m5:B[]){const q=await db.from("poi_depth_shadow").select("*").eq("symbol","EURUSD").gte("frozen_at",CUT).eq("status","ambiguous").like("ambiguous_reason","Legacy Yahoo EURUSD 5m resolution censored%").order("frozen_at",{ascending:true}).limit(500);if(q.error)throw Error(q.error.message);if(!(q.data??[]).length)return{found:0,fixed:0,stillAmbiguous:0};const keys=[...new Set((q.data??[]).map((x:any)=>x.trade_key))],p=await db.from("paper_trades").select("trade_key,bos_time").in("trade_key",keys);if(p.error)throw Error(p.error.message);const pm=new Map((p.data??[]).map((x:any)=>[x.trade_key,x]));let fixed=0,still=0;for(const s of q.data??[]){const parent:any=pm.get(s.trade_key);if(!parent){still++;continue}const z:any=resolve(m15,m5,s.direction,parent.bos_time,+s.entry_price,+s.stop_price,+s.target_price,+s.risk_distance,ENTRY_HORIZON);if(z.kind==="defer"){still++;continue}const patch:any={resolution_timeframe:"canonical5m",updated_at:new Date().toISOString(),ambiguous_reason:null};if(z.kind==="waiting"){patch.status="waiting";patch.filled_at=null;patch.exit_at=null;patch.exit_price=null;patch.gross_r=null;fixed++;}else if(z.kind==="not_filled"){patch.status="not_filled";patch.filled_at=null;patch.exit_at=z.at;patch.exit_price=null;patch.gross_r=0;fixed++;}else if(z.kind==="ambiguous"){patch.status="ambiguous";patch.filled_at=z.entryAt??null;patch.exit_at=z.exitAt??z.entryAt??null;patch.exit_price=null;patch.gross_r=null;patch.ambiguous_reason=z.reason;still++;}else if(z.kind==="open"){patch.status="open";patch.filled_at=z.entryAt;patch.exit_at=null;patch.exit_price=null;patch.gross_r=null;patch.bars_to_entry=z.barsToEntry;fixed++;}else{patch.status=z.kind;patch.filled_at=z.entryAt;patch.exit_at=z.exitAt;patch.exit_price=z.exitPrice;patch.gross_r=z.gross;patch.bars_to_entry=z.barsToEntry;fixed++;}const w=await db.from("poi_depth_shadow").update(patch).eq("shadow_key",s.shadow_key);if(w.error)throw Error(w.error.message)}return{found:(q.data??[]).length,fixed,stillAmbiguous:still}}
Deno.serve(async req=>{try{if(!(await cronOk(req)))return J({error:"unauthorized"},401);const[m15,m5]=await Promise.all([bars("15m",600),bars("5m",1000)]);const[t,s]=await Promise.all([verifyTrades(m15,m5),verifyShadows(m15,m5)]);return J({version:"EURUSD canonical 5m verifier v1",m15Bars:m15.length,m5Bars:m5.length,trades:t,shadows:s,generatedAt:new Date().toISOString()})}catch(e){return J({error:e instanceof Error?e.message:String(e)},500)}});