import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,WH=(Deno.env.get("DISCORD_WEBHOOK_URL")??"").trim();
const db=createClient(SB,KEY,{auth:{persistSession:false}}),PAIRS=["EURUSD","GBPUSD"];
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const f=(x:any,d=2)=>Number.isFinite(Number(x))?Number(x).toFixed(d):"—",p5=(x:any)=>Number.isFinite(Number(x))?Number(x).toFixed(5):"—",up=(x:any)=>String(x??"—").toUpperCase();
function webhookOk(){try{const u=new URL(WH);return u.protocol==="https:"&&u.hostname==="discord.com"&&u.pathname.startsWith("/api/webhooks/")}catch{return false}}
async function post(title:string,description:string,fields:any[]=[]){const u=new URL(WH);u.searchParams.set("wait","true");const r=await fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:"V2 Market Brief",allowed_mentions:{parse:[]},embeds:[{title,description,fields,footer:{text:"V2 research-only market support · paper states are not broker execution"},timestamp:new Date().toISOString()}]})});const t=await r.text();if(!r.ok)throw Error(`Discord ${r.status}: ${t.slice(0,220)}`);try{return JSON.parse(t)}catch{return{id:null}}}
async function read(k:string){const q=await db.from("discord_alert_state").select("snapshot").eq("state_key",k).maybeSingle();if(q.error)throw Error(q.error.message);return q.data?.snapshot??null}
async function save(k:string,s:any,sent=false){const row:any={state_key:k,snapshot:s,updated_at:new Date().toISOString()};if(sent)row.last_sent_at=new Date().toISOString();const q=await db.from("discord_alert_state").upsert(row,{onConflict:"state_key"});if(q.error)throw Error(q.error.message)}
async function log(symbol:string|null,type:string,payload:any,id:any){const q=await db.from("discord_alert_log").insert({symbol,event_type:type,discord_message_id:id??null,payload,sent_at:new Date().toISOString()});if(q.error)console.error("log",q.error.message)}
const stageAlert=new Set([3,5,6,7,8]),fav=[.5,1,1.5,2],adv=[-.5,-.75];
function maxCross(x:number|null){if(x==null)return null;const z=fav.filter(v=>x>=v);return z.length?Math.max(...z):null}function minCross(x:number|null){if(x==null)return null;const z=adv.filter(v=>x<=v);return z.length?Math.min(...z):null}
function tradeFields(t:any){return[{name:"Now",value:`${t.currentR==null?"—":`${t.currentR>=0?"+":""}${f(t.currentR)}R`} · ${t.label}`,inline:true},{name:"Best / worst seen",value:`${t.bestSeenR==null?"—":`+${f(t.bestSeenR)}R`} / ${t.worstSeenR==null?"—":`${f(t.worstSeenR)}R`}`,inline:true},{name:"Frozen levels",value:`Entry ${p5(t.entryPrice)} · Stop ${p5(t.stopPrice)} · Target ${p5(t.targetPrice)}`,inline:false}]}
function macroFields(m:any){const x=m?.nextRelease;if(!x)return[];const e=x.primaryEvent??x.events?.[0]??{};return[{name:"Release",value:`${x.title} · ${new Date(x.timeUtc).toISOString().slice(0,16).replace("T"," ")} UTC`,inline:false},{name:"Consensus / previous",value:`${e.consensus||e.forecast||"—"} / ${e.previous||"—"}`,inline:true}]}
Deno.serve(async req=>{if(req.method!=="GET")return J({error:"GET only"},405);try{if(!webhookOk())return J({configured:false},503);const r=await fetch(`${SB}/functions/v1/trader-brief`,{headers:{"Cache-Control":"no-cache"}});if(!r.ok)throw Error(`trader-brief ${r.status}`);const brief=await r.json(),pairs=Array.isArray(brief?.pairs)?brief.pairs:[],sent:any[]=[];
for(const b of pairs){const key=`pulse:v22:${b.symbol}`,old=await read(key),t=b.trade??null,m=b.macro??{},formation=b.formation??{},now:any={stage:Number(formation.stage??0),direction:formation.direction??null,mode:b.status?.decisionMode??null,trust:b.status?.dataTrust?.level??null,tradeKey:t?.tradeKey??null,tradeStatus:t?.status??null,favMax:old?.tradeKey===t?.tradeKey?(old?.favMax??null):null,advMin:old?.tradeKey===t?.tradeKey?(old?.advMin??null):null,macroNotified:old?.macroNotified??{},newsSeen:Array.isArray(old?.newsSeen)?old.newsSeen:[]};const events:any[]=[];
if(old){if((old.stage!==now.stage||old.direction!==now.direction)&&stageAlert.has(now.stage))events.push({type:`stage_${now.stage}`,title:`${b.symbol} · ${formation.plain?.title??"Setup update"}`,desc:`${formation.plain?.summary??"The setup changed."} ${formation.plain?.next??""}`,fields:[{name:"What V2 waits for next",value:formation.plain?.next??"—",inline:false},{name:"Technical",value:formation.plain?.technicalLabel??`Stage ${now.stage}/8`,inline:true}]});if(old.tradeKey!==now.tradeKey||old.tradeStatus!==now.tradeStatus){if(t)events.push({type:`paper_${t.status}`,title:`${b.symbol} · ${t.status==="open"?"Paper trade opened":t.status==="armed"?"Paper plan ready":`Paper trade ${up(t.status)}`}`,desc:t.status==="open"?`${up(t.direction)} paper entry is now being tracked.`:`${up(t.direction)} paper state is now ${up(t.status)}.`,fields:tradeFields(t)})}if(old.trust!==now.trust&&(now.trust==="BLOCKED"||old.trust==="BLOCKED"))events.push({type:now.trust==="BLOCKED"?"data_blocked":"data_restored",title:`${b.symbol} · ${now.trust==="BLOCKED"?"Data quality pause":"Data quality restored"}`,desc:b.status?.dataTrust?.reason??`Data trust is ${now.trust}.`,fields:[]});if(old.mode!=="DUAL_ATTENTION"&&now.mode==="DUAL_ATTENTION")events.push({type:"dual_attention",title:`${b.symbol} · Two things are happening`,desc:`An existing ${up(t?.direction)} paper trade is being tracked while a ${up(formation.direction)} setup develops separately. V2 does not treat the new setup as an automatic reversal.`,fields:t?tradeFields(t):[]})}
if(t?.status==="open"){const observedMax=Math.max(Number(t.currentR??-99),Number(t.bestSeenR??-99)),observedMin=Math.min(Number(t.currentR??99),Number(t.worstSeenR??99)),fc=maxCross(observedMax),ac=minCross(observedMin);if(fc!=null&&(now.favMax==null||fc>now.favMax)){events.push({type:`r_plus_${String(fc).replace(".","_")}`,title:`${b.symbol} · Paper trade reached +${f(fc,1)}R`,desc:`The ${up(t.direction)} paper trade has reached at least +${f(fc,1)}R in its observed path. The frozen stop and 2.5R target are unchanged.`,fields:tradeFields(t)});now.favMax=fc}if(ac!=null&&(now.advMin==null||ac<now.advMin)){events.push({type:`r_minus_${String(Math.abs(ac)).replace(".","_")}`,title:`${b.symbol} · Paper trade reached ${f(ac,2)}R`,desc:`The ${up(t.direction)} paper trade has moved against the entry by at least ${f(Math.abs(ac),2)}R. V2 keeps the frozen stop and target unchanged.`,fields:tradeFields(t)});now.advMin=ac}}
const rel=m?.nextRelease,mins=Number(m?.minutesToNext);if(rel?.id&&Number.isFinite(mins)&&rel.impact===3){const state=now.macroNotified[rel.id]??{};if(mins<=240&&!state.h4){events.push({type:"macro_4h",title:`${b.symbol} · Major macro event approaching`,desc:`${rel.title} is due within four hours. ${rel.why} This is a volatility warning, not a directional signal.`,fields:macroFields(m)});state.h4=true}if(mins<=60&&!state.h1){events.push({type:"macro_1h",title:`${b.symbol} · High-impact release within 1 hour`,desc:`${rel.title} is close. Be cautious around the release window; V2 will not rewrite an existing paper trade's frozen geometry.`,fields:macroFields(m)});state.h1=true}if(mins<=15&&t?.status==="open"&&!state.m15){events.push({type:"macro_15m_open_trade",title:`${b.symbol} · Event risk while paper trade is open`,desc:`${rel.title} is within 15 minutes while a ${up(t.direction)} paper trade remains open. Expect possible volatility; the research stop and target remain frozen.`,fields:[...tradeFields(t),...macroFields(m)]});state.m15=true}now.macroNotified={[rel.id]:state}}
for(const x of (b.officialNews??[])){if(x?.relevance<3||now.newsSeen.includes(x.id))continue;events.push({type:"official_news",title:`${b.symbol} · Official policy update`,desc:`${x.source}: ${x.title}`,fields:[{name:"Why it is here",value:"Official central-bank communication with high policy relevance. Context only; no directional score is inferred.",inline:false}]});now.newsSeen.push(x.id)}now.newsSeen=now.newsSeen.slice(-20);
for(const e of events){const msg=await post(e.title,e.desc,e.fields);await log(b.symbol,e.type,{title:e.title,description:e.desc,fields:e.fields},msg?.id);sent.push({symbol:b.symbol,type:e.type,messageId:msg?.id??null})}await save(key,now,events.length>0)}return J({ok:true,generatedAt:new Date().toISOString(),sent})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});