import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import LZMA from "npm:lzma@2.3.2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}}),PIP=.0001,CUT="2026-08-12T19:10:00.000Z";
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const ms=(x:any)=>new Date(x).getTime(),floor15=(x:any)=>Math.floor(ms(x)/900000)*900000,floorHour=(x:number)=>Math.floor(x/3600000)*3600000;
function path(d:Date){return`${d.getUTCFullYear()}/${String(d.getUTCMonth()).padStart(2,"0")}/${String(d.getUTCDate()).padStart(2,"0")}/${String(d.getUTCHours()).padStart(2,"0")}h_ticks.bi5`}
function entryTickHit(dir:string,t:any,e:number){return dir==="long"?t.ask<=e:t.bid>=e}function exitTickHit(dir:string,t:any,s:number,q:number){return dir==="long"?{stop:t.bid<=s,target:t.bid>=q}:{stop:t.ask>=s,target:t.ask<=q}}
function entryMinuteHit(dir:string,b:any,e:number){return dir==="long"?Number(b.ask_low)<=e:Number(b.bid_high)>=e}function exitMinuteHit(dir:string,b:any,s:number,q:number){return dir==="long"?{stop:Number(b.bid_low)<=s,target:Number(b.bid_high)>=q}:{stop:Number(b.ask_high)>=s,target:Number(b.ask_low)<=q}}
async function ticksHour(symbol:string,h:number,cache:Map<string,any[]>){const key=`${symbol}:${h}`;if(cache.has(key))return cache.get(key)!;try{const d=new Date(h),r=await fetch(`https://datafeed.dukascopy.com/datafeed/${symbol}/${path(d)}`,{headers:{"User-Agent":"Mozilla/5.0 V2ExecutionAudit/2.0"},signal:AbortSignal.timeout(7000)});if(!r.ok){cache.set(key,[]);return[]}const enc=new Uint8Array(await r.arrayBuffer());if(!enc.length){cache.set(key,[]);return[]}const raw:any=(LZMA as any).decompress(enc),bytes=raw instanceof Uint8Array?raw:new Uint8Array(raw),dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),out:any[]=[];for(let o=0;o+20<=bytes.length;o+=20){const ofs=dv.getUint32(o,false),ask=dv.getUint32(o+4,false)/100000,bid=dv.getUint32(o+8,false)/100000;if(!(ask>=bid&&bid>0&&ask-bid<.01))continue;out.push({ts:h+ofs,ask,bid,spread:(ask-bid)/PIP})}cache.set(key,out);return out}catch{cache.set(key,[]);return[]}}
async function tickRange(symbol:string,start:number,end:number,cache:Map<string,any[]>){const hs:number[]=[];for(let h=floorHour(start);h<=floorHour(Math.max(start,end-1));h+=3600000)hs.push(h);const xs=(await Promise.all(hs.map(h=>ticksHour(symbol,h,cache)))).flat().filter(t=>t.ts>=start&&t.ts<end);xs.sort((a,b)=>a.ts-b.ts);return xs}
function simTicks(dir:string,xs:any[],entry:number,stop:number,target:number){let entered=false,entryTick:any=null;for(const t of xs){if(!entered){if(!entryTickHit(dir,t,entry))continue;entered=true;entryTick=t;const h=exitTickHit(dir,t,stop,target);if(h.stop||h.target)return{entryTick,kind:h.stop&&h.target?"ambiguous_same_tick":h.stop?"loss":"win",exitTick:t};continue}const h=exitTickHit(dir,t,stop,target);if(h.stop||h.target)return{entryTick,kind:h.stop&&h.target?"ambiguous_same_tick":h.stop?"loss":"win",exitTick:t}}return{entryTick,kind:entered?"open":"not_filled",exitTick:null}}
async function minuteRange(symbol:string,start:number,end:number){const q=await db.from("fx_microstructure_1m").select("ts,bid_open,bid_high,bid_low,bid_close,ask_open,ask_high,ask_low,ask_close,spread_mean_pips,tick_count").eq("symbol",symbol).gte("ts",new Date(start).toISOString()).lt("ts",new Date(end).toISOString()).order("ts",{ascending:true});if(q.error)throw Error(q.error.message);return q.data??[]}
function simMinutes(dir:string,xs:any[],entry:number,stop:number,target:number){let entered=false,entryBar:any=null,totalTicks=0;for(const b of xs){totalTicks+=Number(b.tick_count||0);if(!entered){if(!entryMinuteHit(dir,b,entry))continue;entered=true;entryBar=b;const h=exitMinuteHit(dir,b,stop,target);if(h.stop||h.target)return{entryBar,kind:"ambiguous_entry_minute",exitBar:b,totalTicks};continue}const h=exitMinuteHit(dir,b,stop,target);if(h.stop&&h.target)return{entryBar,kind:"ambiguous_exit_minute",exitBar:b,totalTicks};if(h.stop)return{entryBar,kind:"loss",exitBar:b,totalTicks};if(h.target)return{entryBar,kind:"win",exitBar:b,totalTicks}}return{entryBar,kind:entered?"open":"not_filled",exitBar:null,totalTicks}}
Deno.serve(async()=>{try{const since=new Date(Date.now()-96*3600000).toISOString(),q=await db.from("paper_trades").select("trade_key,symbol,direction,status,armed_at,entry_at,exit_at,entry_price,stop_price,target_price,exit_price,resolution_timeframe,ambiguous_reason,updated_at").in("symbol",["EURUSD","GBPUSD"]).not("entry_at","is",null).gte("updated_at",since).order("updated_at",{ascending:false}).limit(50);if(q.error)throw Error(q.error.message);const cache=new Map<string,any[]>(),out:any[]=[];
for(const t of q.data??[]){const entry=Number(t.entry_price),stop=Number(t.stop_price),target=Number(t.target_price),start=floor15(t.entry_at),entryEnd=start+900000;let method="dukascopy_bid_ask_ticks_v2",entryConfirmed=false,entryAt:any=null,entrySpread:any=null,ticksObserved=0,shadowOutcome:any=null,shadowExitAt:any=null,shadowExitPrice:any=null,auditStatus="unavailable",confidence="none";
const direct=await tickRange(t.symbol,start,entryEnd,cache);if(direct.length){const s=simTicks(t.direction,direct,entry,stop,target);entryConfirmed=Boolean(s.entryTick);entryAt=s.entryTick?new Date(s.entryTick.ts).toISOString():null;entrySpread=s.entryTick?.spread??null;ticksObserved=direct.length;auditStatus=entryConfirmed?"tick_entry_confirmed":"tick_entry_not_confirmed";confidence="tick"}else{const mins=await minuteRange(t.symbol,start,entryEnd);if(mins.length){const s=simMinutes(t.direction,mins,entry,stop,target);entryConfirmed=Boolean(s.entryBar);entryAt=s.entryBar?.ts??null;entrySpread=s.entryBar?.spread_mean_pips??null;ticksObserved=s.totalTicks;auditStatus=entryConfirmed?"minute_entry_confirmed":"minute_entry_not_confirmed";confidence="1m";method="dukascopy_bid_ask_1m_fallback_v2"}}
const end=t.exit_at?Math.min(floor15(t.exit_at)+900000,start+12*3600000):entryEnd;if(t.status==="ambiguous"&&t.exit_at){const xs=await tickRange(t.symbol,start,end,cache);if(xs.length){const s=simTicks(t.direction,xs,entry,stop,target);shadowOutcome=s.kind;if(s.exitTick){shadowExitAt=new Date(s.exitTick.ts).toISOString();shadowExitPrice=s.kind==="win"?target:s.kind==="loss"?stop:null}auditStatus=`shadow_tick_${s.kind}`;confidence="tick";method="dukascopy_bid_ask_ticks_v2"}else{const mins=await minuteRange(t.symbol,start,end),s=simMinutes(t.direction,mins,entry,stop,target);shadowOutcome=s.kind;if(s.exitBar){shadowExitAt=s.exitBar.ts;shadowExitPrice=s.kind==="win"?target:s.kind==="loss"?stop:null}auditStatus=mins.length?`shadow_1m_${s.kind}`:"unavailable";confidence=mins.length?"1m":"none";method="dukascopy_bid_ask_1m_fallback_v2"}}
const row={trade_key:t.trade_key,symbol:t.symbol,direction:t.direction,method,audit_status:auditStatus,entry_confirmed:entryConfirmed,entry_at_tick:entryAt,entry_spread_pips:entrySpread,ticks_observed:ticksObserved,shadow_outcome:shadowOutcome,shadow_exit_at:shadowExitAt,shadow_exit_price:shadowExitPrice,canonical_status:t.status,prospective:ms(t.armed_at)>=ms(CUT),source:"Dukascopy public BID/ASK path",details:{cutoff:CUT,confidence,canonicalResolution:t.resolution_timeframe,canonicalAmbiguousReason:t.ambiguous_reason??null,boundary:"Indicative public BID/ASK path; exact tick when available, otherwise 1m fallback. Not broker-specific execution truth."},updated_at:new Date().toISOString()};const w=await db.from("paper_trade_execution_audit").upsert(row,{onConflict:"trade_key"});if(w.error)throw Error(w.error.message);out.push(row)}return J({ok:true,cutoff:CUT,audited:out.length,rows:out.map(x=>({tradeKey:x.trade_key,status:x.audit_status,entryConfirmed:x.entry_confirmed,entryAt:x.entry_at_tick,entrySpreadPips:x.entry_spread_pips,shadowOutcome:x.shadow_outcome,confidence:x.details.confidence,prospective:x.prospective}))})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});