import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,WH=(Deno.env.get("DISCORD_WEBHOOK_URL")??"").trim();
const db=createClient(SB,KEY,{auth:{persistSession:false}}),H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),f=(x:any,d=2)=>Number.isFinite(Number(x))?Number(x).toFixed(d):"—",cap=(x:any)=>String(x??"—").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
function okHook(){try{const u=new URL(WH);return u.protocol==="https:"&&u.hostname==="discord.com"&&u.pathname.startsWith("/api/webhooks/")}catch{return false}}
async function post(title:string,desc:string,fields:any[]){const u=new URL(WH);u.searchParams.set("wait","true");const r=await fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:"V2 Market Brief",allowed_mentions:{parse:[]},embeds:[{title,description:desc,fields,footer:{text:"V2 XAU research lane · indicative Dukascopy data · no broker execution claim"},timestamp:new Date().toISOString()}]})});const t=await r.text();if(!r.ok)throw Error(`Discord ${r.status}: ${t.slice(0,200)}`);try{return JSON.parse(t)}catch{return{id:null}}}
async function read(){const q=await db.from("discord_alert_state").select("snapshot").eq("state_key","pulse:xau:v1").maybeSingle();if(q.error)throw Error(q.error.message);return q.data?.snapshot??null}
async function save(s:any,sent=false){const row:any={state_key:"pulse:xau:v1",snapshot:s,updated_at:new Date().toISOString()};if(sent)row.last_sent_at=new Date().toISOString();const q=await db.from("discord_alert_state").upsert(row,{onConflict:"state_key"});if(q.error)throw Error(q.error.message)}
async function log(type:string,payload:any,id:any){const q=await db.from("discord_alert_log").insert({symbol:"XAUUSD",event_type:type,discord_message_id:id??null,payload,sent_at:new Date().toISOString()});if(q.error)console.error(q.error.message)}
function fields(s:any,macro:any){const d=s.details?.diagnostics??{},h=s.data_health??{},x=macro?.pairs?.EURUSD?.nextRelease,mins=Number(macro?.pairs?.EURUSD?.minutesToNext),event=x&&Number.isFinite(mins)?`${x.title} · ${mins<=0?"release window":mins<60?`${Math.max(0,Math.round(mins))}m`:`${Math.floor(mins/60)}h ${Math.round(mins%60)}m`}`:"No confirmed high-impact USD event";return[{name:"Gold reference",value:`$${f(s.reference_price,2)} · ${s.market_session??"—"}`,inline:true},{name:"Structure",value:`Stage ${s.formation_stage??"—"}/8 · ${cap(s.formation_direction||"none")}`,inline:true},{name:"D1 / H4 / H1 / M15",value:`${cap(s.d1_trend)} / ${cap(s.h4_trend)} / ${cap(s.h1_trend)} / ${cap(s.m15_trend)}`,inline:false},{name:"Context",value:`${cap(d.structureContext)} · ${cap(s.regime)} · shift risk ${cap(d.shiftRisk)}`,inline:false},{name:"USD event clock",value:event,inline:false},{name:"Data",value:`${h.structureStatus??"—"} · latest minute ${h.referenceMinute?new Date(h.referenceMinute).toISOString().slice(11,16)+" UTC":"—"}`,inline:false}]}
Deno.serve(async req=>{if(req.method!=="GET")return J({error:"GET only"},405);try{if(!okHook())return J({configured:false},503);const [q,mr]=await Promise.all([db.from("market_states").select("*").eq("symbol","XAUUSD").maybeSingle(),fetch(`${SB}/functions/v1/macro-context`,{headers:{"Cache-Control":"no-cache"},signal:AbortSignal.timeout(15000)})]);if(q.error)throw Error(q.error.message);const s=q.data;if(!s)return J({ok:true,sent:[],note:"No XAU state yet"});const macro=mr.ok?await mr.json():null,old=await read(),h=s.data_health??{},d=s.details?.diagnostics??{},rel=macro?.pairs?.EURUSD?.nextRelease,mins=Number(macro?.pairs?.EURUSD?.minutesToNext),notified:any=old?.macroNotified??{},now:any={stage:Number(s.formation_stage??0),direction:s.formation_direction??null,code:s.formation_code??null,health:h.structureStatus??null,context:d.structureContext??null,d1:s.d1_trend,h4:s.h4_trend,h1:s.h1_trend,m15:s.m15_trend,reference:Number(s.reference_price),asOf:s.as_of,macroNotified:notified},events:any[]=[];
if(!old)events.push({type:"xau_research_live",title:"XAUUSD · Gold research lane is live",desc:`V2 now has a near-live gold feed and a separate XAU market-state engine. Current action: ${now.stage>=3?"WAIT / WATCH":"WATCH"}. Gold entries remain shadow-only until XAU-specific validation passes.`});
else{if((old.stage!==now.stage||old.direction!==now.direction)&&now.stage>=3)events.push({type:`xau_stage_${now.stage}`,title:`XAUUSD · ${s.formation_label??"Gold structure changed"}`,desc:now.stage>=6?"A gold POI/entry-zone sequence has matured, but V2 is still collecting XAU-specific evidence before paper-entry promotion.":now.stage===5?"Gold has produced the structural BOS checkpoint. V2 is now looking for a clean XAU POI under the separate gold calibration.":"Gold structure changed. V2 is monitoring the next completed checkpoint; this is not an executable trade alert."});if(old.health!==now.health&&(now.health==="stale"||old.health==="stale"))events.push({type:now.health==="stale"?"xau_data_stale":"xau_data_restored",title:`XAUUSD · ${now.health==="stale"?"Gold data is stale":"Gold data is current again"}`,desc:now.health==="stale"?"V2 has paused interpretation of new gold structure until completed candles catch up.":"Completed XAU candles are current again; research monitoring has resumed."});if(old.context!==now.context&&now.stage>=3)events.push({type:"xau_context_change",title:"XAUUSD · Higher-timeframe context changed",desc:`The active ${cap(now.direction)} formation is now ${cap(now.context)} relative to D1/H4/H1/M15 context. V2 remains research-only on XAU.`})}
if(rel?.id&&rel.impact===3&&Number.isFinite(mins)){const z=notified[rel.id]??{};if(mins<=240&&mins>-30&&!z.h4){events.push({type:"xau_macro_4h",title:"XAUUSD · High-impact USD event approaching",desc:`${rel.title} is within four hours. Gold can reprice quickly around USD inflation/rate expectations, so V2 treats the event window as a volatility-risk modifier, not a directional signal.`});z.h4=true}if(mins<=60&&mins>-30&&!z.h1){events.push({type:"xau_macro_1h",title:"XAUUSD · High-impact USD release within 1 hour",desc:`${rel.title} is close. New gold structure immediately around the release will be separated from ordinary-session evidence.`});z.h1=true}if(mins<=15&&mins>-15&&!z.m15){events.push({type:"xau_macro_15m",title:"XAUUSD · Event window is imminent",desc:`${rel.title} is within 15 minutes. V2 will not promote a gold entry from this event window while XAU remains under validation.`});z.m15=true}now.macroNotified={[rel.id]:z}}
const sent:any[]=[];for(const e of events){const fs=fields(s,macro),m=await post(e.title,e.desc,fs);await log(e.type,{title:e.title,description:e.desc,fields:fs},m?.id);sent.push({type:e.type,messageId:m?.id??null})}await save(now,events.length>0);return J({ok:true,generatedAt:new Date().toISOString(),sent,state:now,macro:{nextRelease:rel?.title??null,minutesToNext:Number.isFinite(mins)?mins:null}})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});