import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,WH=(Deno.env.get("DISCORD_WEBHOOK_URL")??"").trim();
const db=createClient(SB,KEY,{auth:{persistSession:false}}),PIP=.0001,H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const R=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
async function cronOk(req:Request){const k=req.headers.get("x-v2-cron-key")??"";if(!k)return false;const q=await db.from("v2_runtime_secrets").select("secret").eq("name","cron").maybeSingle();if(q.error||!q.data?.secret)return false;const a=new TextEncoder().encode(k),b=new TextEncoder().encode(String(q.data.secret));if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]!^b[i]!;return d===0}
const n=(x:any)=>x===null||x===undefined||x===""?null:(Number.isFinite(Number(x))?Number(x):null),f=(x:any,d=2)=>n(x)!=null?Number(x).toFixed(d):"—",p=(x:any)=>n(x)!=null?Number(x).toFixed(5):"—",signed=(x:any,d=2,s="")=>n(x)==null?"—":`${Number(x)>=0?"+":""}${Number(x).toFixed(d)}${s}`,up=(x:any)=>String(x??"—").toUpperCase();
function webhookOk(){try{const u=new URL(WH);return u.protocol==="https:"&&u.hostname==="discord.com"&&u.pathname.startsWith("/api/webhooks/")}catch{return false}}
async function post(title:string,description:string,fields:any[]){const u=new URL(WH);u.searchParams.set("wait","true");const q=await fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:"V2 Market Brief",allowed_mentions:{parse:[]},embeds:[{title,description,fields,footer:{text:"V2 FX paper research · text alerts only · not broker execution"},timestamp:new Date().toISOString()}]})});const t=await q.text();if(!q.ok)throw Error(`Discord ${q.status}: ${t.slice(0,220)}`);try{return JSON.parse(t)}catch{return{id:null}}}
async function state(k:string){const q=await db.from("discord_alert_state").select("snapshot").eq("state_key",k).maybeSingle();if(q.error)throw Error(q.error.message);return q.data?.snapshot??null}
async function save(k:string,s:any){const now=new Date().toISOString(),q=await db.from("discord_alert_state").upsert({state_key:k,snapshot:s,last_sent_at:now,updated_at:now},{onConflict:"state_key"});if(q.error)throw Error(q.error.message)}
async function log(symbol:string,type:string,payload:any,id:any){const q=await db.from("discord_alert_log").insert({symbol,event_type:type,discord_message_id:id??null,payload,sent_at:new Date().toISOString()});if(q.error)console.error(q.error.message)}
function copy(t:any){const r=n(t.gross_r);if(t.status==="win")return{title:`${t.symbol} · Paper target reached`,desc:`The ${up(t.direction)} paper trade closed at the target${r==null?"":` for +${f(r)}R`}.`,type:"paper_closed_win"};if(t.status==="loss")return{title:`${t.symbol} · Paper stop reached`,desc:`The ${up(t.direction)} paper trade closed at the stop${r==null?"":` for ${f(r)}R`}.`,type:"paper_closed_loss"};if(t.status==="timeout")return{title:`${t.symbol} · Paper trade timed out`,desc:`Neither stop nor target resolved before V2's 48-bar time limit${r==null?"":` · marked at ${signed(r)}R`}.`,type:"paper_closed_timeout"};return{title:`${t.symbol} · Paper outcome unresolved`,desc:"The public price path could not prove which level was reached first, so V2 assigns no P&L.",type:"paper_closed_ambiguous"}}
function fallbackPips(t:any){const e=n(t.entry_price),s=n(t.stop_price),q=n(t.target_price),x=n(t.exit_price);const risk=e!=null&&s!=null?Math.abs(e-s)/PIP:null,target=e!=null&&q!=null?Math.abs(q-e)/PIP:null,result=e!=null&&x!=null&&t.status!=="ambiguous"?(t.direction==="long"?x-e:e-x)/PIP:null;return{risk,target,result,rr:risk&&target?target/risk:2.5}}
Deno.serve(async req=>{if(req.method!=="GET")return R({error:"GET only"},405);try{if(!(await cronOk(req)))return R({error:"unauthorized"},401);if(!webhookOk())return R({configured:false},503);const since=new Date(Date.now()-48*3600_000).toISOString();const[q,pr]=await Promise.all([db.from("paper_trades").select("trade_key,symbol,direction,status,entry_at,exit_at,entry_price,stop_price,target_price,exit_price,gross_r,bars_held,ambiguous_reason,updated_at").in("status",["win","loss","timeout","ambiguous"]).gte("updated_at",since).order("updated_at",{ascending:true}),fetch(`${SB}/functions/v1/portfolio-snapshot`,{headers:{"Cache-Control":"no-cache"}})]);if(q.error)throw Error(q.error.message);const trades=q.data??[],port=pr.ok?await pr.json():null,sent:any[]=[];
for(const t of trades){const key=`closure:v1:${t.trade_key}:${t.status}:${t.exit_at??t.updated_at}`;if(await state(key))continue;const c=copy(t),pm=(port?.tradeMetrics??[]).find((x:any)=>x.tradeKey===t.trade_key),led=(port?.ledger??[]).find((x:any)=>x.tradeKey===t.trade_key),fb=fallbackPips(t),risk=n(pm?.riskPips)??fb.risk,target=n(pm?.targetPips)??fb.target,result=n(pm?.realizedPips)??fb.result,rr=n(pm?.rewardRisk)??fb.rr,a=port?.account,fields:any[]=[{name:"Result",value:t.status==="ambiguous"?"Unresolved · no P&L assigned":`${signed(t.gross_r)}R · ${result==null?"—":signed(result,1," pips")}`,inline:false},{name:"Trade plan",value:`Entry ${p(t.entry_price)} · Stop ${p(t.stop_price)} · Target ${p(t.target_price)}\n${risk==null?"—":`${f(risk,1)} pips`} risk · ${target==null?"—":`${f(target,1)} pips`} target · RR 1:${f(rr,2)}`,inline:false}];if(a)fields.push({name:"Paper account",value:t.status==="ambiguous"?`Balance stays $${f(a.realizedBalanceUsd)} · ${signed(a.growthPct,2,"%")} since $500`:`This trade ${led?.pnlUsd==null?"—":signed(led.pnlUsd,2," USD")} · balance $${f(a.realizedBalanceUsd)} · ${signed(a.growthPct,2,"%")} since $500`,inline:false});if(t.status==="ambiguous"&&t.ambiguous_reason)fields.push({name:"Why it is unresolved",value:String(t.ambiguous_reason).slice(0,800),inline:false});const msg=await post(c.title,c.desc,fields),payload={title:c.title,description:c.desc,fields,tradeKey:t.trade_key};await log(t.symbol,c.type,payload,msg?.id);await save(key,{messageId:msg?.id??null,tradeKey:t.trade_key,status:t.status});sent.push({tradeKey:t.trade_key,type:c.type,messageId:msg?.id??null})}return R({ok:true,generatedAt:new Date().toISOString(),portfolio:port?.account??null,sent})}catch(e){console.error(e);return R({error:e instanceof Error?e.message:String(e)},500)}});