import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,WH=(Deno.env.get("DISCORD_WEBHOOK_URL")??"").trim();
const db=createClient(SB,KEY,{auth:{persistSession:false}}),PIP=.0001;
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const R=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const n=(x:any)=>x===null||x===undefined||x===""?null:(Number.isFinite(Number(x))?Number(x):null);
const f=(x:any,d=2)=>n(x)!=null?Number(x).toFixed(d):"—";
const p=(x:any)=>n(x)!=null?Number(x).toFixed(5):"—";
const signed=(x:any,d=2,s="")=>n(x)==null?"—":`${Number(x)>=0?"+":""}${Number(x).toFixed(d)}${s}`;
const up=(x:any)=>String(x??"—").toUpperCase();

function webhookOk(){try{const u=new URL(WH);return u.protocol==="https:"&&u.hostname==="discord.com"&&u.pathname.startsWith("/api/webhooks/")}catch{return false}}
async function post(title:string,description:string,fields:any[]){const u=new URL(WH);u.searchParams.set("wait","true");const q=await fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:"V2 Market Brief",allowed_mentions:{parse:[]},embeds:[{title,description,fields,footer:{text:"V2 canonical FX paper journal · research only · not broker execution"},timestamp:new Date().toISOString()}]})});const t=await q.text();if(!q.ok)throw Error(`Discord ${q.status}: ${t.slice(0,220)}`);return JSON.parse(t)}
async function state(k:string){const q=await db.from("discord_alert_state").select("snapshot").eq("state_key",k).maybeSingle();if(q.error)throw Error(q.error.message);return q.data?.snapshot??null}
async function save(k:string,s:any){const now=new Date().toISOString();const q=await db.from("discord_alert_state").upsert({state_key:k,snapshot:s,last_sent_at:now,updated_at:now},{onConflict:"state_key"});if(q.error)throw Error(q.error.message)}
async function log(symbol:string,type:string,payload:any,id:any){const q=await db.from("discord_alert_log").insert({symbol,event_type:type,discord_message_id:id??null,payload,sent_at:new Date().toISOString()});if(q.error)console.error(q.error.message)}
function copy(t:any){const r=n(t.gross_r);if(t.status==="win")return{title:`${t.symbol} · Paper target reached`,desc:`The ${up(t.direction)} canonical paper trade closed at the frozen target${r==null?"":` for +${f(r)}R`}.`,type:"paper_closed_win"};if(t.status==="loss")return{title:`${t.symbol} · Paper stop reached`,desc:`The ${up(t.direction)} canonical paper trade closed at the frozen stop${r==null?"":` for ${f(r)}R`}.`,type:"paper_closed_loss"};if(t.status==="timeout")return{title:`${t.symbol} · Paper trade timed out`,desc:`The ${up(t.direction)} canonical paper trade reached V2's frozen time-exit rule${r==null?"":` at ${signed(r)}R`}. The hold-to-SL/TP policy remains shadow research.`,type:"paper_closed_timeout"};return{title:`${t.symbol} · Paper outcome ambiguous`,desc:`The ${up(t.direction)} plan reached an entry/exit sequence whose ordering cannot be proven from the available public path data. V2 assigns no P&L.`,type:"paper_closed_ambiguous"}}
function fallbackPips(t:any){const e=n(t.entry_price),s=n(t.stop_price),q=n(t.target_price),x=n(t.exit_price);const risk=e!=null&&s!=null?Math.abs(e-s)/PIP:null,target=e!=null&&q!=null?Math.abs(q-e)/PIP:null,result=e!=null&&x!=null&&t.status!=="ambiguous"?(t.direction==="long"?x-e:e-x)/PIP:null;return{risk,target,result,rr:risk&&target?target/risk:2.5}}

Deno.serve(async req=>{if(req.method!=="GET")return R({error:"GET only"},405);try{if(!webhookOk())return R({configured:false},503);const since=new Date(Date.now()-48*3600_000).toISOString();const[q,pr]=await Promise.all([db.from("paper_trades").select("trade_key,symbol,direction,status,entry_at,exit_at,entry_price,stop_price,target_price,exit_price,gross_r,bars_held,setup_condition,ambiguous_reason,updated_at").in("status",["win","loss","timeout","ambiguous"]).gte("updated_at",since).order("updated_at",{ascending:true}),fetch(`${SB}/functions/v1/portfolio-snapshot`,{headers:{"Cache-Control":"no-cache"}})]);if(q.error)throw Error(q.error.message);const trades=q.data??[],port=pr.ok?await pr.json():null,sent:any[]=[];
for(const t of trades){const key=`closure:v1:${t.trade_key}:${t.status}:${t.exit_at??t.updated_at}`;if(await state(key))continue;const c=copy(t),sh=await db.from("exit_policy_shadow").select("status,gross_r,exit_at").eq("trade_key",t.trade_key).eq("policy","hold_sltp").maybeSingle(),alt=sh.data&&sh.data.status!=="excluded_ambiguous_parent"&&n(sh.data.gross_r)!=null?`${signed(sh.data.gross_r)}R · ${String(sh.data.status).replaceAll("_"," ")}`:"Not safely scoreable yet",pm=(port?.tradeMetrics??[]).find((x:any)=>x.tradeKey===t.trade_key),led=(port?.ledger??[]).find((x:any)=>x.tradeKey===t.trade_key),fb=fallbackPips(t),riskPips=n(pm?.riskPips)??fb.risk,targetPips=n(pm?.targetPips)??fb.target,resultPips=n(pm?.realizedPips)??fb.result,rr=n(pm?.rewardRisk)??fb.rr,a=port?.account;
const fields:any[]=[{name:"Canonical outcome",value:t.status==="ambiguous"?"AMBIGUOUS · no P&L assigned":`${signed(t.gross_r)}R · ${resultPips==null?"—":signed(resultPips,1," pips")} · ${up(t.status)}`,inline:false},{name:"Risk / target / RR",value:`${riskPips==null?"—":`${f(riskPips,1)} pips`} risk · ${targetPips==null?"—":`${f(targetPips,1)} pips`} target · RR 1:${f(rr,2)}`,inline:false},{name:"Hold-to-SL/TP shadow",value:alt,inline:true},{name:"Frozen levels",value:`Entry ${p(t.entry_price)} · Stop ${p(t.stop_price)} · Target ${p(t.target_price)}`,inline:false},{name:"Setup condition",value:String(t.setup_condition??"—").replaceAll("_"," "),inline:true}];
if(a)fields.push({name:"$500 paper account",value:t.status==="ambiguous"?`Balance stays $${f(a.realizedBalanceUsd)} · ${signed(a.growthPct,2,"%")} growth · ambiguous trade excluded`:`Trade P&L ${led?.pnlUsd==null?"—":signed(led.pnlUsd,2," USD")} · balance after ${led?.balanceAfter==null?`$${f(a.realizedBalanceUsd)}`:`$${f(led.balanceAfter)}`} · current account $${f(a.realizedBalanceUsd)} (${signed(a.growthPct,2,"%")} growth)`,inline:false});
if(t.ambiguous_reason)fields.push({name:"Why ambiguous",value:String(t.ambiguous_reason).slice(0,900),inline:false});const msg=await post(c.title,c.desc,fields),payload={title:c.title,description:c.desc,fields,tradeKey:t.trade_key};await log(t.symbol,c.type,payload,msg?.id);await save(key,{messageId:msg?.id??null,tradeKey:t.trade_key,status:t.status});sent.push({tradeKey:t.trade_key,type:c.type,messageId:msg?.id??null})}
return R({ok:true,generatedAt:new Date().toISOString(),portfolio:port?.account??null,sent})}catch(e){console.error(e);return R({error:e instanceof Error?e.message:String(e)},500)}});