import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,WH=(Deno.env.get("DISCORD_WEBHOOK_URL")??"").trim();
const db=createClient(SB,KEY,{auth:{persistSession:false}}),PIP=.0001,H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const n=(x:any)=>x===null||x===undefined||x===""?null:(Number.isFinite(Number(x))?Number(x):null),f=(x:any,d=2)=>n(x)!=null?Number(x).toFixed(d):"—",p5=(x:any)=>n(x)!=null?Number(x).toFixed(5):"—",up=(x:any)=>String(x??"—").toUpperCase(),signed=(x:any,d=2,s="")=>n(x)==null?"—":`${Number(x)>=0?"+":""}${Number(x).toFixed(d)}${s}`;
function webhookOk(){try{const u=new URL(WH);return u.protocol==="https:"&&u.hostname==="discord.com"&&u.pathname.startsWith("/api/webhooks/")}catch{return false}}
async function post(title:string,description:string,fields:any[]=[]){const u=new URL(WH);u.searchParams.set("wait","true");const r=await fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:"V2 Market Brief",allowed_mentions:{parse:[]},embeds:[{title,description,fields,footer:{text:"V2 FX paper research · text alerts only · not broker execution"},timestamp:new Date().toISOString()}]})});const t=await r.text();if(!r.ok)throw Error(`Discord ${r.status}: ${t.slice(0,220)}`);try{return JSON.parse(t)}catch{return{id:null}}}
async function read(k:string){const q=await db.from("discord_alert_state").select("snapshot").eq("state_key",k).maybeSingle();if(q.error)throw Error(q.error.message);return q.data?.snapshot??null}
async function save(k:string,s:any,sent=false){const row:any={state_key:k,snapshot:s,updated_at:new Date().toISOString()};if(sent)row.last_sent_at=new Date().toISOString();const q=await db.from("discord_alert_state").upsert(row,{onConflict:"state_key"});if(q.error)throw Error(q.error.message)}
async function log(symbol:string|null,type:string,payload:any,id:any){const q=await db.from("discord_alert_log").insert({symbol,event_type:type,discord_message_id:id??null,payload,sent_at:new Date().toISOString()});if(q.error)console.error("log",q.error.message)}
const stageAlert=new Set([3,4,5,6,7,8]),fav=[.5,1,1.5,2],adv=[-.5,-.75];
function maxCross(x:number|null){if(x==null)return null;const z=fav.filter(v=>x>=v);return z.length?Math.max(...z):null}function minCross(x:number|null){if(x==null)return null;const z=adv.filter(v=>x<=v);return z.length?Math.min(...z):null}
function pips(t:any){const e=n(t?.entryPrice),s=n(t?.stopPrice),q=n(t?.targetPrice),m=n(t?.currentMark);if(e==null)return{risk:null,target:null,current:null,rr:n(t?.rewardR)??2.5};const risk=s==null?null:Math.abs(e-s)/PIP,target=q==null?null:Math.abs(q-e)/PIP,current=t?.status==="open"&&m!=null?(t.direction==="long"?m-e:e-m)/PIP:null;return{risk,target,current,rr:risk&&target?target/risk:n(t?.rewardR)??2.5}}
function portfolioMetric(port:any,t:any){return(port?.tradeMetrics??[]).find((x:any)=>x.tradeKey===t?.tradeKey)??null}
function accountField(port:any,t:any){const a=port?.account;if(!a)return null;const m=portfolioMetric(port,t);return{name:"Paper account",value:`$${f(a.realizedBalanceUsd)} · ${signed(a.growthPct,2,"%")} since $500${m?.riskUsd!=null?` · this trade risk $${f(m.riskUsd)}`:""}`,inline:false}}
function tradeFields(t:any,port:any){const pp=pips(t),pm=portfolioMetric(port,t),cur=pm?.currentPips??pp.current,risk=pm?.riskPips??pp.risk,target=pm?.targetPips??pp.target,fields:any[]=[{name:"Trade",value:`${up(t.direction)} · ${t.currentR==null?"—":`${signed(t.currentR)}R`} · ${cur==null?"—":signed(cur,1," pips")}`,inline:false},{name:"Plan",value:`Entry ${p5(t.entryPrice)} · Stop ${p5(t.stopPrice)} · Target ${p5(t.targetPrice)}\n${risk==null?"—":`${f(risk,1)} pips`} risk · ${target==null?"—":`${f(target,1)} pips`} target · RR 1:${f(pp.rr,2)}`,inline:false}];const af=accountField(port,t);if(af)fields.push(af);return fields}
function watchField(b:any){const st=Number(b?.formation?.stage??0),dist=n(b?.formation?.distanceToPoiAtr);let v="No mature setup. Normal monitoring is enough.";if(st===3||st===4)v="A liquidity sweep is active. Watch for a confirmed break of structure (BOS).";if(st===5)v="Break of structure is confirmed. Wait for V2 to identify a fresh entry zone (POI).";if(st===6)v=`A fresh entry zone (POI) is ready${dist!=null?` · about ${f(dist,2)} ATR away`:""}. The paper entry remains the 50% midpoint.`;if(st===7)v=`Price is approaching the entry zone${dist!=null?` · about ${f(dist,2)} ATR away`:""}. A shallow touch is not an entry; V2 waits for the midpoint.`;if(st>=8)v="Price is at the entry area. The paper engine is checking the midpoint rule.";if(b?.trade?.status==="open")v="Paper trade is open. Track the frozen stop and target; a new setup does not automatically reverse it.";return{name:"What to watch next",value:v,inline:false}}
function rangeField(c:any){const r=c?.ranges;if(!r)return{name:"Recent range",value:"Range context unavailable.",inline:false};const pair=(x:any)=>x?`${p5(x.high)} / ${p5(x.low)}`:"—";return{name:"Recent highs / lows",value:`1h ${pair(r.oneHour)} · Today ${pair(r.today)} · Week ${pair(r.week)}`,inline:false}}
function macroFields(m:any){const x=m?.nextRelease;if(!x)return[];const e=x.primaryEvent??x.events?.[0]??{};return[{name:"Scheduled event",value:`${x.title} · ${new Date(x.timeUtc).toISOString().slice(0,16).replace("T"," ")} UTC`,inline:false},{name:"Consensus / previous",value:`${e.consensus||e.forecast||"—"} / ${e.previous||"—"}`,inline:true}]}
function shockEvent(symbol:string,c:any,m:any){const s=c?.shock;if(!s?.active)return null;const arrow=s.direction==="up"?"↑":"↓",mins=n(m?.minutesToNext),near=m?.nextRelease&&mins!=null&&mins>=0&&mins<=20?`A scheduled event is nearby: ${m.nextRelease.title} in about ${f(mins,0)} minutes.`:"V2 has not confirmed the cause from price alone. It may be news, a headline, liquidity, or another market event.";return{type:"sharp_move",title:`${symbol} · Unusually sharp move ${arrow}`,desc:`Price moved about ${f(s.movePips,1)} pips ${s.direction} in roughly ${s.windowMinutes} minutes — much faster than its recent normal pace.`,fields:[{name:"Why V2 alerted",value:`${s.severity} move · about ${f(s.moveVsNormal,1)}× the recent short-term pace · 15m ATR about ${f(s.atrPips,1)} pips.`,inline:false},rangeField(c),{name:"Possible cause",value:near,inline:false},{name:"What this means",value:"Volatility has jumped. This is a market-awareness alert, not a trade signal. Wait for the normal V2 setup rules before treating it as an entry.",inline:false}]}}
function favorableMilestone(b:any,t:any,port:any,threshold:number,observedMax:number){const current=n(t?.currentR),best=n(t?.bestSeenR),peak=best==null?observedMax:Math.max(best,current??best);return{type:`r_plus_${String(threshold).replace(".","_")}`,title:`${b.symbol} · Paper trade crossed +${f(threshold,1)}R`,desc:"The trade crossed this milestone. Current R may be lower if price has retraced; stop and target remain unchanged.",fields:[{name:"Milestone",value:`Crossed +${f(threshold,1)}R · peak ${signed(peak,2)}R · current ${current==null?"—":`${signed(current,2)}R`}`,inline:false},...tradeFields(t,port),watchField(b)]}}
function adverseMilestone(b:any,t:any,port:any,threshold:number,observedMin:number){const current=n(t?.currentR),worst=n(t?.worstSeenR),low=worst==null?observedMin:Math.min(worst,current??worst);return{type:`r_minus_${String(Math.abs(threshold)).replace(".","_")}`,title:`${b.symbol} · Paper trade crossed ${f(threshold,2)}R`,desc:"The trade crossed this adverse milestone. Current R may have recovered; stop and target remain unchanged.",fields:[{name:"Milestone",value:`Crossed ${f(threshold,2)}R · worst ${signed(low,2)}R · current ${current==null?"—":`${signed(current,2)}R`}`,inline:false},...tradeFields(t,port),watchField(b)]}}
Deno.serve(async req=>{if(req.method!=="GET")return J({error:"GET only"},405);try{if(!webhookOk())return J({configured:false},503);const[br,pr,cr]=await Promise.all([fetch(`${SB}/functions/v1/trader-brief`,{headers:{"Cache-Control":"no-cache"}}),fetch(`${SB}/functions/v1/portfolio-snapshot`,{headers:{"Cache-Control":"no-cache"}}),fetch(`${SB}/functions/v1/fx-market-context`,{headers:{"Cache-Control":"no-cache"}})]);if(!br.ok)throw Error(`trader-brief ${br.status}`);const brief=await br.json(),port=pr.ok?await pr.json():null,ctx=cr.ok?await cr.json():null,pairs=Array.isArray(brief?.pairs)?brief.pairs:[],sent:any[]=[];
for(const b of pairs){const key=`pulse:v22:${b.symbol}`,old=await read(key),t=b.trade??null,m=b.macro??{},formation=b.formation??{},c=ctx?.pairs?.[b.symbol]??null,now:any={stage:Number(formation.stage??0),direction:formation.direction??null,mode:b.status?.decisionMode??null,trust:b.status?.dataTrust?.level??null,tradeKey:t?.tradeKey??null,tradeStatus:t?.status??null,favMax:old?.tradeKey===t?.tradeKey?(old?.favMax??null):null,advMin:old?.tradeKey===t?.tradeKey?(old?.advMin??null):null,macroNotified:old?.macroNotified??{},newsSeen:Array.isArray(old?.newsSeen)?old.newsSeen:[],moveAlertAt:old?.moveAlertAt??null,moveSeverity:old?.moveSeverity??null,moveDirection:old?.moveDirection??null};const events:any[]=[];
if(old){if((old.stage!==now.stage||old.direction!==now.direction)&&stageAlert.has(now.stage))events.push({type:`stage_${now.stage}`,title:`${b.symbol} · ${formation.plain?.title??"Setup update"}`,desc:formation.plain?.summary??"The setup changed.",fields:[{name:"What changed",value:`Stage ${old.stage??"—"} → ${now.stage}/8${old.direction&&old.direction!==now.direction?` · ${up(old.direction)} → ${up(now.direction)}`:""}`,inline:false},watchField(b),rangeField(c)]});if(old.tradeKey!==now.tradeKey||old.tradeStatus!==now.tradeStatus){if(t)events.push({type:`paper_${t.status}`,title:`${b.symbol} · ${t.status==="open"?"Paper trade opened":t.status==="armed"?"Paper plan ready":`Paper trade ${up(t.status)}`}`,desc:t.status==="open"?`${up(t.direction)} paper entry is now being tracked.`:`${up(t.direction)} paper state is now ${up(t.status)}.`,fields:[...tradeFields(t,port),watchField(b)]})}if(old.trust!==now.trust&&(now.trust==="BLOCKED"||old.trust==="BLOCKED"))events.push({type:now.trust==="BLOCKED"?"data_blocked":"data_restored",title:`${b.symbol} · ${now.trust==="BLOCKED"?"Data paused":"Data restored"}`,desc:b.status?.dataTrust?.reason??`Data status is ${now.trust}.`,fields:[watchField(b)]});if(old.mode!=="DUAL_ATTENTION"&&now.mode==="DUAL_ATTENTION")events.push({type:"dual_attention",title:`${b.symbol} · Trade open while a new setup develops`,desc:"V2 is tracking the open paper trade and the new setup separately. The new setup is not an automatic reversal.",fields:[...(t?tradeFields(t,port):[]),watchField(b)]})}
if(t?.status==="open"){const current=n(t.currentR),best=n(t.bestSeenR),worst=n(t.worstSeenR),observedMax=Math.max(current??-99,best??-99),observedMin=Math.min(current??99,worst??99),fc=maxCross(observedMax),ac=minCross(observedMin);if(fc!=null&&(now.favMax==null||fc>now.favMax)){events.push(favorableMilestone(b,t,port,fc,observedMax));now.favMax=fc}if(ac!=null&&(now.advMin==null||ac<now.advMin)){events.push(adverseMilestone(b,t,port,ac,observedMin));now.advMin=ac}}
const rel=m?.nextRelease,mins=Number(m?.minutesToNext);if(rel?.id&&Number.isFinite(mins)&&mins>=0&&rel.impact===3){const state=now.macroNotified[rel.id]??{};if(mins<=240&&!state.h4){events.push({type:"macro_4h",title:`${b.symbol} · Major event later today`,desc:`${rel.title} is due within four hours. Volatility may increase around the release.`,fields:[...macroFields(m),watchField(b)]});state.h4=true}if(mins<=60&&!state.h1){events.push({type:"macro_1h",title:`${b.symbol} · High-impact event within 1 hour`,desc:`${rel.title} is close. Expect possible volatility; existing paper levels stay unchanged.`,fields:[...macroFields(m),rangeField(c)]});state.h1=true}if(mins<=15&&t?.status==="open"&&!state.m15){events.push({type:"macro_15m_open_trade",title:`${b.symbol} · Event risk while paper trade is open`,desc:`${rel.title} is within 15 minutes while the ${up(t.direction)} paper trade remains open.`,fields:[...tradeFields(t,port),...macroFields(m)]});state.m15=true}now.macroNotified={[rel.id]:state}}
for(const x of (b.officialNews??[])){if(x?.relevance<3||now.newsSeen.includes(x.id))continue;events.push({type:"official_news",title:`${b.symbol} · Important policy update`,desc:`${x.source}: ${x.title}`,fields:[{name:"Why this matters",value:"This is official central-bank information. V2 does not infer trade direction from the headline alone.",inline:false},watchField(b)]});now.newsSeen.push(x.id)}now.newsSeen=now.newsSeen.slice(-20);
const se=shockEvent(b.symbol,c,m);if(se){const last=now.moveAlertAt?new Date(now.moveAlertAt).getTime():0,cool=Date.now()-last>=20*60_000,flip=now.moveDirection&&now.moveDirection!==c.shock.direction,escalate=now.moveSeverity==="SHARP"&&c.shock.severity==="EXTREME";if(cool||flip||escalate||!last){events.push(se);now.moveAlertAt=new Date().toISOString();now.moveSeverity=c.shock.severity;now.moveDirection=c.shock.direction}}
for(const e of events){const msg=await post(e.title,e.desc,e.fields);await log(b.symbol,e.type,{title:e.title,description:e.desc,fields:e.fields},msg?.id);sent.push({symbol:b.symbol,type:e.type,messageId:msg?.id??null})}await save(key,now,events.length>0)}return J({ok:true,version:"discord-pulse-v6",generatedAt:new Date().toISOString(),portfolio:port?.account??null,marketContext:ctx?.pairs??null,sent})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});
