import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SB,KEY,{auth:{persistSession:false}}),PIP=.0001;
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const n=(x:any)=>x===null||x===undefined?null:(Number.isFinite(Number(x))?Number(x):null);
const med=(xs:number[])=>{const a=xs.filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const pp=(a:any,b:any)=>n(a)!=null&&n(b)!=null?(Number(a)-Number(b))/PIP:null;
function range(rows:any[]){if(!rows.length)return null;return{high:Math.max(...rows.map(r=>Number(r.high))),low:Math.min(...rows.map(r=>Number(r.low)))};}
function mondayStart(t:number){const d=new Date(t),day=(d.getUTCDay()+6)%7;return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()-day);}
function nearestBefore(rows:any[],target:number,maxAgeMin:number){let best=null;for(const r of rows){const t=new Date(r.as_of).getTime();if(t<=target&&(!best||t>new Date(best.as_of).getTime()))best=r}if(!best)return null;return target-new Date(best.as_of).getTime()<=maxAgeMin*60_000?best:null;}
function shock(symbol:string,state:any,bars:any[],hist:any[]){if(!bars.length||!state)return{severity:"NORMAL",active:false};const latest=bars.at(-1),base=bars.slice(Math.max(0,bars.length-97),-1),bodies=base.map(r=>Math.abs(Number(r.close)-Number(r.open))/PIP),ranges=base.map(r=>(Number(r.high)-Number(r.low))/PIP),medianBody=med(bodies)??0,medianRange=med(ranges)??0,body=Math.abs(Number(latest.close)-Number(latest.open))/PIP,barRange=(Number(latest.high)-Number(latest.low))/PIP,bodyMultiple=body/Math.max(medianBody,.25),rangeMultiple=barRange/Math.max(medianRange,.5),nowTs=new Date(state.as_of).getTime(),pNow=Number(state.reference_price),p5=nearestBefore(hist,nowTs-4*60_000,5),p15=nearestBefore(hist,nowTs-13*60_000,7),move5=p5?Math.abs(pp(pNow,p5.reference_price)??0):null,move15=p15?Math.abs(pp(pNow,p15.reference_price)??0):null,dir5=p5?Math.sign(pp(pNow,p5.reference_price)??0):0,dir15=p15?Math.sign(pp(pNow,p15.reference_price)??0):0,steps:number[]=[];
for(let i=1;i<hist.length;i++){const dt=new Date(hist[i].as_of).getTime()-new Date(hist[i-1].as_of).getTime();if(dt>=2*60_000&&dt<=8*60_000){const v=Math.abs(pp(hist[i].reference_price,hist[i-1].reference_price)??0);if(Number.isFinite(v))steps.push(v)}}const medianStep=med(steps.slice(-120))??1,moveMultiple=move5==null?0:move5/Math.max(medianStep,.2),atrPips=(n(state.atr15)??0)/PIP;
let severity="NORMAL",reason="Move is within its recent range.";const sharp5=move5!=null&&move5>=Math.max(5,atrPips*.65)&&moveMultiple>=3;const extreme5=move5!=null&&move5>=Math.max(9,atrPips*1.05)&&moveMultiple>=5;const sharp15=move15!=null&&move15>=Math.max(9,atrPips*1.15);const extreme15=move15!=null&&move15>=Math.max(16,atrPips*1.8);const sharpBar=body>=8&&bodyMultiple>=3&&rangeMultiple>=2;const extremeBar=body>=14&&bodyMultiple>=5&&rangeMultiple>=3;
if(extreme5||extreme15||extremeBar){severity="EXTREME";reason="Price is moving far faster and farther than its recent normal pace."}else if(sharp5||sharp15||sharpBar){severity="SHARP";reason="Price has made an unusually fast move relative to recent volatility."}else if((move5!=null&&moveMultiple>=2.2&&move5>=3)||bodyMultiple>=2.2){severity="ELEVATED";reason="Volatility is elevated, but below V2's sharp-move alert threshold."}
const chosen=extreme5||sharp5?{windowMinutes:5,movePips:move5,direction:dir5}:{windowMinutes:15,movePips:move15??body,direction:move15!=null?dir15:Math.sign(Number(latest.close)-Number(latest.open))};
return{severity,active:severity==="SHARP"||severity==="EXTREME",reason,key:`${symbol}:${severity}:${state.as_of}:${chosen.windowMinutes}`,windowMinutes:chosen.windowMinutes,movePips:chosen.movePips,direction:chosen.direction>0?"up":chosen.direction<0?"down":"flat",atrPips,moveVsNormal:moveMultiple,latest15m:{ts:latest.ts,bodyPips:body,rangePips:barRange,bodyVsMedian:bodyMultiple,rangeVsMedian:rangeMultiple,medianBodyPips:medianBody,medianRangePips:medianRange}};}
async function one(symbol:string){const [bq,sq,hq]=await Promise.all([db.from("market_bars").select("ts,open,high,low,close").eq("symbol",symbol).eq("timeframe","15m").order("ts",{ascending:false}).limit(800),db.from("market_states").select("symbol,as_of,reference_price,atr15,market_session").eq("symbol",symbol).maybeSingle(),db.from("market_state_history").select("as_of,reference_price").eq("symbol",symbol).order("as_of",{ascending:false}).limit(360)]);if(bq.error)throw Error(bq.error.message);if(sq.error)throw Error(sq.error.message);if(hq.error)throw Error(hq.error.message);const bars=(bq.data??[]).slice().reverse(),hist=(hq.data??[]).slice().reverse(),state=sq.data;if(!bars.length||!state)return{symbol,available:false};const t=new Date(state.as_of).getTime(),dayStart=Date.UTC(new Date(t).getUTCFullYear(),new Date(t).getUTCMonth(),new Date(t).getUTCDate()),weekStart=mondayStart(t),hourStart=t-60*60_000,day24=t-24*60*60_000,filter=(from:number)=>bars.filter(r=>new Date(r.ts).getTime()>=from&&new Date(r.ts).getTime()<=t),oneHour=range(filter(hourStart)),today=range(filter(dayStart)),last24h=range(filter(day24)),week=range(filter(weekStart)),current=Number(state.reference_price);const withDist=(r:any)=>r?{...r,toHighPips:pp(r.high,current),toLowPips:pp(current,r.low)}:null;return{symbol,available:true,asOf:state.as_of,current,session:state.market_session,ranges:{oneHour:withDist(oneHour),today:withDist(today),last24h:withDist(last24h),week:withDist(week)},shock:shock(symbol,state,bars,hist)};}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});if(req.method!=="GET")return J({error:"GET only"},405);try{const pairs=await Promise.all([one("EURUSD"),one("GBPUSD")]);return J({version:"V2 FX Market Context v2",generatedAt:new Date().toISOString(),researchOnly:true,pairs:Object.fromEntries(pairs.map((x:any)=>[x.symbol,x]))})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});