import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const CORE=["EURUSD","GBPUSD"],M15=15*60_000,H=[15,30,60,120,240] as const;
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Cache-Control":"no-store"};
type Row={symbol:string;as_of:string;formation_stage:number;formation_code:string|null;formation_direction:"long"|"short"|null;regime:string|null;state:any};
type Bar={ts:string;open:number;high:number;low:number;close:number};
type Ep={episode_key:string;symbol:string;direction:"long"|"short";sweep_time:string|null;status:"active"|"ended";started_at:string;ended_at:string|null;end_reason:string|null;last_seen_at:string;max_stage:number;stage3_at:string|null;stage4_at:string|null;stage5_at:string|null;stage6_at:string|null;stage7_at:string|null;stage8_at:string|null;stage3_price:number|null;stage5_price:number|null;stage6_price:number|null;stage3_atr:number|null;stage5_atr:number|null;stage6_atr:number|null;anchor_context:Record<string,unknown>;source_meta:Record<string,unknown>};
const resp=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}});
const num=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:null};const iso=(v:string|Date)=>new Date(v).toISOString();const add=(v:string,m:number)=>new Date(new Date(v).getTime()+m*60_000).toISOString();const round=(v:number|null,d=6)=>{if(v==null||!Number.isFinite(v))return null;const p=10**d;return Math.round(v*p)/p};
function sweepTime(r:Row){const v=r.state?.formation?.details?.sweepTime;return v?iso(v):null}
function eventInfo(r:Row){const s=r.state??{},dh=s.dataHealth??s.data_health??{},bs=dh.last_m15_bar??dh.lastM15Bar??null;return{observedAt:iso(r.as_of),eventAt:bs?add(bs,15):iso(r.as_of),barStart:bs?iso(bs):null,price:num(s.structurePrice??dh.structure_reference_price??dh.structureReferencePrice),source:dh.structure_source??dh.structureSource??null,sweepTime:sweepTime(r)}}
function ctx(r:Row){const s=r.state??{},d=s.diagnostics??s.details?.diagnostics??{},t=s.trends??{};return{observedAt:iso(r.as_of),stage:r.formation_stage,code:r.formation_code,direction:r.formation_direction,regime:r.regime,trends:{d1:t.d1?.label??null,h4:t.h4?.label??null,h1:t.h1?.label??null,m15:t.m15?.label??null},trendDetails:t,session:s.session??null,rangePosition:s.rangePosition??null,diagnostics:d,formation:s.formation??null}}
const epKey=(s:string,d:string,sweep:string|null,observed:string)=>`${s}:${d}:${sweep??iso(observed)}`;
function newEp(r:Row):Ep{const e=eventInfo(r),d=r.formation_direction!;return{episode_key:epKey(r.symbol,d,e.sweepTime,r.as_of),symbol:r.symbol,direction:d,sweep_time:e.sweepTime,status:"active",started_at:iso(r.as_of),ended_at:null,end_reason:null,last_seen_at:iso(r.as_of),max_stage:Math.max(3,r.formation_stage),stage3_at:null,stage4_at:null,stage5_at:null,stage6_at:null,stage7_at:null,stage8_at:null,stage3_price:null,stage5_price:null,stage6_price:null,stage3_atr:null,stage5_atr:null,stage6_atr:null,anchor_context:{},source_meta:{sweepTime:e.sweepTime,firstStructureEventAt:e.eventAt,firstBarStart:e.barStart,structureSource:e.source}}}
function mark(ep:Ep,r:Row){const st=Number(r.formation_stage),e=eventInfo(r);ep.last_seen_at=iso(r.as_of);ep.max_stage=Math.max(ep.max_stage,st);for(const a of[3,4,5,6,7,8])if(st>=a&&(ep as any)[`stage${a}_at`]==null)(ep as any)[`stage${a}_at`]=iso(r.as_of);for(const a of[3,5,6])if(st>=a){if((ep as any)[`stage${a}_price`]==null&&e.price!=null)(ep as any)[`stage${a}_price`]=e.price;if(!(`stage${a}` in ep.anchor_context))(ep.anchor_context as any)[`stage${a}`]={...ctx(r),eventAt:e.eventAt,structurePrice:e.price,barStart:e.barStart,sweepTime:e.sweepTime}}ep.source_meta={...ep.source_meta,lastStructureEventAt:e.eventAt,lastBarStart:e.barStart,structureSource:e.source}}
function close(ep:Ep,t:string,reason:string){ep.status="ended";ep.ended_at=iso(t);ep.end_reason=reason}
function earlier(a:string|null,b:string|null){if(!a)return b;if(!b)return a;return new Date(a)<=new Date(b)?a:b}
function later(a:string|null,b:string|null){if(!a)return b;if(!b)return a;return new Date(a)>=new Date(b)?a:b}
function mergeEpisode(a:Ep,b:Ep):Ep{
  const newest=new Date(a.last_seen_at)>=new Date(b.last_seen_at)?a:b;
  const oldest=new Date(a.started_at)<=new Date(b.started_at)?a:b;
  const out:Ep={...oldest,anchor_context:{...oldest.anchor_context},source_meta:{...oldest.source_meta}};
  out.started_at=earlier(a.started_at,b.started_at)!;
  out.last_seen_at=later(a.last_seen_at,b.last_seen_at)!;
  out.max_stage=Math.max(a.max_stage,b.max_stage);
  out.status=newest.status;
  out.ended_at=newest.status==="ended"?newest.ended_at:null;
  out.end_reason=newest.status==="ended"?newest.end_reason:null;
  for(const s of[3,4,5,6,7,8]){
    const ak=`stage${s}_at`,aa=(a as any)[ak] as string|null,ba=(b as any)[ak] as string|null;
    const chosen=earlier(aa,ba);(out as any)[ak]=chosen;
    if(s===3||s===5||s===6){
      const pk=`stage${s}_price`,rk=`stage${s}_atr`;
      const fromB=chosen!=null&&ba===chosen&&aa!==chosen;
      (out as any)[pk]=fromB?(b as any)[pk]:(a as any)[pk]??(b as any)[pk];
      (out as any)[rk]=fromB?(b as any)[rk]:(a as any)[rk]??(b as any)[rk];
      const ca=(a.anchor_context as any)?.[`stage${s}`],cb=(b.anchor_context as any)?.[`stage${s}`];
      if(fromB&&cb)(out.anchor_context as any)[`stage${s}`]=cb;else if(ca)(out.anchor_context as any)[`stage${s}`]=ca;else if(cb)(out.anchor_context as any)[`stage${s}`]=cb;
    }
  }
  const af=(a.source_meta as any)??{},bf=(b.source_meta as any)??{},nf=(newest.source_meta as any)??{};
  out.source_meta={...af,...bf,sweepTime:a.sweep_time??b.sweep_time,firstStructureEventAt:earlier(af.firstStructureEventAt??null,bf.firstStructureEventAt??null),firstBarStart:earlier(af.firstBarStart??null,bf.firstBarStart??null),lastStructureEventAt:later(af.lastStructureEventAt??null,bf.lastStructureEventAt??null),lastBarStart:later(af.lastBarStart??null,bf.lastBarStart??null),structureSource:nf.structureSource??af.structureSource??bf.structureSource??null};
  return out
}
function dedupeEpisodes(eps:Ep[]){const byKey=new Map<string,Ep>();for(const ep of eps){const prev=byKey.get(ep.episode_key);byKey.set(ep.episode_key,prev?mergeEpisode(prev,ep):ep)}return[...byKey.values()]}
function build(rows:Row[]){const out:Ep[]=[];let cur:Ep|null=null;for(const r of rows){const st=Number(r.formation_stage??0),d=r.formation_direction,sw=sweepTime(r);if(st>=3&&d){if(!cur)cur=newEp(r);else if(cur.direction!==d||(cur.sweep_time&&sw&&cur.sweep_time!==sw)){close(cur,r.as_of,cur.direction!==d?"direction_flip":"new_sweep");out.push(cur);cur=newEp(r)}mark(cur,r)}else if(cur){close(cur,r.as_of,"formation_reset");out.push(cur);cur=null}}if(cur)out.push(cur);return out}
const bms=(b:Bar)=>new Date(b.ts).getTime();function trs(bs:Bar[]){return bs.map((b,i)=>i===0?b.high-b.low:Math.max(b.high-b.low,Math.abs(b.high-bs[i-1].close),Math.abs(b.low-bs[i-1].close)))}function atrAt(bs:Bar[],t:string){const x=new Date(t).getTime(),ok=bs.filter(b=>bms(b)+M15<=x);if(ok.length<14)return null;const v=trs(ok).slice(-14);return v.reduce((a,b)=>a+b,0)/v.length}function closeAt(bs:Bar[],t:string,m:number){const a=new Date(t).getTime(),target=a+m*60_000,x=bs.filter(b=>bms(b)>=a&&bms(b)+M15<=target);return x.at(-1)?.close??null}function excursion(bs:Bar[],t:string,m:number,p:number,d:"long"|"short",atr:number|null){if(!atr||atr<=0)return{mfe:null,mae:null};const a=new Date(t).getTime(),end=a+m*60_000,x=bs.filter(b=>bms(b)>=a&&bms(b)+M15<=end);if(!x.length)return{mfe:null,mae:null};const hi=Math.max(...x.map(z=>z.high)),lo=Math.min(...x.map(z=>z.low));return d==="long"?{mfe:(hi-p)/atr,mae:(p-lo)/atr}:{mfe:(p-lo)/atr,mae:(hi-p)/atr}}
function anchor(ep:Ep,s:3|5|6){const c=(ep.anchor_context as any)?.[`stage${s}`],o=(ep as any)[`stage${s}_at`],p=num((ep as any)[`stage${s}_price`]);return c&&o&&p!=null?{observedAt:o,eventAt:c.eventAt??o,price:p}:null}
function outcome(ep:Ep,s:3|5|6,bs:Bar[]){const a=anchor(ep,s);if(!a)return null;const latest=bs.length?bms(bs.at(-1)!)+M15:0,am=new Date(a.eventAt).getTime(),atr=atrAt(bs,a.eventAt),f=ep.direction==="long"?1:-1,r:Record<number,number|null>={};let complete=0;for(const h of H){if(latest<am+h*60_000){r[h]=null;continue}const c=closeAt(bs,a.eventAt,h);r[h]=c==null?null:(c/a.price-1)*10000;if(r[h]!=null)complete=h}const x1=complete>=60?excursion(bs,a.eventAt,60,a.price,ep.direction,atr):{mfe:null,mae:null},x4=complete>=240?excursion(bs,a.eventAt,240,a.price,ep.direction,atr):{mfe:null,mae:null};return{episode_key:ep.episode_key,anchor_stage:s,anchor_at:a.eventAt,direction:ep.direction,anchor_price:a.price,atr_at_anchor:round(atr,8),ret_15m_bps:round(r[15]),ret_30m_bps:round(r[30]),ret_1h_bps:round(r[60]),ret_2h_bps:round(r[120]),ret_4h_bps:round(r[240]),signed_ret_15m_bps:round(r[15]==null?null:r[15]!*f),signed_ret_30m_bps:round(r[30]==null?null:r[30]!*f),signed_ret_1h_bps:round(r[60]==null?null:r[60]!*f),signed_ret_2h_bps:round(r[120]==null?null:r[120]!*f),signed_ret_4h_bps:round(r[240]==null?null:r[240]!*f),mfe_1h_atr:round(x1.mfe),mae_1h_atr:round(x1.mae),mfe_4h_atr:round(x4.mfe),mae_4h_atr:round(x4.mae),complete_through_minutes:complete,updated_at:new Date().toISOString()}}
const evidence=(n:number)=>n<10?"insufficient":n<30?"early":n<100?"building":"research-ready";
async function cronOk(req:Request){const k=req.headers.get("x-v2-cron-key")??"";if(!k)return false;const q=await db.from("v2_runtime_secrets").select("secret").eq("name","cron").maybeSingle();if(q.error||!q.data?.secret)return false;const a=new TextEncoder().encode(k),b=new TextEncoder().encode(String(q.data.secret));if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]!^b[i]!;return d===0}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(!["GET","POST"].includes(req.method))return resp({error:"GET or POST only"},405);try{if(!(await cronOk(req)))return resp({error:"unauthorized"},401);const result:any[]=[];for(const symbol of CORE){const[hq,bq]=await Promise.all([db.from("market_state_history").select("symbol,as_of,formation_stage,formation_code,formation_direction,regime,state").eq("symbol",symbol).order("as_of",{ascending:false}).limit(5000),db.from("market_bars").select("ts,open,high,low,close").eq("symbol",symbol).eq("timeframe","15m").order("ts",{ascending:false}).limit(10000)]);if(hq.error)throw new Error(`${symbol} history: ${hq.error.message}`);if(bq.error)throw new Error(`${symbol} bars: ${bq.error.message}`);const rows=[...((hq.data??[]) as Row[])].reverse(),bs=[...((bq.data??[]) as Bar[])].reverse(),eps=dedupeEpisodes(build(rows));if(eps.length){const q=await db.from("formation_episodes").upsert(eps.map(e=>({...e,updated_at:new Date().toISOString()})),{onConflict:"episode_key"});if(q.error)throw new Error(`${symbol} episode upsert: ${q.error.message}`)}const outs=eps.flatMap(e=>([3,5,6] as const).map(s=>outcome(e,s,bs)).filter(Boolean));if(outs.length){const q=await db.from("episode_outcomes").upsert(outs,{onConflict:"episode_key,anchor_stage"});if(q.error)throw new Error(`${symbol} outcome upsert: ${q.error.message}`)}const active=[...eps].reverse().find(e=>e.status==="active")??null,complete6=outs.filter((x:any)=>x.anchor_stage===6&&x.complete_through_minutes>=60).length;result.push({symbol,historyRows:rows.length,episodes:eps.length,activeEpisode:active?.episode_key??null,outcomes:outs.length,completedStage6_1h:complete6,evidence:evidence(complete6)})}return resp({version:"V2 episode engine v1.1.2",generatedAt:new Date().toISOString(),result})}catch(e){console.error(e);return resp({error:String(e)},500)}});