import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SB,KEY,{auth:{persistSession:false}}),ROOT="https://jetta.dukascopy.com/v1",CODE="XAU-USD",SYMBOL="XAUUSD",SOURCE="Dukascopy Jetta XAU/USD";
const H={"Access-Control-Allow-Origin":"*","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
type Bar={ts:string;open:number;high:number;low:number;close:number;volume:number|null};
function scale(m:number){const[c,e="0"]=String(m).toLowerCase().split("e"),d=c.split(".")[1]?.length??0;return Math.max(0,d-Number(e))}
function decode(j:any):Bar[]{if(!j||!Array.isArray(j.times)||!Number.isFinite(j.timestamp)||!Number.isFinite(j.multiplier))return[];const n=j.times.length,cols=[j.opens,j.highs,j.lows,j.closes,j.volumes];if(cols.some((c:any)=>!Array.isArray(c)||c.length!==n))return[];const m=Number(j.multiplier),sc=scale(m),fmt=(u:number)=>Number((u*m).toFixed(sc));let ts=Number(j.timestamp),o=Math.round(Number(j.open)/m),h=Math.round(Number(j.high)/m),l=Math.round(Number(j.low)/m),c=Math.round(Number(j.close)/m);const out:Bar[]=[];for(let i=0;i<n;i++){ts+=Number(j.times[i])*Number(j.shift);o+=Number(j.opens[i]);h+=Number(j.highs[i]);l+=Number(j.lows[i]);c+=Number(j.closes[i]);const x={ts:new Date(ts).toISOString(),open:fmt(o),high:fmt(h),low:fmt(l),close:fmt(c),volume:Number.isFinite(Number(j.volumes[i]))?Number(j.volumes[i]):null};if(x.open>0&&x.high>=x.low&&x.low>0)out.push(x)}return out}
async function active(side:string){const n=new Date(),today=Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate()),u=`${ROOT}/candles/minute/${CODE}/${side}?from=${today}`,r=await fetch(u,{headers:{"Accept":"application/json","User-Agent":"V2GoldResearch/1.0"},signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error(`Dukascopy ${side} ${r.status}`);return decode(await r.json())}
function aggregate(b:Bar[],mins:number){const ms=mins*60000,m=new Map<number,Bar[]>();for(const x of b){const k=Math.floor(+new Date(x.ts)/ms)*ms,g=m.get(k)??[];g.push(x);m.set(k,g)}return[...m.entries()].sort((a,b)=>a[0]-b[0]).map(([t,g])=>({ts:new Date(t).toISOString(),open:g[0].open,high:Math.max(...g.map(x=>x.high)),low:Math.min(...g.map(x=>x.low)),close:g.at(-1)!.close,volume:g.some(x=>x.volume!=null)?g.reduce((s,x)=>s+(x.volume??0),0):null}))}
const completed=(b:Bar[],mins:number)=>b.filter(x=>+new Date(x.ts)+mins*60000<=Date.now());
async function persist(tf:string,b:Bar[]){const rows=b.map(x=>({symbol:SYMBOL,timeframe:tf,ts:x.ts,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume,source:SOURCE,is_proxy:false}));if(rows.length){const q=await db.from("market_bars").upsert(rows,{onConflict:"symbol,timeframe,ts,source"});if(q.error)throw Error(`${tf}: ${q.error.message}`)}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="GET")return J({error:"GET only"},405);try{const[bid1,ask1]=await Promise.all([active("BID"),active("ASK")]);if(!bid1.length)throw Error("No active XAU BID minutes returned");const m15=completed(aggregate(bid1,15),15),h1=completed(aggregate(bid1,60),60),h4=completed(aggregate(bid1,240),240);await Promise.all([persist("15m",m15),persist("1h",h1),persist("4h",h4)]);const bid=bid1.at(-1)!,askSame=ask1.find(x=>x.ts===bid.ts)??null;return J({ok:true,version:"xau-minute-sync-v1",feed:{provider:"Dukascopy",instrument:"XAU/USD",latestMinute:bid.ts,bid:bid.close,ask:askSame?.close??null,spread:askSame?Math.max(0,askSame.close-bid.close):null,askAligned:!!askSame,todayMinutes:bid1.length,completed:{m15:m15.length,h1:h1.length,h4:h4.length}},boundary:"This function only syncs bars. It never writes market_states; xau-state-engine is the sole canonical XAU state owner."})}catch(e){console.error(e);return J({error:e instanceof Error?e.message:String(e)},500)}});