import {spawn,execFileSync} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function chromePath(){for(const name of ['google-chrome','google-chrome-stable','chromium','chromium-browser']){try{return execFileSync('which',[name],{encoding:'utf8'}).trim()}catch{}}throw new Error('Chrome/Chromium not found on runner')}
async function waitJson(url,timeout=10000){const end=Date.now()+timeout;while(Date.now()<end){try{const r=await fetch(url);if(r.ok)return await r.json()}catch{}await sleep(150)}throw new Error(`Timed out waiting for ${url}`)}
async function pageTarget(port,timeout=12000){const end=Date.now()+timeout;while(Date.now()<end){try{const r=await fetch(`http://127.0.0.1:${port}/json/list`);if(r.ok){const xs=await r.json();const p=xs.find(x=>x.type==='page'&&x.webSocketDebuggerUrl);if(p)return p}}catch{}await sleep(150)}throw new Error('Timed out waiting for Chrome page target')}
async function removeProfile(path){for(let i=0;i<6;i++){try{rmSync(path,{recursive:true,force:true,maxRetries:3,retryDelay:100});return}catch(e){if(i===5)console.warn('profile cleanup skipped',e?.code||e);else await sleep(200)}}}
async function startChrome(){const bin=chromePath(),failures=[];for(let attempt=0;attempt<3;attempt++){const port=9222+attempt,profile=mkdtempSync(join(tmpdir(),`v2-chrome-${attempt}-`));const chrome=spawn(bin,['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-software-rasterizer',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'about:blank'],{stdio:'ignore'});try{await waitJson(`http://127.0.0.1:${port}/json/version`,9000);return{chrome,profile,port}}catch(e){failures.push(String(e));try{chrome.kill('SIGKILL')}catch{}await sleep(350);await removeProfile(profile)}}throw new Error(`Chrome failed to start after 3 attempts: ${failures.join(' | ')}`)}
const root=process.cwd(),smokeUrl=process.env.SMOKE_URL||'http://127.0.0.1:4173/web/index.html',local=!process.env.SMOKE_URL,server=local?spawn('python3',['-m','http.server','4173','--bind','127.0.0.1','--directory',root],{stdio:'ignore'}):null;
let ws,browser;
try{
  browser=await startChrome();const target=await pageTarget(browser.port);ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true})});let seq=0;const waiting=new Map(),exceptions=[];
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&waiting.has(m.id)){const{resolve,reject}=waiting.get(m.id);waiting.delete(m.id);m.error?reject(new Error(m.error.message)):resolve(m.result);return}if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params?.exceptionDetails?.exception?.description||m.params?.exceptionDetails?.text||'Uncaught exception')});
  const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;waiting.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))}),evalJs=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text||'Runtime evaluation failed');return r.result?.value};
  await call('Page.enable');await call('Runtime.enable');await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:true,screenWidth:390,screenHeight:844});await call('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await call('Page.navigate',{url:smokeUrl});
  const end=Date.now()+30000;while(Date.now()<end){if(await evalJs("document.readyState==='complete' && typeof setView==='function' && document.documentElement.classList.contains('v28Mobile') && !!document.querySelector('#mobilePortfolioChip')"))break;await sleep(150)}if(!await evalJs("document.readyState==='complete' && typeof setView==='function' && document.documentElement.classList.contains('v28Mobile') && !!document.querySelector('#mobilePortfolioChip')"))throw new Error(`Mobile UX did not initialize at ${smokeUrl}`);

  const pairDeadline=Date.now()+20000;let pairs=0;while(Date.now()<pairDeadline){pairs=await evalJs("document.querySelectorAll('[data-pair]').length");if(pairs===2)break;await sleep(250)}if(pairs!==2)throw new Error(`Expected exactly 2 FX pair buttons, found ${pairs}`);const labels=await evalJs("[...document.querySelectorAll('[data-pair]')].map(x=>x.dataset.pair).join(',')");if(labels!=='EURUSD,GBPUSD')throw new Error(`Unexpected pair list: ${labels}`);

  const accountDeadline=Date.now()+20000;let accountReady=false;while(Date.now()<accountDeadline){accountReady=await evalJs("!!window.v2PaperAccount?.account && !!document.querySelector('#paperAccount .portfolioBalance') && document.querySelector('#paperAccount')?.parentElement?.classList.contains('mobileAccountSlot')");if(accountReady)break;await sleep(250)}if(!accountReady)throw new Error('Paper account did not move into the mobile account sheet');
  const chip=await evalJs(`(()=>{const c=document.querySelector('#mobilePortfolioChip');return{balance:c?.querySelector('strong')?.textContent||'',growth:c?.querySelector('span')?.textContent||'',inTop:!!c?.closest('.topbar'),accountInWrap:!!document.querySelector('.wrap #paperAccount')}})()`);
  if(!/^\$\d+\.\d{2}$/.test(chip.balance)||!/[+-]?\d+(?:\.\d+)?%/.test(chip.growth)||!chip.inTop||chip.accountInWrap)throw new Error(`Mobile account chip invalid: ${JSON.stringify(chip)}`);
  const opened=await evalJs(`(()=>{const c=document.querySelector('#mobilePortfolioChip');c?.click();const l=document.querySelector('#mobileAccountLayer');return !!l&&!l.hidden&&c?.getAttribute('aria-expanded')==='true'})()`);if(!opened)throw new Error('Paper account sheet did not open from top balance chip');await sleep(150);const sheetBalance=await evalJs("document.querySelector('.mobileAccountSheet #paperAccount .portfolioBalance b')?.textContent||''");if(sheetBalance!==chip.balance)throw new Error(`Account sheet balance ${sheetBalance} did not match top chip ${chip.balance}`);await evalJs("document.querySelector('.mobileSheetClose')?.click()");

  const expected=[['chartView','chartView'],['tradesView','tradesView'],['evidenceView','evidenceView'],['dataView','dataView'],['overview','overview']];for(const[button,view]of expected){const ok=await evalJs(`(()=>{const bs=[...document.querySelectorAll('[data-view="${button}"]')];const b=bs.find(x=>x.offsetParent!==null)||bs[0];if(!b)return false;b.click();return true})()`);if(!ok)throw new Error(`Missing navigation button ${button}`);await sleep(400);const active=await evalJs("document.querySelector('.view.active')?.id||''");if(active!==view)throw new Error(`Click ${button} left active view as ${active||'none'}`)}

  await evalJs("document.querySelector('[data-view=\"tradesView\"]')?.click()");await sleep(500);
  const journalDeadline=Date.now()+20000;let journalReady=false;while(Date.now()<journalDeadline){journalReady=await evalJs("document.querySelectorAll('#paperHistory .tradeRow').length>0 && document.querySelectorAll('#paperHistory .pipStrip').length>0 && document.querySelectorAll('#paperHistory [data-v27-exec]').length>0");if(journalReady)break;await sleep(250)}if(!journalReady)throw new Error('Paper journal, pips/RR or advanced price checks did not render');
  async function checkPairJournal(symbol){const clicked=await evalJs(`(()=>{const b=document.querySelector('[data-pair="${symbol}"]');if(!b)return false;b.click();return true})()`);if(!clicked)throw new Error(`Could not select ${symbol}`);await sleep(450);const j=await evalJs(`(()=>{const visible=[...document.querySelectorAll('#paperHistory .tradeRow')].filter(x=>!x.hidden);return{title:document.querySelector('#paperHistory')?.closest('.section')?.querySelector('.sectionHead h2')?.textContent||'',symbols:visible.map(x=>x.querySelector('.tradeRowHead b')?.textContent.trim().split(/\\s+/)[0]),execClosed:visible.every(x=>{const d=x.querySelector('[data-v27-exec]');return d?.tagName==='DETAILS'&&!d.open}),mixed:[...document.querySelectorAll('#paperHistory .tradeRow')].filter(x=>!x.hidden).some(x=>x.querySelector('.tradeRowHead b')?.textContent.trim().split(/\\s+/)[0]!== '${symbol}')}})()`);if(j.title!==`${symbol} journal`||j.mixed||j.symbols.some(x=>x!==symbol)||!j.execClosed)throw new Error(`${symbol} journal filter/advanced disclosure failed: ${JSON.stringify(j)}`)}
  await checkPairJournal('EURUSD');await checkPairJournal('GBPUSD');

  const advanced=await evalJs(`(()=>{const a=document.querySelector('#paperAccount [data-v27-account]');return{tag:a?.tagName||'',open:a?.open??null,text:a?.querySelector('summary')?.textContent?.trim()||''}})()`);if(advanced.tag!=='DETAILS'||advanced.open!==false||!advanced.text.includes('Advanced account checks'))throw new Error(`Account audit is not optional/collapsed: ${JSON.stringify(advanced)}`);

  await evalJs("document.querySelector('[data-view=\"dataView\"]')?.click()");const rangeDeadline=Date.now()+20000;let rangeReady=false;while(Date.now()<rangeDeadline){rangeReady=await evalJs("!!document.querySelector('#v29MarketRange') && document.querySelector('#v29MarketRange')?.textContent.includes('Recent highs & lows')");if(rangeReady)break;await sleep(250)}if(!rangeReady)throw new Error('Recent high/low market context did not render');await evalJs("document.querySelector('#v29MarketRange').open=true");await sleep(100);const rangeText=await evalJs("document.querySelector('#v29MarketRange')?.textContent||''");if(!rangeText.includes('Last hour')||!rangeText.includes('Today')||!rangeText.includes('This week'))throw new Error('High/low panel missing 1h/day/week context');
  const dataAdvanced=await evalJs(`(()=>{const d=document.querySelector('#v27ExecutionQuality');return{tag:d?.tagName||'',open:d?.open??null,summary:d?.querySelector('summary')?.textContent||''}})()`);if(dataAdvanced.tag!=='DETAILS'||dataAdvanced.open!==false||!dataAdvanced.summary.includes('Extra price data'))throw new Error(`Execution data is not collapsed/optional: ${JSON.stringify(dataAdvanced)}`);

  const mobileChecks=await evalJs(`(()=>{const nav=[...document.querySelectorAll('.bottom .navBtn')].map(x=>x.getBoundingClientRect().height);const controls=[...document.querySelectorAll('.focusAction,.pairBtn,.iconBtn,.mobilePortfolioChip,.mobileSheetClose')].filter(x=>x.offsetParent!==null).map(x=>x.getBoundingClientRect().height);const body=parseFloat(getComputedStyle(document.body).fontSize);const intro=document.querySelector('.intro h1')?.textContent||'';const status=document.querySelector('.focusStatus')?.textContent||'';return{navMin:Math.min(...nav),controlMin:Math.min(...controls),body,intro,status,overflow:document.documentElement.scrollWidth-window.innerWidth,bottomLabels:[...document.querySelectorAll('.bottom .navBtn span:last-child')].map(x=>x.textContent).join(',')}})()`);
  if(mobileChecks.navMin<48||mobileChecks.controlMin<48)throw new Error(`Touch target below 48px: nav ${mobileChecks.navMin}, control ${mobileChecks.controlMin}`);if(mobileChecks.body<16)throw new Error(`Mobile body font too small: ${mobileChecks.body}px`);if(mobileChecks.overflow>1)throw new Error(`Mobile horizontal overflow: ${mobileChecks.overflow}px`);if(mobileChecks.intro!=='What matters right now')throw new Error(`Plain-language intro missing: ${mobileChecks.intro}`);if(mobileChecks.bottomLabels!=='Home,Chart,Trades,Research,Data')throw new Error(`Mobile nav copy unexpected: ${mobileChecks.bottomLabels}`);if(!mobileChecks.status)throw new Error('Mobile Focus status missing');
  if(exceptions.length)throw new Error(`Uncaught browser exception: ${exceptions.join(' | ')}`);console.log(`mobile browser smoke passed at ${smokeUrl}: compact top balance, account sheet, pair-specific journal, collapsed advanced price checks, recent highs/lows, 48px targets and no overflow`)
}finally{try{ws?.close()}catch{}try{browser?.chrome.kill('SIGKILL')}catch{}server?.kill('SIGKILL');await sleep(300);if(browser?.profile)await removeProfile(browser.profile)}