from __future__ import annotations

"""Benchmark live detector warnings against independent public V2 proxy entries.

A proxy entry is generated by scripts/public_data_v2_proxy.py using its frozen
sweep/BOS/fresh-POI/midpoint-entry rules. We then ask whether the live formation
state machine had already emitted same-direction development states before that
entry time. No future bar is used by the live-state replay.
"""

import argparse, json
from pathlib import Path
import numpy as np
import pandas as pd
from public_data_v2_proxy import ProxyConfig, detect_symbol, load_market


def evaluate(states: pd.DataFrame, trades: pd.DataFrame, lookback_bars: int = 32):
    rows=[]
    states=states.copy();states["time"]=pd.to_datetime(states.time,utc=True)
    for t in trades.itertuples(index=False):
        et=pd.Timestamp(t.entry_time)
        prior=states[(states.time<et)&(states.time>=et-pd.Timedelta(minutes=15*lookback_bars))&(states.direction==t.direction)]
        rec={"setup_id":t.setup_id,"symbol":t.symbol,"direction":t.direction,"entry_time":et}
        for threshold in [3,4,5,6,7]:
            hit=prior[(prior.stage>=threshold)&(prior.stage<8)]
            rec[f"warn_stage{threshold}"]=not hit.empty
            rec[f"lead_stage{threshold}_min"]=(et-hit.time.iloc[0]).total_seconds()/60 if not hit.empty else np.nan
        rows.append(rec)
    return pd.DataFrame(rows)


def summarize(df: pd.DataFrame):
    out={"proxy_entries":int(len(df))}
    for threshold in [3,4,5,6,7]:
        col=f"warn_stage{threshold}";lead=f"lead_stage{threshold}_min"
        out[f"stage{threshold}_recall"]=float(df[col].mean()) if len(df) else None
        vals=df.loc[df[col],lead]
        out[f"stage{threshold}_median_lead_minutes"]=float(vals.median()) if len(vals) else None
    return out


def main():
    ap=argparse.ArgumentParser();ap.add_argument("--data-dir",type=Path,required=True);ap.add_argument("--states",type=Path,required=True);ap.add_argument("--out",type=Path,required=True);ap.add_argument("--start",default="2023-01-01");args=ap.parse_args();args.out.mkdir(parents=True,exist_ok=True)
    states=pd.read_csv(args.states);states["time"]=pd.to_datetime(states.time,utc=True)
    all_rows=[];summary={}
    for symbol in ["EURUSD","GBPUSD"]:
        m15=load_market(args.data_dir/f"{symbol}-15m.feather",symbol);m15=m15[m15.date>=pd.Timestamp(args.start,tz="UTC")].reset_index(drop=True)
        proxy=detect_symbol(m15,None,symbol,ProxyConfig())
        s=states[states.symbol==symbol].copy();res=evaluate(s,proxy);all_rows.append(res);summary[symbol]=summarize(res)
    out=pd.concat(all_rows,ignore_index=True);out.to_csv(args.out/"proxy_entry_recall.csv",index=False)
    pooled=summarize(out);result={"version":"v0.6 independent proxy-entry recall","symbols":summary,"pooled":pooled,"interpretation":"Recall answers whether the live detector warned before a separately generated proxy entry. It does not validate trade profitability or broker execution."};(args.out/"proxy_entry_validation.json").write_text(json.dumps(result,indent=2),encoding="utf-8");print(json.dumps(result,indent=2))

if __name__=="__main__":main()
