import fs from 'node:fs';
import vm from 'node:vm';

const html=fs.readFileSync('web/index.html','utf8');
const css=fs.readFileSync('web/v11.css','utf8');
const css13=fs.readFileSync('web/v13.css','utf8');
const css15=fs.readFileSync('web/v15.css','utf8');
const js=fs.readFileSync('web/v12.js','utf8');
const poi=fs.readFileSync('web/poi-watch.js','utf8');
const paper=fs.readFileSync('web/paper-trades.js','utf8');
const focus=fs.readFileSync('web/v15-focus.js','utf8');
const requiredHtml=['Version 1.5','Focus mode','Research details','Paper trades','Research Trade Chart','POI lifecycle','Partial mitigation','Data trust','v11.css','v13.css','v15.css','v12.js','poi-watch.js','paper-trades.js','v15-focus.js','lightweight-charts@5.2.0','aria-label="Primary navigation"','role="status"'];
for(const m of requiredHtml)if(!html.includes(m))throw new Error(`Missing v1.5 HTML marker: ${m}`);
const requiredCss=['min-height:48px',':focus-visible','prefers-reduced-motion','@media(min-width:720px)','@media(min-width:1000px)','.bottom','.rail'];
for(const m of requiredCss)if(!css.includes(m))throw new Error(`Missing base CSS/accessibility marker: ${m}`);
for(const m of ['repeat(5,1fr)','.paperLevels','.researchChart','.tradeList'])if(!css13.includes(m))throw new Error(`Missing paper-trade CSS marker: ${m}`);
for(const m of ['.focusHero','.researchDisclosure','@media(max-width:560px)'])if(!css15.includes(m))throw new Error(`Missing v1.5 focus CSS marker: ${m}`);
const requiredJs=['lab-insights','campaign','sweeps','independentCampaigns','researchPriority','s3.tradingview.com'];
for(const m of requiredJs)if(!js.includes(m))throw new Error(`Missing core intelligence marker: ${m}`);
const requiredPoi=['POI Watch','Waiting for BOS','BOS confirmed','Fresh POI found','Approaching POI','POI reached','poi_low','poi_high','distance_to_poi_atr','v===null||v===undefined'];
for(const m of requiredPoi)if(!poi.includes(m))throw new Error(`Missing POI Watch marker: ${m}`);
const requiredPaper=['paper-trade-engine','Paper trade open','entry_price','stop_price','target_price','createPriceLine','createSeriesMarkers','CandlestickSeries','Research simulation','2.5R','MFE','MAE','extended_wait','long_tail_wait','outside_studied_tail','partially_mitigated','target_delivered_before_entry','former eight-bar cutoff'];
for(const m of requiredPaper)if(!paper.includes(m))throw new Error(`Missing adaptive paper-trade marker: ${m}`);
for(const m of ['WAIT FOR POI','What must happen next','historical lifecycle base rate','Paper plan waiting for POI'])if(!focus.includes(m))throw new Error(`Missing focus-mode behavior: ${m}`);
new vm.Script(js,{filename:'web/v12.js'});
new vm.Script(poi,{filename:'web/poi-watch.js'});
new vm.Script(paper,{filename:'web/paper-trades.js'});
new vm.Script(focus,{filename:'web/v15-focus.js'});
if((css.match(/min-(?:width|height):48px/g)||[]).length<2)throw new Error('Expected explicit 48px interaction target rules');
if(!html.includes('Open chart')||!html.includes('Research evidence'))throw new Error('Primary investigation actions missing');
console.log('v1.5 frontend validation passed: focus-first disclosure UX preserves adaptive POI lifecycle, paper trades, chart overlays, accessibility and research detail');
