import fs from 'node:fs';
import vm from 'node:vm';

const html=fs.readFileSync('web/index.html','utf8');
const bus=fs.readFileSync('web/v2-data-bus.js','utf8');
const css=fs.readFileSync('web/v11.css','utf8');
const css13=fs.readFileSync('web/v13.css','utf8');
const css15=fs.readFileSync('web/v15.css','utf8');
const css22=fs.readFileSync('web/v22.css','utf8');
const js=fs.readFileSync('web/v12.js','utf8');
const poi=fs.readFileSync('web/poi-watch.js','utf8');
const paper=fs.readFileSync('web/paper-trades.js','utf8');
const focus=fs.readFileSync('web/v15-focus.js','utf8');
const brief=fs.readFileSync('web/v22-brief.js','utf8');
const loader=fs.readFileSync('web/v17-shadow.js','utf8');
const chat=fs.readFileSync('web/v23-chat.js','utf8');
if(!/Version 2\.5/.test(html))throw new Error('Missing current V2.5 version marker');
const requiredHtml=['Research details','Paper trades','Research Trade Chart','POI lifecycle','Partial mitigation','Data trust','/web/v11.css','/web/v13.css','/web/v15.css','/web/v2-data-bus.js','/web/v25-unified.js','/web/v12.js','/web/poi-watch.js','/web/paper-trades.js','/web/v15-focus.js','/web/v17-shadow.js','lightweight-charts@5.2.0','aria-label="Primary navigation"','role="status"','__V2_PRIMARY_V25=true'];
for(const m of requiredHtml)if(!html.includes(m))throw new Error(`Missing current HTML marker: ${m}`);
const requiredCss=['min-height:48px',':focus-visible','prefers-reduced-motion','@media(min-width:720px)','@media(min-width:1000px)','.bottom','.rail'];
for(const m of requiredCss)if(!css.includes(m))throw new Error(`Missing base CSS/accessibility marker: ${m}`);
for(const m of ['repeat(5,1fr)','.paperLevels','.researchChart','.tradeList'])if(!css13.includes(m))throw new Error(`Missing paper-trade CSS marker: ${m}`);
for(const m of ['.focusHero','.researchDisclosure','@media(max-width:560px)'])if(!css15.includes(m))throw new Error(`Missing v1.5 focus CSS marker: ${m}`);
const requiredJs=['lab-insights','campaign','sweeps','independentCampaigns','researchPriority','s3.tradingview.com'];
for(const m of requiredJs)if(!js.includes(m))throw new Error(`Missing core intelligence marker: ${m}`);
const requiredPoi=['POI Watch','Waiting for BOS','BOS confirmed','Fresh POI found','Approaching POI','POI reached','poi_low','poi_high','distance_to_poi_atr','v===null||v===undefined'];
for(const m of requiredPoi)if(!poi.includes(m))throw new Error(`Missing POI Watch marker: ${m}`);
const requiredPaper=['paper-trade-engine','Paper trade open','entry_price','stop_price','target_price','createPriceLine','createSeriesMarkers','CandlestickSeries','Research simulation','2.5R','MFE','MAE','extended_wait','long_tail_wait','outside_studied_tail','partially_mitigated','target_delivered_before_entry','former eight-bar cutoff'];
for(const m of requiredPaper)if(!paper.includes(m))throw new Error(`Missing adaptive paper-trade marker: ${m}`);
for(const m of ['WAIT FOR POI','What must happen next','historical lifecycle base rate','Paper plan waiting for POI'])if(!focus.includes(m))throw new Error(`Missing focus-mode behavior: ${m}`);
for(const m of ['Trade now','Setup now','Event risk','Research details','R now','What V2 needs next','trader-brief'])if(!brief.includes(m))throw new Error(`Missing V2.2 plain-language marker: ${m}`);
for(const m of ['font-size:16px','font-size:15.5px','.v22RTrack','.v22Details','.v22Active #v21DecisionBoard'])if(!css22.includes(m))throw new Error(`Missing V2.2 readability/disclosure marker: ${m}`);
for(const m of ['loadV22','v22.css','v22-brief.js','asset('])if(!loader.includes(m))throw new Error(`Missing immutable V2.2 asset-loader marker: ${m}`);
const unified=fs.readFileSync('web/v25-unified.js','utf8');
if(!unified.includes('ASSET_BASE')||!unified.includes('v25-sim.json'))throw new Error('V2.5 simulation asset must resolve relative to its deployed script');
if(!bus.includes('__V2DataBus')||!bus.includes('bars='))throw new Error('Paper research consumers must share a request bus');
if(!paper.includes('PRIMARY')||!paper.includes('__V2DataBus'))throw new Error('Paper detail view must load lazily and share its snapshot');
if(!focus.includes('PRIMARY')||!focus.includes('__V2DataBus'))throw new Error('Legacy focus must not duplicate primary paper polling');
if(!loader.includes('PRIMARY')||!chat.includes("['evidenceView','dataView']"))throw new Error('Primary research modules must load on demand');
const vercel=JSON.parse(fs.readFileSync('vercel.json','utf8'));
if(vercel.rewrites?.[0]?.destination!=='/web')throw new Error('Root must route to the repository web entrypoint');
if(!vercel.headers?.some(x=>x.source==='/'))throw new Error('Root cache policy is missing');
new vm.Script(js,{filename:'web/v12.js'});
new vm.Script(poi,{filename:'web/poi-watch.js'});
new vm.Script(paper,{filename:'web/paper-trades.js'});
new vm.Script(focus,{filename:'web/v15-focus.js'});
new vm.Script(brief,{filename:'web/v22-brief.js'});
if((css.match(/min-(?:width|height):48px/g)||[]).length<2)throw new Error('Expected explicit 48px interaction target rules');
if(!html.includes('Open chart')||!html.includes('Research evidence'))throw new Error('Primary investigation actions missing');
console.log('frontend validation passed: V2.2 prioritizes trade status, plain-language setup, event risk and progressive research disclosure');
