import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync('web/index.html','utf8');
const js=fs.readFileSync('web/v17-shadow.js','utf8');
const css=fs.readFileSync('web/v17.css','utf8');
const edge=fs.readFileSync('supabase/functions/shadow-arena/index.ts','utf8');
const migration=fs.readFileSync('supabase/migrations/20260810225500_v17_shadow_arena.sql','utf8');
for(const m of ['Version 1.7 · Shadow Arena','/v17.css','/v17-shadow.js','evidenceView'])if(!html.includes(m))throw new Error(`missing v1.7 HTML marker: ${m}`);
for(const m of ['Prospective Shadow Arena','probabilities stay hidden','Base Brier','prospective scoring','incremental value beyond StateTwin','ABSTAIN'])if(!js.toLowerCase().includes(m.toLowerCase()))throw new Error(`missing Shadow Arena UI behavior: ${m}`);
for(const m of ['.shadowArenaResearch','.shadowGrid','.shadowModels','@media(max-width:560px)'])if(!css.includes(m))throw new Error(`missing Shadow Arena CSS: ${m}`);
for(const m of ['LANDMARKS','resolvePending','observedBeforeOutcome','horizon_elapsed','walkforward-base-v1','state-twin-v16','granite-ttm-r2-v17'])if(!edge.includes(m))throw new Error(`missing Shadow Arena engine marker: ${m}`);
for(const m of ['shadow_forecasts','shadow_model_registry','model_spec_hash','enable row level security','service_role','PROMOTE_TTM_TO_SHADOW'])if(!migration.includes(m))throw new Error(`missing Shadow Arena migration marker: ${m}`);
new vm.Script(js,{filename:'web/v17-shadow.js'});
console.log('v1.7 Shadow Arena validation passed: immutable prospective capture, automatic resolution, abstention UI and passing TTM shadow boundary present');
