import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync('web/index.html','utf8');
const js=fs.readFileSync('web/v17-shadow.js','utf8');
const css=fs.readFileSync('web/v17.css','utf8');
const edge=fs.readFileSync('supabase/functions/shadow-arena/index.ts','utf8');
const gateway=fs.readFileSync('supabase/functions/shadow-score-gateway/index.ts','utf8');
const dual=fs.existsSync('scripts/v18_shadow_observer_scorer.py');
const scorer=fs.readFileSync(dual?'scripts/v18_shadow_observer_scorer.py':'scripts/v17_shadow_ttm_scorer.py','utf8');
const calibrator=fs.readFileSync('reports/v17/V17_TTM_LIVE_CALIBRATOR.json','utf8');
const workflow=fs.readFileSync('.github/workflows/v17-shadow-scorer.yml','utf8');
const migration=fs.readFileSync('supabase/migrations/20260810225500_v17_shadow_arena.sql','utf8');
for(const m of ['Version 1.7 · Shadow Arena','/v17.css','/v17-shadow.js','evidenceView'])if(!html.includes(m))throw new Error(`missing v1.7 HTML marker: ${m}`);
for(const m of ['Prospective Shadow Arena','probabilities stay hidden','Base Brier','prospective scoring','incremental value beyond StateTwin','ABSTAIN'])if(!js.toLowerCase().includes(m.toLowerCase()))throw new Error(`missing Shadow Arena UI behavior: ${m}`);
for(const m of ['.shadowArenaResearch','.shadowGrid','.shadowModels','@media(max-width:560px)'])if(!css.includes(m))throw new Error(`missing Shadow Arena CSS: ${m}`);
for(const m of ['LANDMARKS','resolvePending','observedBeforeOutcome','bosReference','horizon_elapsed','walkforward-base-v1','state-twin-v16','granite-ttm-r2-v17'])if(!edge.includes(m))throw new Error(`missing Shadow Arena engine marker: ${m}`);
for(const m of ['token.actions.githubusercontent.com','v2-shadow-arena','v17-shadow-scorer.yml@refs/heads/main','crypto.subtle.verify','score_queue','preOutcome:true'])if(!gateway.includes(m))throw new Error(`missing OIDC score-gateway marker: ${m}`);
const scorerMarkers=dual?['granite-timeseries-ttm-r2','observed_bar_at','bosReference','calibrate_ttm','V2_OIDC','context_source']:['granite-timeseries-ttm-r2','observed_bar_at','bosReference','calibrate','V2_OIDC','context_source'];
for(const m of scorerMarkers)if(!scorer.includes(m))throw new Error(`missing TTM scorer marker: ${m}`);
for(const m of ['fit_through_year','2025','logistic_coef','source_artifact_sha256','shadow only'])if(!calibrator.includes(m))throw new Error(`missing frozen TTM calibrator marker: ${m}`);
const workflowScorer=dual?'v18_shadow_observer_scorer.py':'v17_shadow_ttm_scorer.py';
for(const m of ['id-token: write','audience=v2-shadow-arena',workflowScorer,'torch==2.10.0'])if(!workflow.includes(m))throw new Error(`missing secretless scorer workflow marker: ${m}`);
for(const m of ['shadow_forecasts','shadow_model_registry','model_spec_hash','enable row level security','service_role','PROMOTE_TTM_TO_SHADOW'])if(!migration.includes(m))throw new Error(`missing Shadow Arena migration marker: ${m}`);
new vm.Script(js,{filename:'web/v17-shadow.js'});
console.log(`v1.7 Shadow Arena validation passed: immutable prospective capture, OIDC-authenticated ${dual?'dual-observer':'TTM'} shadow scoring, automatic resolution and abstention UI present`);
