import fs from 'node:fs';
import vm from 'node:vm';
const protocol=fs.readFileSync('reports/v18/V18_MODEL_COUNCIL_PROTOCOL.md','utf8');
const results=fs.readFileSync('reports/v18/V18_MODEL_COUNCIL_RESULTS.md','utf8');
const student=JSON.parse(fs.readFileSync('reports/v18/V18_STATE_TWIN_STUDENT.json','utf8'));
const research=fs.readFileSync('scripts/v18_model_council_research.py','utf8');
const observer=fs.readFileSync('scripts/v18_shadow_observer_scorer.py','utf8');
const gateway=fs.readFileSync('supabase/functions/shadow-score-gateway/index.ts','utf8');
const council=fs.readFileSync('supabase/functions/model-council/index.ts','utf8');
const migration=fs.readFileSync('supabase/migrations/20260811002500_v18_model_council.sql','utf8');
const workflow=fs.readFileSync('.github/workflows/v17-shadow-scorer.yml','utf8');
const loader=fs.readFileSync('web/v17-shadow.js','utf8');
const js=fs.readFileSync('web/v18-council.js','utf8');
const css=fs.readFileSync('web/v18.css','utf8');
for(const m of ['paired campaign bootstrap','0.15','age 0 only','Falsification rule'])if(!protocol.includes(m))throw new Error(`missing frozen v1.8 protocol marker: ${m}`);
for(const m of ['REJECT_COUNCIL_INCREMENTAL','PROMOTE_STATE_TWIN_STUDENT_TO_SHADOW','-0.000221','0.9200'])if(!results.includes(m))throw new Error(`missing frozen v1.8 result marker: ${m}`);
if(student.historical_gate!=='PASS'||student.version!=='state-twin-student-v18-through-2025'||student.eligible_landmark_age_bars?.[0]!==0)throw new Error('invalid frozen StateTwin student artifact');
for(const m of ['BOOTSTRAP_REPS = 2000','choose_council_weight','paired_bootstrap_ci','PROMOTE_STATE_TWIN_STUDENT_TO_SHADOW','REJECT_COUNCIL_INCREMENTAL'])if(!research.includes(m))throw new Error(`missing v1.8 research marker: ${m}`);
for(const m of ['TTM_VERSION = "granite-ttm-r2-v17"','STUDENT_VERSION = "state-twin-student-v18"','student_features','score_student','score_ttm','landmark_age_bars'])if(!observer.includes(m))throw new Error(`missing dual observer scorer marker: ${m}`);
for(const m of ['new Set([TTM,STUDENT])','landmark_age_bars",0','missing_models','eligibleLandmarkAgeBars:[0]'])if(!gateway.includes(m))throw new Error(`missing dual age-zero gateway guard: ${m}`);
for(const m of ['V2 Model Council v1.8','probabilityVisible:false','MODEL_DISAGREEMENT','resolvedBoth','unlockAt:30'])if(!council.includes(m))throw new Error(`missing Council endpoint boundary: ${m}`);
for(const m of ['state-twin-student-v18','model-council-v18','REJECT_COUNCIL_INCREMENTAL','eligibleLandmarkAgeBars'])if(!migration.includes(m))throw new Error(`missing registry decision marker: ${m}`);
for(const m of ['name: v18-shadow-observers','id-token: write','v18_shadow_observer_scorer.py','V18_STATE_TWIN_STUDENT.json'])if(!workflow.includes(m))throw new Error(`missing OIDC observer workflow marker: ${m}`);
for(const m of ["asset('v18.css')","asset('v18-council.js')",'loadV18'])if(!loader.includes(m))throw new Error(`missing v1.8 additive loader: ${m}`);
for(const m of ['Version 1.8 · Model Council','PROBABILITY WITHHELD','Eligible age-0 records','Model Council'])if(!js.includes(m))throw new Error(`missing Council UI marker: ${m}`);
for(const m of ['.modelCouncilResearch','.councilGrid','.councilDecisions','@media(max-width:560px)'])if(!css.includes(m))throw new Error(`missing Council CSS marker: ${m}`);
new vm.Script(js,{filename:'web/v18-council.js'});
new vm.Script(loader,{filename:'web/v17-shadow.js'});
console.log('v1.8 validation passed: Council rejection frozen, StateTwin student shadow artifact frozen, dual age-zero observers OIDC-wired, qualitative-only browser contract intact');