import fs from 'node:fs';
import vm from 'node:vm';
const protocol=fs.readFileSync('reports/v18/V18_MODEL_COUNCIL_PROTOCOL.md','utf8');
const research=fs.readFileSync('scripts/v18_model_council_research.py','utf8');
const gateway=fs.readFileSync('supabase/functions/shadow-score-gateway/index.ts','utf8');
const council=fs.readFileSync('supabase/functions/model-council/index.ts','utf8');
const ttm=fs.readFileSync('scripts/v17_shadow_ttm_scorer.py','utf8');
const loader=fs.readFileSync('web/v17-shadow.js','utf8');
const js=fs.readFileSync('web/v18-council.js','utf8');
const css=fs.readFileSync('web/v18.css','utf8');
for(const m of ['paired campaign bootstrap','0.15','age 0 only','Falsification rule'])if(!protocol.includes(m))throw new Error(`missing frozen v1.8 protocol marker: ${m}`);
for(const m of ['BOOTSTRAP_REPS = 2000','choose_council_weight','paired_bootstrap_ci','PROMOTE_STATE_TWIN_STUDENT_TO_SHADOW','REJECT_COUNCIL_INCREMENTAL'])if(!research.includes(m))throw new Error(`missing v1.8 research marker: ${m}`);
for(const m of ['landmark_age_bars",0','eligibleLandmarkAgeBars:[0]'])if(!gateway.includes(m))throw new Error(`missing age-zero gateway guard: ${m}`);
for(const m of ['landmark_age_bars','!= 0','eligible_landmark_age_bars'])if(!ttm.includes(m))throw new Error(`missing age-zero TTM guard: ${m}`);
for(const m of ['V2 Model Council v1.8','probabilityVisible:false','MODEL_DISAGREEMENT','resolvedBoth','unlockAt:30'])if(!council.includes(m))throw new Error(`missing Council endpoint boundary: ${m}`);
for(const m of ['/v18.css','/v18-council.js','loadV18'])if(!loader.includes(m))throw new Error(`missing v1.8 additive loader: ${m}`);
for(const m of ['Version 1.8 · Model Council','PROBABILITY WITHHELD','Eligible age-0 records','Model Council'])if(!js.includes(m))throw new Error(`missing Council UI marker: ${m}`);
for(const m of ['.modelCouncilResearch','.councilGrid','.councilDecisions','@media(max-width:560px)'])if(!css.includes(m))throw new Error(`missing Council CSS marker: ${m}`);
new vm.Script(js,{filename:'web/v18-council.js'});
new vm.Script(loader,{filename:'web/v17-shadow.js'});
console.log('v1.8 Model Council validation passed: frozen incremental gate, age-zero eligibility, qualitative-only browser contract and additive UI present');
