import {readFileSync} from 'node:fs';
const css=readFileSync('web/v32-ui.css','utf8');
const loader=readFileSync('web/v32-ui.js','utf8');
const icons=readFileSync('web/v32-icons.js','utf8');
const copy=readFileSync('web/v32-copy.js','utf8');
const stage=readFileSync('web/v32-stage.js','utf8');
const mobile=readFileSync('web/v29-mobile-ux.js','utf8');
const must=(ok,msg)=>{if(!ok)throw new Error(msg)};
must(css.includes("rsms.me/inter/inter.css"),'Inter official CDN import missing');
must(css.includes('font-family:Inter'),'Inter is not the global UI typeface');
must(css.includes('.bottom{')&&css.includes('backdrop-filter:blur(26px)'),'floating navigation control layer missing');
must(css.includes('.focusGrid .focusCard:nth-child(2)'),'mobile progressive-disclosure rule missing');
must(css.includes('.v32StageSheet'),'stage guide styles missing');
must(icons.includes('lucide@1.27.0')&&icons.includes('chart-candlestick'),'Lucide icon adapter missing or unpinned');
must(copy.includes("'Home'")&&copy.includes('Data quality'),'plain-language navigation/copy missing');
must((stage.match(/\['/g)||[]).length>=9,'expected nine stage definitions');
must(stage.includes('Waiting for structure break')&&stage.includes('Entry zone reached'),'stage guide is incomplete');
must(loader.includes('v31-quality.js')&&loader.includes('v32-stage.js'),'V3.2 module loader incomplete');
must(mobile.includes("v32-ui.css")&&mobile.includes("v32-ui.js"),'V3.2 is not wired into the shipped app');
console.log('V3.2 UI static validation passed: Inter, Lucide, hierarchy, stage guide and progressive disclosure are wired.');
