import {spawn,execFileSync} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';

const URL=process.env.SMOKE_URL||'https://v2trading.vercel.app';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function chromePath(){for(const n of ['google-chrome','google-chrome-stable','chromium','chromium-browser']){try{return execFileSync('which',[n],{encoding:'utf8'}).trim()}catch{}}throw new Error('Chrome not found')}
async function waitJson(url,timeout=10000){const end=Date.now()+timeout;while(Date.now()<end){try{const r=await fetch(url);if(r.ok)return r.json()}catch{}await sleep(150)}throw new Error('Chrome debug endpoint timeout')}
async function target(port){const end=Date.now()+12000;while(Date.now()<end){try{const r=await fetch(`http://127.0.0.1:${port}/json/list`);if(r.ok){const xs=await r.json();const p=xs.find(x=>x.type==='page'&&x.webSocketDebuggerUrl);if(p)return p}}catch{}await sleep(150)}throw new Error('No Chrome page target')}
const profile=mkdtempSync(join(tmpdir(),'v32-live-'));const port=9333;const chrome=spawn(chromePath(),['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'about:blank'],{stdio:'ignore'});let ws;
try{
  await waitJson(`http://127.0.0.1:${port}/json/version`);const t=await target(port);ws=new WebSocket(t.webSocketDebuggerUrl);await new Promise((res,rej)=>{ws.addEventListener('open',res,{once:true});ws.addEventListener('error',rej,{once:true})});let seq=0;const waiting=new Map(),exceptions=[];ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&waiting.has(m.id)){const w=waiting.get(m.id);waiting.delete(m.id);m.error?w.reject(new Error(m.error.message)):w.resolve(m.result);return}if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params?.exceptionDetails?.exception?.description||m.params?.exceptionDetails?.text||'exception')});
  const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;waiting.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
  const ev=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value};
  await call('Page.enable');await call('Runtime.enable');await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:3,mobile:true,screenWidth:390,screenHeight:844});await call('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await call('Page.navigate',{url:URL});
  const end=Date.now()+40000;let ready=false;while(Date.now()<end){ready=await ev("document.readyState==='complete' && !!document.querySelector('#v32StageButton') && getComputedStyle(document.body).fontFamily.toLowerCase().includes('inter')");if(ready)break;await sleep(300)}if(!ready)throw new Error('V3.2 UI did not initialize');
  const iconEnd=Date.now()+15000;let iconCount=0;while(Date.now()<iconEnd){iconCount=await ev("document.querySelectorAll('svg.lucide').length");if(iconCount>=5)break;await sleep(250)}if(iconCount<5)throw new Error(`Lucide icons not active: ${iconCount}`);
  const state=await ev(`(()=>{const b=document.querySelector('#v32StageButton'),grid=document.querySelector('#focusBoard .focusGrid');const visible=grid?[...grid.children].filter(x=>getComputedStyle(x).display!=='none').length:0;return{font:getComputedStyle(document.body).fontFamily,stage:b?.textContent.trim()||'',visible,overflow:document.documentElement.scrollWidth-window.innerWidth,minAction:Math.min(...[...document.querySelectorAll('.focusAction,.pairBtn,.navBtn,.iconBtn,#v32StageButton')].filter(x=>x.offsetParent!==null).map(x=>x.getBoundingClientRect().height))}})()`);if(state.visible>2)throw new Error(`Home still cluttered: ${state.visible} operational cards visible`);if(state.overflow>1)throw new Error(`Horizontal overflow ${state.overflow}px`);if(state.minAction<44)throw new Error(`Touch target too small: ${state.minAction}`);
  const opened=await ev(`(()=>{const b=document.querySelector('#v32StageButton');b?.click();const l=document.querySelector('#v32StageLayer');return !!l&&!l.hidden})()`);if(!opened)throw new Error('Stage guide did not open');await sleep(200);const guide=await ev(`(()=>({items:document.querySelectorAll('.v32StageItem').length,current:document.querySelectorAll('.v32StageItem[aria-current="step"]').length,title:document.querySelector('#v32StageTitle')?.textContent||''}))()`);if(guide.items!==9||guide.current!==1||guide.title!=='How V2 stages work')throw new Error(`Stage guide invalid: ${JSON.stringify(guide)}`);
  const qEnd=Date.now()+15000;let quality=false;while(Date.now()<qEnd){quality=await ev("!!document.querySelector('#v31QualityJs') && !!document.querySelector('#v31QualityCss')");if(quality)break;await sleep(250)}if(!quality)throw new Error('V3.1 setup-quality layer not loaded by V3.2');if(exceptions.length)throw new Error(`Browser exceptions: ${exceptions.join(' | ')}`);
  console.log(JSON.stringify({ok:true,url:URL,font:state.font,lucideIcons:iconCount,homeOperationalCards:state.visible,stageGuideItems:guide.items,noHorizontalOverflow:true}));
}finally{try{ws?.close()}catch{}try{chrome.kill('SIGKILL')}catch{}await sleep(250);try{rmSync(profile,{recursive:true,force:true})}catch{}}
