import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SB=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SB,KEY,{auth:{persistSession:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-v2-feed-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const hex=(b:ArrayBuffer)=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function auth(req:Request){const token=req.headers.get('x-v2-feed-token')?.trim();if(!token)return null;const hash=hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)));const q=await db.from('v2_live_feed_ingest_keys').select('token_hash,label').eq('token_hash',hash).eq('active',true).maybeSingle();if(q.error||!q.data)return null;await db.from('v2_live_feed_ingest_keys').update({last_used_at:new Date().toISOString()}).eq('token_hash',hash);return q.data;}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return J({error:'POST only'},405);try{const key=await auth(req);if(!key)return J({ok:false,error:'unauthorized feed gateway'},401);const body=await req.json();const xs=Array.isArray(body?.quotes)?body.quotes.slice(0,10):[body],results:any[]=[];for(const x of xs){const provider=String(x?.provider||'').trim(),symbol=String(x?.symbol||'').toUpperCase(),observedAt=x?.observedAt,bid=Number(x?.bid),ask=Number(x?.ask),quoteId=x?.quoteId==null?null:String(x.quoteId),meta={...(x?.meta||{}),gateway:key.label};if(!provider||!['EURUSD','GBPUSD'].includes(symbol)||!observedAt||!Number.isFinite(bid)||!Number.isFinite(ask)){results.push({ok:false,error:'invalid quote payload',symbol});continue}const q=await db.rpc('v2_process_stream_quote',{p_provider:provider,p_symbol:symbol,p_observed_at:observedAt,p_bid:bid,p_ask:ask,p_quote_id:quoteId,p_meta:meta});if(q.error){results.push({ok:false,error:q.error.message,symbol});continue}results.push({ok:true,...q.data});}
const changed=results.filter(x=>x.ok&&x.applied&&['stream_entry','stream_win','stream_loss'].includes(String(x.action)));let discordKick:any=null;if(changed.length){try{const c=new AbortController();const t=setTimeout(()=>c.abort(),2500);const r=await fetch(`${SB}/functions/v1/discord-pulse-v6`,{method:'GET',headers:{'Authorization':`Bearer ${KEY}`},signal:c.signal});clearTimeout(t);discordKick={status:r.status,ok:r.ok}}catch(e){discordKick={ok:false,error:String(e)}}}return J({ok:results.every(x=>x.ok),version:'V2 live feed bridge v2',processed:results.length,results,discordKick})}catch(e){console.error(e);return J({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
