(()=>{
'use strict';
const BASE='https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/';
const BUILD='V2 UI health.1 · 2026-08-18';
const CORE_REFRESH_MS=60000,HEALTH_REFRESH_MS=30000;
const $=s=>document.querySelector(s);
let health=null,lastHealthAt=0,lastCoreKick=Date.now(),lastCoreSuccessAt=0,coreServices={},healthBusy=false;
let observer=null;
const age=v=>{if(!v)return null;const x=Math.max(0,(Date.now()-new Date(v).getTime())/60000);return Number.isFinite(x)?x:null};
const ageText=v=>{const x=typeof v==='number'?v:age(v);if(x==null)return'—';if(x<1)return'<1m';if(x<60)return`${Math.round(x)}m`;return`${Math.floor(x/60)}h ${Math.round(x%60)}m`};
const time=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.valueOf())?'—':d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})};
const short=s=>String(s??'').replace(/\s+/g,' ').slice(0,72);
function row(label,value,ok=null){const cls=ok===true?'ok':ok===false?'bad':'';return `<div class="service"><span>${label}</span><b class="${cls}">${value}</b></div>`}
function captureCore(){const root=$('#services');if(!root)return;const found={};root.querySelectorAll('.service').forEach(el=>{const label=el.querySelector('span')?.textContent?.trim(),value=el.querySelector('b')?.textContent?.trim();if(label&&value)found[label]=value});const keys=['EURUSD market state','GBPUSD market state','Paper trade engine','Portfolio snapshot'];const hits=keys.filter(k=>found[k]);if(hits.length){coreServices=found;const ok=hits.filter(k=>/^OK\b/.test(found[k])).length;if(ok===hits.length)lastCoreSuccessAt=Date.now()}}
function job(name){return(health?.jobs||[]).find(x=>x.name===name)||null}
function market(sym){return(health?.market||[]).find(x=>x.symbol===sym)||null}
function browserErrorRow(){const errors=Array.isArray(window.__v2BrowserErrors)?window.__v2BrowserErrors:[];if(!errors.length)return row('Browser JavaScript','0 errors',true);const e=errors[errors.length-1];return row('Browser JavaScript',`${errors.length} · ${short(e.message||e.reason||'error')}`,false)}
function render(){const root=$('#services');if(!root)return;captureCore();const eur=market('EURUSD'),gbp=market('GBPUSD'),paperJob=job('v2-paper-trade-engine-5m'),discordJob=job('v2-discord-fx-pulse-2m'),closureJob=job('v2-discord-fx-closures-5m'),qualityJob=job('v2-discord-quality-2m'),v34=job('v34-market-intelligence'),v35=job('v35-trend-candle-engine-1m');const coreVals=['EURUSD market state','GBPUSD market state','Paper trade engine','Portfolio snapshot'].map(k=>coreServices[k]).filter(Boolean),coreOk=coreVals.length?coreVals.filter(v=>/^OK\b/.test(v)).length:null;const coreText=lastCoreSuccessAt?`${time(lastCoreSuccessAt)} · ${coreOk??'—'}/${coreVals.length||4} OK`:'waiting for first refresh';const discord=health?.discord;const audit=health?.executionAudit;const rows=[row('UI + navigation','READY',true),row('Frontend build',BUILD,true),browserErrorRow(),row('Core UI refresh',coreText,lastCoreSuccessAt>0),eur?row('EURUSD completed-M15',`${eur.status.toUpperCase()} · Stage ${eur.formationStage??'—'} · ${ageText(eur.stateAgeMinutes)} old`,eur.status==='healthy'):row('EURUSD completed-M15','checking…',null),gbp?row('GBPUSD completed-M15',`${gbp.status.toUpperCase()} · Stage ${gbp.formationStage??'—'} · ${ageText(gbp.stateAgeMinutes)} old`,gbp.status==='healthy'):row('GBPUSD completed-M15','checking…',null),paperJob?row('Paper engine scheduler',`${paperJob.status.toUpperCase()} · every 1m · last ${ageText(paperJob.lastRunAgeMinutes)} ago`,paperJob.status==='healthy'):row('Paper engine scheduler','checking…',null),row('Portfolio snapshot',coreServices['Portfolio snapshot']||'checking…',coreServices['Portfolio snapshot']?/^OK\b/.test(coreServices['Portfolio snapshot']):null),discord?row('Discord heartbeat',`${discord.status.toUpperCase()} · ${ageText(discord.heartbeatAgeMinutes)} old`,discord.status==='healthy'):row('Discord heartbeat','checking…',null),discord?row('Last Discord alert',discord.lastAlertSentAt?`${discord.lastAlertSymbol||''} ${String(discord.lastAlertType||'').replaceAll('_',' ')} · ${time(discord.lastAlertSentAt)}`:'No alert sent yet',true):'',audit?row('Execution audit',`${audit.audited_trades??0} audited · ${audit.confirmed_entries??0} entries confirmed · ${ageText(audit.latest_audit_at)} old`,true):row('Execution audit','checking…',null),discordJob&&closureJob&&qualityJob?row('Discord schedulers',[discordJob,closureJob,qualityJob].every(x=>x.status==='healthy')?'3/3 HEALTHY':'ATTENTION',[discordJob,closureJob,qualityJob].every(x=>x.status==='healthy')):'',v34&&v35?row('Research schedulers',`${v34.status==='healthy'?'V3.4 OK':'V3.4 attention'} · ${v35.status==='healthy'?'V3.5 OK':'V3.5 attention'}`,v34.status==='healthy'&&v35.status==='healthy'):'',health?row('Health snapshot',`${String(health.overall||'unknown').toUpperCase()} · ${time(health.generatedAt)}`,health.overall==='healthy'):row('Health snapshot','checking…',null)].filter(Boolean);
if(observer)observer.disconnect();root.innerHTML=rows.join('');if(observer)observer.observe(root,{childList:true,subtree:true})}
async function loadHealth(){if(healthBusy)return;healthBusy=true;const c=new AbortController(),t=setTimeout(()=>c.abort(),5500);try{const r=await fetch(BASE+'v2-health',{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`health HTTP ${r.status}`);health=await r.json();lastHealthAt=Date.now();render()}catch(e){health={...(health||{}),overall:'attention'};render()}finally{clearTimeout(t);healthBusy=false}}
function kickCore(){const btn=$('#refresh');if(document.visibilityState!=='visible'||!btn||btn.disabled)return;lastCoreKick=Date.now();btn.click();setTimeout(loadHealth,4500)}
function setupObserver(){const root=$('#services');if(!root)return;observer=new MutationObserver(()=>{captureCore();render()});observer.observe(root,{childList:true,subtree:true})}
setupObserver();
window.addEventListener('v2:browser-error',()=>render());
const refresh=$('#refresh');if(refresh)refresh.addEventListener('click',()=>setTimeout(loadHealth,700));
window.addEventListener('v2:view',e=>{if(e.detail?.id==='system'&&Date.now()-lastHealthAt>10000)loadHealth()});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){if(Date.now()-lastHealthAt>HEALTH_REFRESH_MS)loadHealth();if(Date.now()-lastCoreKick>CORE_REFRESH_MS)kickCore()}});
setInterval(()=>{if(document.visibilityState==='visible'&&Date.now()-lastHealthAt>=HEALTH_REFRESH_MS)loadHealth()},10000);
setInterval(()=>{if(document.visibilityState==='visible'&&Date.now()-lastCoreKick>=CORE_REFRESH_MS)kickCore()},10000);
setTimeout(loadHealth,350);
})();
