(()=>{
'use strict';
const BASE='https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/';
const ENDPOINTS={EURUSD:'eurusd-market-lab',GBPUSD:'market-lab?symbol=GBPUSD',paper:'paper-trade-engine?symbol=EURUSD,GBPUSD&bars=1',portfolio:'portfolio-snapshot'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cache={states:{},paper:null,portfolio:null,research:null};
let pairFilter='ALL',qualityFilter='ALL',chartPair='EURUSD',chartLoaded='',researchLoaded=false;
const n=v=>v===null||v===undefined||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const px=v=>n(v)==null?'—':Number(v).toFixed(5);
const cap=v=>String(v??'—').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const money=v=>n(v)==null?'—':`${Number(v)>=0?'+':'-'}$${Math.abs(Number(v)).toFixed(2)}`;
const when=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.valueOf())?'—':d.toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})};
function duration(a,b){if(!a||!b)return'—';const mins=Math.max(0,Math.round((new Date(b)-new Date(a))/60000));if(mins<60)return`${mins}m`;const h=Math.floor(mins/60),m=mins%60;return m?`${h}h ${m}m`:`${h}h`}
const STAGES={0:['No setup yet','Wait for price to approach meaningful liquidity.'],1:['Liquidity nearby','Wait for an actual liquidity sweep.'],2:['Previous zone used','Wait for a fresh sequence.'],3:['Liquidity sweep confirmed','Wait for a completed break of structure.'],4:['Waiting for structure break','No entry yet. Structure must confirm first.'],5:['Structure break confirmed','Wait for a fresh POI.'],6:['Fresh POI found','Wait for price to retrace to the midpoint.'],7:['Price approaching POI','Watch the midpoint interaction.'],8:['Entry zone reached','Paper engine checks the midpoint/path rule.']};
async function get(path,ms=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms),start=performance.now();try{const r=await fetch(BASE+path,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return{data:await r.json(),ms:Math.round(performance.now()-start)}}finally{clearTimeout(t)}}
function extractState(x,sym){if(!x)return{};if(x.state)return x.state;if(Array.isArray(x.states))return x.states.find(v=>v.symbol===sym)||{};return{}}
function activePlan(sym){const ts=cache.paper?.trades||[];return ts.find(t=>t.symbol===sym&&t.status==='open')||ts.find(t=>t.symbol===sym&&t.status==='armed'&&t.focus_active!==false&&t.lifecycle_phase!=='outside_studied_tail')||null}
function quality(t){const cond=String(t.setup_condition||'intact'),bars=n(t.bars_to_entry)??n(t.pending_age_bars)??0,pre=Boolean(t.pre_entry_target_reached)||cond.includes('after_target')||cond==='target_delivered_before_entry',partial=cond.includes('partially_mitigated');let tier='clean',label='Clean',hint='No weakening condition was recorded before entry.';if(pre&&bars>48){tier='longtail';label='Long-tail · after target';hint='The target was delivered before this later entry and the plan waited beyond 48 M15 bars.'}else if(pre){tier='weakened';label='After-target entry';hint='The target was delivered before entry. Keep this separate in research.'}else if(partial){tier='weakened';label='Weakened';hint='Price interacted with part of the POI before the midpoint entry.'}else if(bars>48){tier='longtail';label='Long-tail';hint='Entry arrived after more than 48 M15 bars.'}else if(bars>8){tier='extended';label='Extended wait';hint='The plan remained intact but entry arrived after the first 8 M15 bars.'}return{tier,label,hint,bars,pre,partial}}
function qualityChips(t){const q=quality(t),chips=[`<span class="qchip ${q.tier}">${esc(q.label)}</span>`];if(q.pre&&!q.label.toLowerCase().includes('target'))chips.push('<span class="qchip weakened">Target before entry</span>');if(q.bars>48&&!q.label.toLowerCase().includes('long-tail'))chips.push('<span class="qchip longtail">Long-tail</span>');return chips.join('')}
function nextFor(stage,t){if(t?.status==='open')return'Trade is open. Frozen stop and target remain unchanged.';if(t?.status==='armed')return'Plan is armed. Wait for the POI midpoint entry.';return(STAGES[stage]||['Monitoring','Wait for the next completed structural event.'])[1]}
function stateCard(sym,full=true){const s=cache.states[sym]||{},stage=Math.max(0,Math.min(8,n(s.formation_stage)??0)),meta=STAGES[stage]||[`Stage ${stage}`,'Monitoring'],t=activePlan(sym),lo=n(t?.poi_low??s.poi_low),hi=n(t?.poi_high??s.poi_high),hasPoi=lo!=null&&hi!=null,why=s.formation_label||s.research_summary||meta[0],dir=cap(t?.direction||s.formation_direction||'monitoring'),pct=stage/8*100;let levels='';if(full&&(t||hasPoi)){levels='<div class="levels">'+(t?`<div><span>POI</span><b>${hasPoi?px(lo)+'–'+px(hi):'—'}</b></div><div><span>Entry</span><b>${px(t.entry_price)}</b></div><div><span>SL</span><b>${px(t.stop_price)}</b></div><div><span>TP</span><b>${px(t.target_price)}</b></div>`:`<div><span>POI low</span><b>${px(lo)}</b></div><div><span>POI high</span><b>${px(hi)}</b></div><div><span>Midpoint</span><b>${px((lo+hi)/2)}</b></div><div><span>Distance</span><b>${n(s.distance_to_poi_atr)==null?'—':Number(s.distance_to_poi_atr).toFixed(2)+' ATR'}</b></div>` )+'</div>'}
return `<div class="pairTop"><div><strong>${sym}</strong><div class="pairPrice">${px(s.reference_price)}</div></div><span class="stageBadge ${stage>=3?'active':''}">Stage ${stage}/8</span></div><div class="stageTrack"><i style="width:${pct}%"></i></div><div class="stageName">${esc(meta[0])}${dir!=='Monitoring'?` · ${esc(dir)}`:''}</div><p>${esc(why)}</p><div class="next"><b>Next</b><span>${esc(nextFor(stage,t))}</span></div>${levels}`}
function renderStates(){['EURUSD','GBPUSD'].forEach(sym=>{const h=$(`#${sym}Home`),tr=$(`#${sym}Trade`),r=$(`#${sym}Research`);if(h)h.innerHTML=stateCard(sym,false);if(tr)tr.innerHTML=stateCard(sym,true);if(r)r.innerHTML=stateCard(sym,true)})}
function renderAccount(){const a=cache.portfolio?.account;if(!a)return;const bal=n(a.realizedBalanceUsd)??500,pnl=n(a.realizedPnlUsd)??0,growth=n(a.growthPct)??0;$('#balance').textContent=`$${bal.toFixed(2)}`;$('#pnl').textContent=`${money(pnl)} · ${growth>=0?'+':''}${growth.toFixed(2)}%`;$('#pnl').className=`accountPnl ${pnl>=0?'good':'bad'}`;$('#record').textContent=`${a.wins||0}W · ${a.losses||0}L · ${a.timeouts||0}T`;$('#openNow').textContent=String(a.openTrades||0);$('#riskNext').textContent=`$${(bal*.01).toFixed(2)}`;$('#drawdown').textContent=n(a.maxDrawdownPct)==null?'—':`${Number(a.maxDrawdownPct).toFixed(2)}%`;$('#tradeBalance').textContent=`$${bal.toFixed(2)}`;$('#tradePnl').textContent=money(pnl);$('#tradePnl').className=pnl>=0?'good':'bad';$('#tradeOpen').textContent=String(a.openTrades||0)}
function metricFor(t){return(cache.portfolio?.tradeMetrics||[]).find(m=>m.tradeKey===t.trade_key)||{}}
function resultFor(t,m){if(t.status==='open'){const r=n(m.currentR);return{main:'OPEN',sub:r==null?'Active paper trade':`${r>=0?'+':''}${r.toFixed(2)}R now`,cls:r!=null&&r<0?'bad':'good'}}const r=n(t.gross_r),usd=n(m.realizedPnlUsd);return{main:r==null?cap(t.status):`${r>=0?'+':''}${r.toFixed(2)}R`,sub:usd==null?cap(t.status):money(usd),cls:r==null?'':r>=0?'good':'bad'}}
function tradeCard(t){const m=metricFor(t),q=quality(t),res=resultFor(t,m),lead=duration(t.armed_at,t.entry_at),held=t.exit_at?duration(t.entry_at,t.exit_at):duration(t.entry_at,new Date().toISOString()),poi=n(t.poi_low)!=null&&n(t.poi_high)!=null?`${px(t.poi_low)}–${px(t.poi_high)}`:'—',exitLabel=t.exit_at?when(t.exit_at):'Open';return `<details class="tradeCard" data-quality="${q.tier}" data-symbol="${esc(t.symbol)}"><summary><div class="tradeMain"><div class="tradeTitle"><strong>${esc(t.symbol)}</strong><span class="direction">${esc(String(t.direction||'').toUpperCase())}</span>${qualityChips(t)}</div><div class="tradeWhen">${when(t.entry_at)} → ${exitLabel}</div></div><div class="tradeDur"><span>Plan lead <b>${lead}</b></span><span>Held <b>${held}</b></span></div><div class="tradeResult ${res.cls}">${esc(res.main)}<small>${esc(res.sub)}</small></div></summary><div class="tradeBody"><div class="timeline"><div><span>Plan ready</span><b>${when(t.armed_at)}</b></div><i>→</i><div><span>Entered</span><b>${when(t.entry_at)}</b></div><i>→</i><div><span>${t.exit_at?'Exited':'Now'}</span><b>${exitLabel}</b></div></div><div class="geometry"><div><span>POI</span><b>${poi}</b></div><i>→</i><div><span>Entry</span><b>${px(t.entry_price)}</b></div><i>↙</i><div><span>SL</span><b>${px(t.stop_price)}</b></div><i>↘</i><div><span>TP</span><b>${px(t.target_price)}</b></div></div><div class="detailGrid"><div><span>Risk</span><b>${n(m.riskUsd)==null?'—':`$${Number(m.riskUsd).toFixed(2)}`}</b></div><div><span>Result pips</span><b>${n(m.realizedPips)==null?'—':`${Number(m.realizedPips)>=0?'+':''}${Number(m.realizedPips).toFixed(1)}`}</b></div><div><span>Bars to entry</span><b>${n(t.bars_to_entry)==null?'—':String(t.bars_to_entry)}</b></div><div><span>Setup condition</span><b>${esc(cap(t.setup_condition||'intact'))}</b></div><div><span>MFE</span><b>${n(t.mfe_r)==null?'—':Number(t.mfe_r).toFixed(2)+'R'}</b></div><div><span>MAE</span><b>${n(t.mae_r)==null?'—':Number(t.mae_r).toFixed(2)+'R'}</b></div></div><div class="qualityNote"><b>${esc(q.label)}</b> · ${esc(q.hint)} This label is descriptive research context and does not rewrite the frozen V2 result.</div></div></details>`}
function renderTrades(){const all=(cache.paper?.trades||[]).filter(t=>t.entry_at).sort((a,b)=>new Date(b.entry_at)-new Date(a.entry_at));const waiting=(cache.paper?.trades||[]).filter(t=>t.status==='armed'&&t.focus_active!==false&&t.lifecycle_phase!=='outside_studied_tail').length;$('#plansWaiting').textContent=String(waiting);let rows=all;if(pairFilter!=='ALL')rows=rows.filter(t=>t.symbol===pairFilter);if(qualityFilter!=='ALL')rows=rows.filter(t=>quality(t).tier===qualityFilter);const root=$('#tradeList');root.innerHTML=rows.length?rows.map(tradeCard).join(''):'<div class="empty">No entered trades match these filters.</div>';const counts={clean:0,weakened:0,extended:0,longtail:0};all.forEach(t=>{const q=quality(t).tier;counts[q]=(counts[q]||0)+1});$('#qualitySummary').textContent=`${counts.clean||0} clean · ${counts.weakened||0} weakened · ${counts.extended||0} extended · ${counts.longtail||0} long-tail`}
$$('[data-pair-filter]').forEach(b=>b.addEventListener('click',()=>{pairFilter=b.dataset.pairFilter;$$('[data-pair-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTrades()}));
$$('[data-quality-filter]').forEach(b=>b.addEventListener('click',()=>{qualityFilter=b.dataset.qualityFilter;$$('[data-quality-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTrades()}));
function chartUrl(sym){const tv=sym==='GBPUSD'?'OANDA%3AGBPUSD':'OANDA%3AEURUSD';return`https://s.tradingview.com/widgetembed/?frameElementId=v2chart&symbol=${tv}&interval=15&hidesidetoolbar=0&symboledit=0&saveimage=0&toolbarbg=11161c&theme=dark&style=1&timezone=Etc%2FUTC&withdateranges=1&hideideas=1`}
function loadChart(force=false){if(chartLoaded===chartPair&&!force)return;chartLoaded=chartPair;$('#chartTitle').textContent=`${chartPair} · 15 minute`;$('#chartHost').innerHTML=`<iframe class="chartFrame" title="${chartPair} TradingView chart" src="${chartUrl(chartPair)}" loading="eager" referrerpolicy="origin"></iframe>`}
$$('[data-chart-pair]').forEach(b=>b.addEventListener('click',()=>{chartPair=b.dataset.chartPair;$$('[data-chart-pair]').forEach(x=>x.classList.toggle('active',x===b));loadChart(true)}));
window.addEventListener('v2:view',e=>{if(e.detail?.id==='chart')loadChart();if(e.detail?.id==='research')loadResearch()});
async function loadResearch(){if(researchLoaded)return;researchLoaded=true;const box=$('#researchLive');box.innerHTML='<div class="empty">Loading V3.5 research snapshot…</div>';try{const r=await get('trend-candle-engine?symbol=EURUSD,GBPUSD',6500);cache.research=r.data;const x=r.data||{},signals=Array.isArray(x.signals)?x.signals.length:Array.isArray(x.candidates)?x.candidates.length:null;box.innerHTML=`<div class="researchLiveCard"><div><span>V3.5 live research</span><strong>${esc(x.version||'Trend-candle research')}</strong><p>Loaded only after Research was opened. It remains shadow-only and cannot affect V2 paper trades.</p></div><div class="researchFacts"><b>${signals==null?'—':signals}</b><span>signals / candidates returned</span><b>${esc(when(x.generated_at||x.generatedAt))}</b><span>snapshot time</span></div></div>`}catch(e){box.innerHTML='<div class="empty">V3.5 research did not load. Baseline V2 remains fully usable.</div>'}}
function renderServices(results){const labels={EURUSD:'EURUSD market state',GBPUSD:'GBPUSD market state',paper:'Paper trade engine',portfolio:'Portfolio snapshot'},keys=Object.keys(ENDPOINTS);$('#services').innerHTML='<div class="service"><span>UI + navigation</span><b class="ok">READY</b></div>'+keys.map((k,i)=>{const r=results[i],ok=r.status==='fulfilled',txt=ok?`OK · ${r.value.ms}ms`:(r.reason?.name==='AbortError'?'TIMEOUT':'FAILED');return`<div class="service"><span>${labels[k]}</span><b class="${ok?'ok':'bad'}">${txt}</b></div>`}).join('')}
async function load(){const btn=$('#refresh');btn.disabled=true;$('#topStatus').textContent='Refreshing live data';const keys=Object.keys(ENDPOINTS),results=await Promise.allSettled(keys.map(k=>get(ENDPOINTS[k])));results.forEach((r,i)=>{if(r.status!=='fulfilled')return;const k=keys[i],d=r.value.data;if(k==='EURUSD'||k==='GBPUSD')cache.states[k]=extractState(d,k);else cache[k]=d});renderStates();renderAccount();renderTrades();renderServices(results);const ok=results.filter(r=>r.status==='fulfilled').length,healthy=ok===results.length;$('#topDot').classList.toggle('ok',healthy);$('#homeDot').classList.toggle('ok',healthy);$('#topStatus').textContent=healthy?'Live data connected':`${ok}/${results.length} services connected`;$('#healthText').textContent=healthy?'All core V2 services responded':`${ok}/${results.length} services responded; navigation remains available`;btn.disabled=false}
$('#refresh').addEventListener('click',load);setTimeout(load,80);
})();
