(()=>{
  const ENDPOINT='https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/trader-brief';
  let payload=null,loading=false,lastSymbol='';
  const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const price=v=>Number.isFinite(Number(v))?Number(v).toFixed(5):'—';
  const num=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
  const signed=(v,d=2)=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(d)}`:'—';
  const cap=v=>String(v??'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,m=>m.toUpperCase());
  const currentSymbol=()=>{if(typeof selected!=='undefined'&&selected)return selected;const a=document.querySelector('.pairSwitch .active,[data-pair].active');return (a?.textContent||'').includes('GBP')?'GBPUSD':'EURUSD'};
  const currentPair=()=>payload?.pairs?.find(x=>x.symbol===currentSymbol())||null;
  const countdown=mins=>{if(!Number.isFinite(Number(mins)))return '—';mins=Math.max(0,Math.round(Number(mins)));if(mins<60)return `${mins} min`;if(mins<1440)return `${Math.floor(mins/60)}h ${mins%60}m`;return `${Math.floor(mins/1440)}d ${Math.round((mins%1440)/60)}h`};
  const localTime=iso=>{if(!iso)return '—';try{return new Intl.DateTimeFormat(undefined,{weekday:'short',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(iso))}catch{return new Date(iso).toLocaleString()}};
  const trustTone=x=>x==='HIGH'?'good':x==='BLOCKED'?'danger':'watch';
  const macroTone=x=>x==='HIGH'?'danger':x==='WATCH'||x==='TODAY'?'watch':'good';
  function ensure(){
    document.body.classList.add('v22Active');
    let root=document.getElementById('v22BriefBoard');
    if(!root){root=document.createElement('section');root.id='v22BriefBoard';root.className='v22Board';const anchor=document.getElementById('v21DecisionBoard')||document.getElementById('focusBoard');anchor?.insertAdjacentElement('beforebegin',root)}
    const intro=document.querySelector('.intro');if(intro){const e=intro.querySelector('.eyebrow'),h=intro.querySelector('h1'),p=intro.querySelector('p');if(e)e.textContent='Version 2.2 · Trader Brief';if(h)h.textContent='Know what matters now.';if(p)p.textContent='Plain-language market structure, paper-trade progress and event risk for EURUSD and GBPUSD.'}
    return root;
  }
  function statusPills(p){const trust=p.status?.dataTrust||{},macro=p.macro||{},t=p.trade;return `<div class="v22Pills">${t?`<span class="v22Pill ${t.status==='open'?'active':'watch'}">Paper ${safe(t.status)} · ${safe(String(t.direction).toUpperCase())}</span>`:'<span class="v22Pill">No paper trade open</span>'}<span class="v22Pill ${trustTone(trust.level)}">Data ${safe(trust.level||'—')}</span><span class="v22Pill ${macroTone(macro.level)}">Event risk ${safe(macro.level||'CLEAR')}</span></div>`}
  function tradeCard(p){const t=p.trade;if(!t)return `<article class="v22Card v22TradeCard empty"><div class="v22Kicker">Trade now</div><h3>No paper trade is open</h3><p>V2 is monitoring the current setup. A paper trade appears here only after the frozen research entry rule is satisfied.</p></article>`;
    const r=Number(t.currentR),reward=Number(t.rewardR||2.5),marker=Number.isFinite(r)?Math.max(0,Math.min(100,(r+1)/(reward+1)*100)):0,remaining=Number.isFinite(Number(t.distanceToTargetR))?Math.max(0,Number(t.distanceToTargetR)):null;
    return `<article class="v22Card v22TradeCard"><div class="v22CardHead"><div><div class="v22Kicker">Trade now · paper research</div><h3>${safe(String(t.direction).toUpperCase())} · ${safe(t.label)}</h3></div><div class="v22R ${Number(t.currentR)>=0?'positive':'negative'}">${safe(signed(t.currentR))}<small>R now</small></div></div><p class="v22Lead">${safe(t.copy)}</p><div class="v22RTrack" aria-label="Paper trade progress from stop at minus one R to target at ${safe(num(reward,1))} R"><span class="stop">−1R stop</span><div class="rail"><i class="entry"></i><b style="left:${marker}%"></b></div><span class="target">+${safe(num(reward,1))}R target</span></div><div class="v22Metrics"><div><span>Current mark</span><b>${price(t.currentMark)}</b></div><div><span>Best seen</span><b>${safe(signed(t.bestSeenR))}R</b></div><div><span>Worst seen</span><b>${safe(signed(t.worstSeenR))}R</b></div><div><span>To target</span><b>${remaining==null?'—':`${num(remaining)}R`}</b></div></div><div class="v22Levels"><div><span>Entry</span><b>${price(t.entryPrice)}</b></div><div><span>Stop</span><b>${price(t.stopPrice)}</b></div><div><span>Target</span><b>${price(t.targetPrice)}</b></div></div><div class="v22Note">Frozen paper geometry. V2 tracks it; it does not move the stop or target because price or news changes.</div></article>`}
  function setupCard(p){const f=p.formation||{},plain=f.plain||{};return `<article class="v22Card"><div class="v22CardHead"><div><div class="v22Kicker">Setup now</div><h3>${safe(plain.title||f.label||'Watching market structure')}</h3></div><span class="v22Tech">${safe(plain.technicalLabel||`Stage ${f.stage||0}/8`)}</span></div><p class="v22Lead">${safe(plain.summary||'V2 is observing completed market structure.')}</p><div class="v22Next"><span>What V2 needs next</span><b>${safe(plain.next||'Wait for the next completed structural event.')}</b></div><div class="v22InlineMeta"><span>${f.direction?`${safe(String(f.direction).toUpperCase())} structure`:'No direction yet'}</span><span>${safe(cap(f.regime||'unknown'))} regime</span><span>${safe(cap(f.context||'neutral'))} HTF context</span></div></article>`}
  function macroCard(p){const m=p.macro||{},plain=m.plain||{},x=m.nextRelease;if(!x)return `<article class="v22Card"><div class="v22Kicker">Event risk</div><h3>No major scheduled event nearby</h3><p>V2 has no high-impact release in the immediate window for this pair.</p></article>`;const e=x.primaryEvent||x.events?.[0]||{};return `<article class="v22Card v22Macro ${macroTone(m.level)}"><div class="v22CardHead"><div><div class="v22Kicker">Event risk · ${safe(m.level||'CLEAR')}</div><h3>${safe(x.title)}</h3></div><div class="v22Countdown">${safe(countdown(m.minutesToNext))}<small>until release</small></div></div><p class="v22Lead">${safe(x.why||plain.copy||'This release can increase short-term volatility.')}</p><div class="v22Next"><span>Scheduled</span><b>${safe(localTime(x.timeUtc))}</b></div><div class="v22Metrics two"><div><span>Consensus</span><b>${safe(e.consensus||e.forecast||'—')}</b></div><div><span>Previous</span><b>${safe(e.previous||'—')}</b></div></div>${p.trade?.status==='open'?'<div class="v22Note">A paper trade is open. Event risk is a warning only; its frozen entry, stop and target stay unchanged.</div>':''}</article>`}
  function researchCard(p){const news=(p.officialNews||[]).slice(0,3),model=p.model||{},trust=p.status?.dataTrust||{};return `<details class="v22Details"><summary><span>Research details</span><small>Data quality, model evidence & official policy context</small></summary><div class="v22DetailGrid"><div><span>Data source</span><b>${safe(trust.label||trust.level||'—')}</b><p>${safe(trust.reason||'No additional source note.')}</p></div><div><span>Model layer</span><b>${safe(model.route||'ABSTAIN')}</b><p>${safe(model.plain||'Model influence remains evidence-gated.')}</p></div></div>${news.length?`<div class="v22News"><h4>Recent official policy context</h4>${news.map(x=>`<div class="v22NewsItem"><span>${safe(x.source)}</span><b>${safe(x.title)}</b><small>${safe(x.timeUtc?localTime(x.timeUtc):'Recent')}</small></div>`).join('')}</div>`:'<div class="v22Quiet">No high-relevance official central-bank update is being surfaced right now.</div>'}<div class="v22Boundary">${safe(p.researchBoundary||'Research only; no broker execution truth.')}</div></details>`}
  function render(){const root=ensure(),p=currentPair();if(!root)return;if(!p){root.innerHTML='<div class="v22Loading">Loading the trader brief…</div>';return}const t=p.trade,primary=t?tradeCard(p):setupCard(p),secondary=t?setupCard(p):tradeCard(p);root.innerHTML=`<header class="v22Hero"><div class="v22HeroMain"><div class="v22Eyebrow">${safe(p.symbol)} · What matters now</div><h2>${safe(p.status?.headline||'V2 market brief')}</h2><p>${safe(p.status?.subhead||'V2 is observing the market.')}</p>${statusPills(p)}<div class="v22HeroNext"><span>Next</span><b>${safe(p.status?.next||'Wait for the next confirmed event.')}</b></div></div><div class="v22Quote"><b>${price(p.referencePrice)}</b><span>research reference</span><small>${safe(p.symbol)}</small></div></header><div class="v22Grid"><div class="v22Primary">${primary}${secondary}</div><div class="v22Side">${macroCard(p)}${researchCard(p)}</div></div>`}
  async function load(){if(loading)return;loading=true;try{const r=await fetch(ENDPOINT,{cache:'no-store'});if(!r.ok)throw new Error(`Trader Brief ${r.status}`);payload=await r.json();render()}catch(e){console.warn('V2.2 Trader Brief',e);const root=ensure();if(root&&!payload)root.innerHTML='<div class="v22Error"><b>Trader brief unavailable</b><span>The underlying research engine has not been changed. Try refresh shortly.</span></div>'}finally{loading=false}}
  document.addEventListener('click',e=>{if(e.target.closest('.pairSwitch,[data-pair]'))setTimeout(()=>{lastSymbol=currentSymbol();render()},80)});
  document.getElementById('refresh')?.addEventListener('click',()=>setTimeout(load,180));
  ensure();render();load();setInterval(()=>{if(document.hidden)return;const s=currentSymbol();if(s!==lastSymbol){lastSymbol=s;render()}},800);setInterval(()=>{if(!document.hidden)load()},30_000);
})();