(()=>{
const API={EURUSD:'https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/eurusd-market-lab',GBPUSD:'https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/market-lab?symbol=GBPUSD',XAUUSD:'https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/xau-state-engine'};
const PAPER='https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/paper-trade-engine?symbol=EURUSD,GBPUSD',MACRO='https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/macro-context',SIM='/v25-sim.json';
const SYMS=['EURUSD','GBPUSD','XAUUSD'],NAMES={EURUSD:'Euro / U.S. Dollar',GBPUSD:'British Pound / U.S. Dollar',XAUUSD:'Gold / U.S. Dollar'};let pick='EURUSD',local={},paper={trades:[]},macro=null,sim=null,busy=false;
const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),cap=v=>String(v??'—').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()),num=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—',money=v=>Number.isFinite(Number(v))?`$${Number(v).toFixed(2)}`:'—';
const state=s=>local[s]||{},trade=s=>(paper.trades||[]).filter(x=>x.symbol===s).find(x=>x.status==='open')||(paper.trades||[]).filter(x=>x.symbol===s).find(x=>x.status==='armed')||null,diag=s=>state(s).details?.diagnostics||{};
function px(s,v){return Number.isFinite(Number(v))?Number(v).toFixed(s==='XAUUSD'?2:5):'—'}
function action(s){const x=state(s),t=trade(s),z=Number(x.formation_stage||0);if(t?.status==='open')return['TRACK PAPER TRADE','good'];if(t?.status==='armed')return['WAIT FOR POI','warn'];if(z>=6)return[s==='XAUUSD'?'REVIEW POI':'POI READY','warn'];if(z===5)return['WAIT FOR POI','hold'];if(z===4)return['WAIT FOR BOS','hold'];if(z===3)return['WATCH SWEEP','hold'];if(z===1)return['WATCH LIQUIDITY',''];return['NO SETUP','']}
function next(s){const x=state(s),t=trade(s),z=Number(x.formation_stage||0);if(t?.status==='open')return`Track the frozen stop ${px(s,t.stop_price)} and target ${px(s,t.target_price)}.`;if(t?.status==='armed')return`Wait for the frozen midpoint ${px(s,t.entry_price)}. No fill is counted before price reaches it.`;if(z>=6)return s==='XAUUSD'?'A gold POI exists, but entries remain shadow-only until XAU validation clears.':'Watch the frozen POI and midpoint without changing its geometry.';if(z===5)return'BOS is confirmed. Wait for a fresh POI to be identified.';if(z===4)return'Wait for a completed same-direction BOS. Intrabar movement does not count.';if(z===3)return'Watch whether the sweep converts into a completed BOS.';if(z===1)return'Price is near liquidity. Wait for a clean sweep.';return'Nothing requires action yet. Wait for the next clean liquidity event.'}
function why(s){const x=state(s),d=diag(s),z=Number(x.formation_stage||0),dir=String(x.formation_direction||'').toLowerCase();if(z===4&&d.structureContext==='conflicting')return`A ${dir||'new'} liquidity sweep exists, but the higher-timeframe structure leans the other way. V2 needs BOS before the idea matures.`;if(z===4)return'A liquidity sweep is confirmed, but structure has not broken yet. The sweep alone is not enough.';if(z>=6)return`The sweep and BOS sequence matured into a fresh POI. ${s==='XAUUSD'?'Gold is still evidence-only for entries.':'The midpoint remains the frozen research comparator.'}`;if(z===1)return'Price is close to a liquidity level. This is an area to watch, not an entry by itself.';return`${cap(x.regime||'transition')} market with no mature V2 sequence requiring attention.`}
function macroText(s){const m=macro?.pairs?.[s]||(s==='XAUUSD'?macro?.pairs?.EURUSD:null),r=m?.nextRelease,k=Number(m?.minutesToNext);if(!r||!Number.isFinite(k))return null;const w=k<60?`${Math.max(0,Math.round(k))}m`:`${Math.max(0,Math.floor(k/60))}h ${Math.max(0,Math.round(k%60))}m`;return`${r.title} · ${w}`}
function fresh(s){const h=state(s).data_health||{},t=h.referenceMinute||h.lastM15Bar||h.generatedAt||state(s).as_of;if(!t)return'Unknown';const m=Math.max(0,Math.round((Date.now()-new Date(t).getTime())/60000));return m<=2?'Near-live':`${m}m old`}
function ensure(){let r=document.getElementById('v25Unified');if(r)return r;r=document.createElement('section');r.id='v25Unified';const sw=document.getElementById('pairSwitch');sw?.insertAdjacentElement('beforebegin',r);return r}
function simPart(s){const m=sim?.markets?.[s];if(!m)return'';return`<div class="v25Sim"><div class="v25SimHead"><b>Historical lens</b><span>$500 · 1% risk · 2022–2025</span></div><div class="v25SimGrid"><div class="v25SimCell"><span>Clean-path balance</span><b>${money(m.account?.clean?.ending_balance)}</b></div><div class="v25SimCell"><span>Win rate</span><b>${num(m.resolved_win_rate_pct,1)}%</b></div><div class="v25SimCell"><span>Fill rate</span><b>${num(m.fill_rate_pct,1)}%</b></div><div class="v25SimCell"><span>Ambiguity stress</span><b>${money(m.account?.pessimistic?.ending_balance)}</b></div></div></div>`}
function render(){const r=ensure(),x=state(pick),[a,tone]=action(pick),d=diag(pick),mt=macroText(pick),tf=[['D1',x.d1_trend],['H4',x.h4_trend],['H1',x.h1_trend],['M15',x.m15_trend]];r.innerHTML=`<div class="v25MarketTabs">${SYMS.map(s=>`<button data-v25="${s}" class="${pick===s?'active':''}"><span>${s}</span><small>${NAMES[s]}</small><b>${s==='XAUUSD'?'$':''}${px(s,state(s).reference_price)}</b><em>${action(s)[0]}</em></button>`).join('')}</div><div class="v25Deck"><div class="v25Top"><div><div class="v25Kicker">${pick} · What matters now</div><div class="v25Title"><h2>${a}</h2><span class="v25Price">${pick==='XAUUSD'?'$':''}${px(pick,x.reference_price)}</span></div></div><span class="v25Action ${tone}"><i class="v25Dot"></i>${a}</span></div><p class="v25Why">${safe(why(pick))}</p><div class="v25Next"><div class="v25Box"><span>What happens next</span><b>${safe(next(pick))}</b></div><div class="v25Box"><span>Market context</span><b>${safe(d.structureContext?`HTF ${cap(d.structureContext)} · ${cap(x.regime)}`:cap(x.regime))}</b></div></div><div class="v25Strip">${tf.map(q=>`<span class="v25Chip">${q[0]}<strong>${cap(q[1])}</strong></span>`).join('')}<span class="v25Chip">Data<strong>${fresh(pick)}</strong></span>${mt?`<span class="v25Chip">Event<strong>${safe(mt)}</strong></span>`:''}</div><div class="v25Actions"><button class="v25Btn primary" data-open="chart">Open chart</button><button class="v25Btn" data-open="research">Research</button><button class="v25Btn" data-open="ask">Ask V2</button></div><div class="v25ResearchBoundary">${pick==='XAUUSD'?'Gold is first-class for market intelligence, but entry authority remains shadow-only until gold-specific validation passes.':'Research/paper workflow only. No broker execution instruction.'}</div>${simPart(pick)}</div>`;r.querySelectorAll('[data-v25]').forEach(b=>b.onclick=()=>{pick=b.dataset.v25;syncLegacy();render()});r.querySelector('[data-open="chart"]')?.addEventListener('click',()=>{syncLegacy();if(typeof setView==='function')setView('chartView')});r.querySelector('[data-open="research"]')?.addEventListener('click',()=>{syncLegacy();if(typeof setView==='function')setView('evidenceView')});r.querySelector('[data-open="ask"]')?.addEventListener('click',()=>document.getElementById('v23Chat')?.scrollIntoView({behavior:'smooth',block:'center'}))}
function syncLegacy(){try{selected=pick;chartLoaded='';if(typeof states!=='undefined')states[pick]=state(pick);if(pick==='XAUUSD'&&typeof insights!=='undefined'){const x=state(pick),d=diag(pick),a=action(pick)[0];insights.XAUUSD={stats:{recentMeaningful:[]},campaign:{},sweeps:{},evidence:{relevant:{label:'Gold validation building',independentCampaigns:0,rawSweepOutcomes:0,note:'XAU evidence is collected separately.'}},brief:{attention:{label:a},researchPriority:{key:'observe',label:a,action:next(pick)},headline:x.formation_label||a,next:next(pick),context:d.structureContext,alignmentPct:d.alignmentPct,shiftRisk:d.shiftRisk,reasons:[why(pick)]}};TV.XAUUSD='OANDA:XAUUSD';NAME.XAUUSD=NAMES.XAUUSD}if(typeof render==='function')render()}catch(e){console.warn('V2.5 legacy sync',e)}}
function researchPanel(){const v=document.getElementById('evidenceView');if(!v)return;let r=document.getElementById('v25Research');if(!r){r=document.createElement('article');r.id='v25Research';r.className='card v25ResearchPanel';v.querySelector('.sectionHead')?.insertAdjacentElement('afterend',r)}if(!sim){r.innerHTML='<div class="cardLabel">V2.5 three-market simulation</div><h3>Common-protocol results are being generated.</h3>';return}const c=SYMS.map(s=>{const m=sim.markets[s],a=m.account?.clean,p=m.account?.pessimistic;return`<div class="v25ResearchCard"><span>${s}</span><b>${money(a?.ending_balance)}</b><small>${num(m.resolved_win_rate_pct,1)}% resolved win · ${m.resolved} resolved<br>Ambiguity stress ${money(p?.ending_balance)}</small></div>`}).join('');r.innerHTML=`<div class="cardLabel">V2.5 · Common-engine account study</div><h3>$500 across EURUSD, GBPUSD and XAUUSD</h3><p>Same midpoint, stop, 2.5R, 48-hour horizon and 1% compounding risk. Costs excluded.</p><div class="v25ResearchGrid">${c}<div class="v25ResearchCard"><span>Combined</span><b>${money(sim.portfolio?.account?.clean?.ending_balance)}</b><small>${sim.portfolio?.resolved||0} resolved<br>Ambiguity stress ${money(sim.portfolio?.account?.pessimistic?.ending_balance)}</small></div></div><div class="v25GoldGate">Clean-path figures exclude bars whose event ordering cannot be defended. Ambiguity-stress treats uncertain filled cases as -1R. The gap is a data-quality warning, not a forecast range.</div>`}
async function load(){if(busy)return;busy=true;try{const rs=await Promise.allSettled([...SYMS.map(s=>fetch(API[s],{cache:'no-store'})),fetch(PAPER,{cache:'no-store'}),fetch(MACRO,{cache:'no-store'}),fetch(SIM,{cache:'no-store'})]);for(let i=0;i<3;i++)if(rs[i].status==='fulfilled'&&rs[i].value.ok){const j=await rs[i].value.json();local[SYMS[i]]=j.state||j}if(rs[3].status==='fulfilled'&&rs[3].value.ok)paper=await rs[3].value.json();if(rs[4].status==='fulfilled'&&rs[4].value.ok)macro=await rs[4].value.json();if(rs[5].status==='fulfilled'&&rs[5].value.ok)sim=await rs[5].value.json();syncLegacy();render();researchPanel()}catch(e){console.warn('V2.5',e)}finally{busy=false}}
document.body.classList.add('v25CompactIntro');load();setInterval(load,60000);document.getElementById('refresh')?.addEventListener('click',load);
})();
