(()=>{
const URL='https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/xau-state-engine',MACRO='https://uykjgyqoptsvvkaifphm.supabase.co/functions/v1/macro-context';
const style=document.createElement('style');style.textContent=`
.xauResearch{margin:10px 0 18px;border:1px solid rgba(255,255,255,.10);background:linear-gradient(180deg,rgba(255,255,255,.055),rgba(255,255,255,.025));border-radius:20px;padding:16px 18px;box-shadow:0 12px 36px rgba(0,0,0,.16)}
.xauTop{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.xauEyebrow{font-size:11px;letter-spacing:.12em;text-transform:uppercase;opacity:.62}.xauResearch h3{margin:5px 0 3px;font-size:20px}.xauPrice{font-size:24px;font-weight:750;white-space:nowrap}.xauGrid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:13px}.xauCell{padding:10px 11px;border-radius:14px;background:rgba(255,255,255,.045)}.xauCell span{display:block;font-size:11px;opacity:.6;margin-bottom:4px}.xauCell b{font-size:13px}.xauCall{margin-top:12px;padding:11px 12px;border-radius:14px;background:rgba(255,255,255,.045);font-size:13px;line-height:1.45}.xauCall strong{display:block;margin-bottom:3px}.xauMacro{margin-top:8px;padding:10px 12px;border-radius:14px;background:rgba(255,255,255,.04);font-size:12px;line-height:1.4}.xauHealth{margin-top:9px;font-size:11px;opacity:.58}.xauWait{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;border-radius:999px;background:rgba(255,255,255,.07);font-size:11px;font-weight:700}.xauDot{width:7px;height:7px;border-radius:50%;background:currentColor}@media(max-width:850px){.xauGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.xauTop{align-items:center}.xauPrice{font-size:20px}}
`;document.head.appendChild(style);
const cap=x=>String(x??'—').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()),n=(x,d=2)=>Number.isFinite(Number(x))?Number(x).toFixed(d):'—';
function mount(){let el=document.getElementById('xauResearch');if(el)return el;el=document.createElement('section');el.id='xauResearch';el.className='xauResearch';const sw=document.getElementById('pairSwitch');(sw?.parentNode||document.querySelector('.wrap')||document.body).insertBefore(el,sw?.nextSibling||null);return el}
function macroView(m){const x=m?.pairs?.EURUSD?.nextRelease,mins=Number(m?.pairs?.EURUSD?.minutesToNext);if(!x||!Number.isFinite(mins))return{label:'No high-impact USD event',text:'No confirmed high-impact USD event is currently attached to the gold state.'};const clock=mins<=0?'release window':mins<60?`${Math.max(0,Math.round(mins))}m`:`${Math.floor(mins/60)}h ${Math.round(mins%60)}m`;return{label:`${x.title} · ${clock}`,text:`${x.impactLabel||'HIGH'} impact · ${x.why||'USD macro event can increase gold volatility.'} This is a volatility/risk modifier, not a directional signal.`}}
function render(j,m){const s=j?.state||{},h=s.data_health||{},d=s.details?.diagnostics||{},trend=[s.d1_trend,s.h4_trend,s.h1_trend,s.m15_trend],aligned=trend.every(x=>x==='bullish')?'Bullish all TF':trend.every(x=>x==='bearish')?'Bearish all TF':'Mixed TF',mv=macroView(m);const action=s.formation_stage>=6?'REVIEW':s.formation_stage>=3?'WAIT':'WATCH',eventSoon=Number(m?.pairs?.EURUSD?.minutesToNext)<=120,reason=s.formation_stage>=3&&d.structureContext==='conflicting'?'Formation direction conflicts with higher-timeframe structure. Wait for stronger confirmation and gold-specific validation.':s.formation_stage>=6?'A POI exists, but XAU entries are still shadow-only while gold calibration builds.':'No validated XAU trade entry is active.',eventNote=eventSoon?' A high-impact USD release is also close, so V2 will not treat pre-event geometry as a normal quiet-session setup.':'';mount().innerHTML=`<div class="xauTop"><div><div class="xauEyebrow">Gold research · XAUUSD</div><h3>${cap(s.formation_label||'Reading gold')}</h3><span class="xauWait"><i class="xauDot"></i>${action} · research only</span></div><div class="xauPrice">$${n(s.reference_price,2)}</div></div><div class="xauGrid"><div class="xauCell"><span>Higher timeframes</span><b>${aligned}</b></div><div class="xauCell"><span>Regime</span><b>${cap(s.regime)}</b></div><div class="xauCell"><span>V2 stage</span><b>${s.formation_stage??'—'}/8 · ${cap(s.formation_direction||'none')}</b></div><div class="xauCell"><span>15m ATR</span><b>$${n(s.atr15,2)}</b></div><div class="xauCell"><span>USD event clock</span><b>${mv.label}</b></div></div><div class="xauCall"><strong>What V2 does now</strong>${reason}${eventNote}</div><div class="xauMacro"><strong>Macro context:</strong> ${mv.text}</div><div class="xauHealth">Dukascopy near-live reference · latest minute ${h.referenceMinute?new Date(h.referenceMinute).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—'} · last completed M15 ${h.lastM15Bar?new Date(h.lastM15Bar).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—'} · indicative data, not broker execution truth</div>`}
async function load(){try{const [a,b]=await Promise.all([fetch(URL,{cache:'no-store'}),fetch(MACRO,{cache:'no-store'})]),j=await a.json(),m=b.ok?await b.json():null;if(!a.ok)throw Error(j?.error||a.status);render(j,m)}catch(e){mount().innerHTML=`<div class="xauEyebrow">Gold research · XAUUSD</div><h3>Gold feed is temporarily unavailable</h3><div class="xauHealth">The Forex workflow is unaffected. V2 will retry automatically.</div>`}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();setInterval(load,60000);
})();